### ISSUE TITLE
Error after first run

### ISSUE THREAD

**Issue by LudovicoPapalia** [elebumm/RedditVideoMakerBot#1012]
Hey, i've installed the requirements and cloned the repo

after running for the first time main.py i get this error

`Traceback (most recent call last):
  File "/Users/user/Downloads/RedditVideoMakerBot-master/main.py", line 10, in <module>
    from video_creation.background import (
  File "/Users/user/Downloads/RedditVideoMakerBot-master/video_creation/background.py", line 7, in <module>
    from moviepy.editor import VideoFileClip
  File "/Users/user/miniforge3/lib/python3.9/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Users/user/miniforge3/lib/python3.9/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/Users/user/miniforge3/lib/python3.9/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/Users/user/miniforge3/lib/python3.9/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/Users/user/miniforge3/lib/python3.9/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/Users/user/miniforge3/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Users/user/miniforge3/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/Users/user/miniforge3/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.`

so i run this 
`pip install ffmpeg`

but i get this 
`Requirement already satisfied: ffmpeg in /Users/user/miniforge3/lib/python3.9/site-packages (1.4)`

after running the main.py again i get always the same error

(i'm using a mac m1)

How can i fix it?
Thanks a lot! Lp

I'm now thinking that the error says ` ffmpeg exe`... **exe**
Why, given that i'm on mac? What am i doing wrong?

Thanks

**Comment by Anvilator-web** [comment]
Try `pip3 install ffmpeg`

**Comment by JasonLovesDoggo** [comment]
> Try `pip3 install ffmpeg` 

If this fails add FFMPEG to path
