### ISSUE TITLE
Toml module not found

### ISSUE THREAD

**Issue by AloW0304** [elebumm/RedditVideoMakerBot#1028]
Done all the steps for installation, however when I run main.py I get the error message

Traceback (most recent call last):
  File "/Users/Desktop/RedditVideoMakerBot-master/main.py", line 5, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/Users/Desktop/RedditVideoMakerBot-master/reddit/subreddit.py", line 3, in <module>
    from utils import settings
  File "/Users/Desktop/RedditVideoMakerBot-master/utils/settings.py", line 2, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'

**Comment by chillingcone426** [comment]
Getting same problem and I tried installing it but it says that its already satisfied

**Comment by Denotess** [comment]
Try running it with "py" command or reinstall python. Worked for me.
