### ISSUE TITLE
ffmpeg?

### ISSUE THREAD

**Issue by Alexfost3** [elebumm/RedditVideoMakerBot#1078]
when running main.py i get a error near the end of the message it reads "untimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable."

**Comment by Alexfost3** [comment]
Alexs-MacBook-Air:RedditVideoMakerBot alexmendez$ python3 main.py
Traceback (most recent call last):
  File "/Users/alex/RedditVideoMakerBot/main.py", line 10, in <module>
    from video_creation.background import (
  File "/Users/alex/RedditVideoMakerBot/video_creation/background.py", line 7, in <module>
    from moviepy.editor import VideoFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

**Comment by saqmadiq94** [comment]
Im having the same porblem. What was the solution?

**Comment by RothWho** [comment]
someone has find the issue? im having the same problem too

**Comment by jakestrouse00** [comment]
I am having the same issue on an M1 mac. I used a clean Python 3.10 virtual env.
