### ISSUE TITLE
Missing Rich But I have It Downloaded?

### ISSUE THREAD

**Issue by 101plusfourty** [elebumm/RedditVideoMakerBot#110]
PS C:\Users\user\Downloads\RedditVideoMakerBot-master> py .\main.py
Traceback (most recent call last):
  File "C:\Users\user\Downloads\RedditVideoMakerBot-master\main.py", line 1, in <module>
    from utils.console import print_markdown
  File "C:\Users\user\Downloads\RedditVideoMakerBot-master\utils\console.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
PS C:\Users\user\Downloads\RedditVideoMakerBot-master> pip insatll rich
ERROR: unknown command "insatll" - maybe you meant "install"
PS C:\Users\user\Downloads\RedditVideoMakerBot-master> pip install rich
Requirement already satisfied: rich in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (12.4.4)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from rich) (2.12.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from rich) (0.9.1)
WARNING: There was an error checking the latest version of pip.
PS C:\Users\user\Downloads\RedditVideoMakerBot-master>

**Comment by Kamushy** [comment]
try removing it and reinstalling it with pip3

**Comment by Hykaaru** [comment]
make sure you install rich on the version of python that will run the code. uninstall all other python variants then uninstall rich and its dependencies and install them again

**Comment by FreebieII** [comment]
Hi @101plusfourty,


I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
