### ISSUE TITLE
error on mp3 generation

### ISSUE THREAD

**Issue by Spark61** [elebumm/RedditVideoMakerBot#1119]
**Describe the bug**
When I run the main file it gives an error when generating the mp3 file, this only happens to me with this one reddit question:
If you could make one illegal thing legal what would it be and why? 

**To Reproduce**
my config:
```
[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
storymode = false

[settings.background]
background_choice = "minecraft"

[settings.tts]
choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_006"

[reddit.creds]
client_id = "****"
client_secret = "***"
username = "***"
password = "***"
2fa = false

[reddit.thread]
random = false
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
post_lang = "en"
min_comments = 20
```

**Console**
```
██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

                                                                               
                                                                               
    Thanks for using this tool! Feel free to contribute to this project on     
  GitHub! If you have any questions, feel free to reach out to me on Twitter   
  or submit a GitHub issue. You can find solutions to many common problems in  
                               the Documentation                               
                                                                               
                                                                               
┌─────────────────────────────────────────────────────────────────────────────┐
│ You are using v2.3 of the bot                                               │
└─────────────────────────────────────────────────────────────────────────────┘
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set 
variables, please input the correct values.
┌─────────────────────────────────────────────────────────────────────────────┐
│ on the 1st iteration of 1                                                   │
└─────────────────────────────────────────────────────────────────────────────┘
Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                │
└─────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit from TOML config
NSFW Post Detected. Skipping...
NSFW Post Detected. Skipping...
Video will be: If you could make one illegal thing legal what would it be and 
why? 👍
Thread has 12502 upvotes
Thread has a upvote ratio of 94.0%
Thread has 8002 comments
Received subreddit threads Successfully.
┌─────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                 │
└─────────────────────────────────────────────────────────────────────────────┘
Translating Text...
Translating Text...
Translating Text...
Translating Text...
Translating Text...
Translating Text...
Translating Text...
Translating Text...
Translating Text...
Saving... ---------------------------------------- 0.4 it/s  
Traceback (most recent call last):
  File "E:\Coding\RedditVideoMakerBot\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 285, in ffmpeg_parse_infos
    line = [l for l in lines if keyword in l][index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Coding\RedditVideoMakerBot\main.py", line 65, in <module>
    run_many(config["settings"]["times_to_run"])
  File "E:\Coding\RedditVideoMakerBot\main.py", line 56, in run_many
    main()
  File "E:\Coding\RedditVideoMakerBot\main.py", line 42, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "E:\Coding\RedditVideoMakerBot\video_creation\voices.py", line 48, in save_text_to_mp3
    return text_to_mp3.run()
  File "E:\Coding\RedditVideoMakerBot\TTS\engine_wrapper.py", line 73, in run
    self.split_post(comment["comment_body"], idx)  # Split the comment
  File "E:\Coding\RedditVideoMakerBot\TTS\engine_wrapper.py", line 96, in split_post
    split_files.append(AudioFileClip(f"{self.path}/{idx}-{idy - offset}.part.mp3"))
  File "E:\Coding\RedditVideoMakerBot\venv\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "E:\Coding\RedditVideoMakerBot\venv\lib\site-packages\moviepy\audio\io\readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "E:\Coding\RedditVideoMakerBot\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 289, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: failed to read the duration of file %s.\n"
OSError: MoviePy error: failed to read the duration of file assets/temp/mp3/5-1.part.mp3.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mp3 @ 00000186953e8e40] Format mp3 detected only with low score of 1, misdetection possible!
[mp3 @ 00000186953e8e40] Failed to read frame size: Could not seek to 1026.
assets/temp/mp3/5-1.part.mp3: Invalid argument


Process finished with exit code 1
```

**System (please complete the following information):**

- Python Version: Python 3.10
- OS: Windows 11
- App version / Branch: master branch

**Comment by JasonLovesDoggo** [comment]
Delete the assets folder and rerun

**Comment by sarimwaniR** [comment]
did not work
