### ISSUE TITLE
end issue

### ISSUE THREAD

**Issue by Hykaaru** [elebumm/RedditVideoMakerBot#116]
PS C:\Users\ionut\Desktop\RedditVideoMakerBot-master> python main.py

                Thanks for using this tool! 😊 Feel free to contribute to this project on GitHub!. If you have any questions, feel free to reach out to me on Twitter or submit a GitHub issue.

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Getting AskReddit threads...                                                                                                                                                                                 │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Video will be: What movie/tv show clearly didn’t research the subject it tackled? 👍
Received AskReddit threads Successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Saving Text to MP3 files 🎶                                                                                                                                                                                  │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1 it/s  
Saved Text to MP3 files Successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Downloading Screenshots of Reddit Posts 📷                                                                                                                                                                   │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Launching Headless Browser...
Downloading screenshots... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.4 it/s  
Screenshots downloaded Successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Finding a spot in the background video to chop...✂️
│
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Moviepy - Running:
Moviepy - Command successful
Background video chopped successfully! 🎉
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Creating the final video 🎥                                                                                                                                                                                  │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Traceback (most recent call last):
  File "main.py", line 22, in <module>
    final_video = make_final_video(number_of_comments)
  File "C:\Users\ionut\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 22, in make_final_video
    VideoFileClip("assets/mp4/clip.mp4")
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "C:\Users\ionut\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 37, in __init__
    self.fps = infos['video_fps']
KeyError: 'video_fps'

---

any ideas?

**Comment by Hykaaru** [comment]
any ideas for

keyerror: 'video_fps' ??

**Comment by CallumIO** [comment]
Closing due to being stale, reopen if issue reoccurs in the newest version
