### ISSUE TITLE
KeyError: 'video_fps'

### ISSUE THREAD

**Issue by AgrTheDev** [elebumm/RedditVideoMakerBot#118]
```
Traceback (most recent call last):
  File "E:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 22, in <module>
    final_video = make_final_video(number_of_comments)
  File "E:\Users\User\Downloads\RedditVideoMakerBot-master\video_creation\final_video.py", line 22, in make_final_video
    VideoFileClip("assets/mp4/clip.mp4")
  File "E:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "E:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 38, in __init__
    self.fps = infos['video_fps']
KeyError: 'video_fps'
```
Full error

**Comment by AgrTheDev** [comment]
Never mind I don’t know what I did but I downloaded the repo and re-ran the program and it works
