### ISSUE TITLE
line 82, in run_many(config["settings"]["times_to_run"])

### ISSUE THREAD

**Issue by TNAHOM** [elebumm/RedditVideoMakerBot#1191]
[15:28:08]  Video Will Be: 50 Seconds Long                    final_video.py:84
The results folder didn't exist so I made it
Traceback (most recent call last):
  File "C:\Users\Nahom tamirat.DESKTOP-O0JRFDT\Desktop\PROJECT\tik_plan\RedditVideoMakerBot-master\main.py", line 82, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Nahom tamirat.DESKTOP-O0JRFDT\Desktop\PROJECT\tik_plan\RedditVideoMakerBot-master\main.py", line 61, in run_many
    main()
  File "C:\Users\Nahom tamirat.DESKTOP-O0JRFDT\Desktop\PROJECT\tik_plan\RedditVideoMakerBot-master\main.py", line 53, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\Nahom tamirat.DESKTOP-O0JRFDT\Desktop\PROJECT\tik_plan\RedditVideoMakerBot-master\video_creation\final_video.py", line 143, in make_final_video
    final = Video(final).add_watermark(
  File "C:\Users\Nahom tamirat.DESKTOP-O0JRFDT\Desktop\PROJECT\tik_plan\RedditVideoMakerBot-master\utils\video.py", line 50, in add_watermark
    img_clip = self._create_watermark(text, redditid, fontsize=fontsize, opacity=opacity)
  File "C:\Users\Nahom tamirat.DESKTOP-O0JRFDT\Desktop\PROJECT\tik_plan\RedditVideoMakerBot-master\utils\video.py", line 37, in _create_watermark
    im.save(path)
  File "C:\Users\Nahom tamirat.DESKTOP-O0JRFDT\Desktop\RedditVideoMakerBot-master\new\lib\site-packages\PIL\Image.py", line 2297, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './assets/temp/{id}/png/watermark.png'

**Comment by JasonLovesDoggo** [comment]
Please reopen with more information
