### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 54] Connection reset by peer>

### ISSUE THREAD

**Issue by JiahuaLink** [elebumm/RedditVideoMakerBot#1192]
/usr/local/bin/python3.9 /Users/jiahualink/Code/RedditVideoMakerBot-master/main.py
Using Hong Kong server backend.

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

                                                                                
                                                                                
     Thanks for using this tool! Feel free to contribute to this project on     
   GitHub! If you have any questions, feel free to reach out to me on Twitter   
  or submit a GitHub issue. You can find solutions to many common problems in   
                               the Documentation                                
                                                                                
                                                                                
╭──────────────────────────────────────────────────────────────────────────────╮
│ You are using an older version (2.4.1) of the bot. Download the newest       │
│ version (2.4.2) from                                                         │
│ https://github.com/elebumm/RedditVideoMakerBot/releases/latest               │
╰──────────────────────────────────────────────────────────────────────────────╯
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set 
variables, please input the correct values.
╭──────────────────────────────────────────────────────────────────────────────╮
│ on the 1st iteration of 1                                                    │
╰──────────────────────────────────────────────────────────────────────────────╯
Logging into Reddit.
╭──────────────────────────────────────────────────────────────────────────────╮
│ Getting subreddit threads...                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
Using subreddit: r/dankvideos from TOML config
This post was pinned by moderators. Skipping...
Video will be: peppers 👍
Thread has 5219 upvotes
Thread has a upvote ratio of 93.0%
Thread has 72 comments
Received subreddit threads Successfully.
Thread ID is wtqlwx
╭──────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.7 it/s  
Saved Text to MP3 files successfully.
╭──────────────────────────────────────────────────────────────────────────────╮
│ Downloading screenshots of reddit posts...                                   │
╰──────────────────────────────────────────────────────────────────────────────╯
Launching Headless Browser...
Skipping translation...

Downloading screenshots... ━━━━━━━━━━━━                              31% 0:01:37
Screenshots downloaded Successfully.
╭──────────────────────────────────────────────────────────────────────────────╮
│ We need to download the backgrounds videos. they are fairly large but it's   │
│ only done once. 😎                                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
Downloading the backgrounds videos... please be patient 🙏 
Downloading gta-stunt-race.mp4 from https://www.youtube.com/watch?v=qGa9kWREOnE
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1347, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiahualink/Code/RedditVideoMakerBot-master/main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/jiahualink/Code/RedditVideoMakerBot-master/main.py", line 62, in run_many
    main()
  File "/Users/jiahualink/Code/RedditVideoMakerBot-master/main.py", line 52, in main
    download_background(bg_config)
  File "/Users/jiahualink/Code/RedditVideoMakerBot-master/video_creation/background.py", line 60, in download_background
    YouTube(uri, on_progress_callback=on_progress).streams.filter(res="1080p").first().download(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytube/streams.py", line 252, in download
    for chunk in request.stream(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytube/request.py", line 157, in stream
    response = _execute_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 518, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 535, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 495, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1390, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1350, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 54] Connection reset by peer>

Process finished with exit code 1

**Comment by JasonLovesDoggo** [comment]
Not a problem on our end.
