### ISSUE TITLE
[Bug]: Downloading backgrounds videos

### ISSUE THREAD

**Issue by Haidule** [elebumm/RedditVideoMakerBot#1209]
### Describe the bug

There is an problem acquiring when bot tries to download background video.

Launching Headless Browser...
Skipping translation...
Downloading screenshots...                                            0% -:--:--
Screenshots downloaded Successfully.
╭──────────────────────────────────────────────────────────────────────────────╮
│ We need to download the backgrounds videos. they are fairly large but it's   │
│ only done once. 😎                                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
Downloading the backgrounds videos... please be patient 🙏 
Downloading gta-stunt-race.mp4 from https://www.youtube.com/watch?v=qGa9kWREOnE
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/haiadas/Desktop/RedditVideoMakerBot-2.4.2/main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/haiadas/Desktop/RedditVideoMakerBot-2.4.2/main.py", line 62, in run_many
    main()
  File "/Users/haiadas/Desktop/RedditVideoMakerBot-2.4.2/main.py", line 52, in main
    download_background(bg_config)
  File "/Users/haiadas/Desktop/RedditVideoMakerBot-2.4.2/video_creation/background.py", line 60, in download_background
    YouTube(uri, on_progress_callback=on_progress).streams.filter(res="1080p").first().download(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

### Reproduction Steps

i tried different methods by changing background video theme but it didn't work.

[settings]
allow_nsfw = false
theme = "light"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = false

[settings.background]
background_choice = "miecraft"

[settings.tts]
voice_choice = "googletranslate"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_006"
python_voice = "1"
py_voice_num = "2"

[reddit.creds]
client_id = "xxxxxxx"
client_secret = "xxxxxxxx"
username = "xxxxxxx"
password = "xxxxxx"
2fa = false

[reddit.thread]
random = false
subreddit = "shortstories"
post_id = ""
max_comment_length = 250
post_lang = ""
min_comments = 20

### Expected behavior

Expected to cut the dowloaded video and. process it.

### System Information

Operating System : [Mac os. 12.5.1]
Python version : [e.g. Python 3.10]
App version / Branch [2.4.2]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Haidule** [comment]
phyton 3.10 folder -> Install Certificates.command
