### ISSUE TITLE
error downloading minecraft video 

### ISSUE THREAD

**Issue by sykeze** [elebumm/RedditVideoMakerBot#121]
getting these errors and idk what to since ima noob lmao
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Getting AskReddit threads...                                                                                                   │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Video will be: What are the best attitudes and mindsets for life? 👍
Received AskReddit threads Successfully.
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files 🎶                                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.3 it/s
Saved Text to MP3 files Successfully.
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Downloading Screenshots of Reddit Posts 📷                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Launching Headless Browser...
Downloading screenshots... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.3 it/s
Screenshots downloaded Successfully.
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ We need to download the Minecraft background video. This is fairly large but it's only done once. 😎                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Downloading the background video... please be patient 🙏
Traceback (most recent call last):
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Trick\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 20, in <module>
    download_background()
  File "c:\Users\Trick\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\background.py", line 26, in download_background
    YouTube("https://www.youtube.com/watch?v=n_Dv4JMiwK8").streams.filter(
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams        
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams    
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature 
    cipher = Cipher(js=js)
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\Trick\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
PS C:\Users\Trick\Downloads\RedditVideoMakerBot-master>

**Comment by null3000** [comment]
You only  need to download the background file once. This is a hacky soultion but it worked for me:
1. use a youtube to mp4 website like this one (https://onlinevideoconverter.pro/en81/youtube-downloader-mp4)
2. paste the youtube link into it (https://www.youtube.com/watch?v=n_Dv4JMiwK8)
3. download in 720p
4. rename the video to "background.mp4"
5. create a new folder inside of "assets" called "mp4"
6. drag the finished mp4 into the mp4 file
8. enjoy!
please lmk if you have any more issues.

**Comment by jacobjake1** [comment]
> You only need to download the background file once. This is a hacky soultion but it worked for me:
> 
> 1. use a youtube to mp4 website like this one (https://onlinevideoconverter.pro/en81/youtube-downloader-mp4)
> 2. paste the youtube link into it (https://www.youtube.com/watch?v=n_Dv4JMiwK8)
> 3. download in 720p
> 4. rename the video to "background.mp4"
> 5. create a new folder inside of "assets" called "mp4"
> 6. drag the finished mp4 into the mp4 file
> 7. enjoy!
>    please lmk if you have any more issues.

I did that now im getting this; https://pastebin.com/raw/WLfDQUAk

**Comment by FreebieII** [comment]
Hi @sykeze 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
