### ISSUE TITLE
[Bug]: OSError: MoviePy error: failed to read the first frame 

### ISSUE THREAD

**Issue by djole1611** [elebumm/RedditVideoMakerBot#1227]
### Describe the bug

Crashing while creating the final video. 
`Traceback (most recent call last):
  File "/home/dyolo/Desktop/RedditVideoMakerBot/main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/home/dyolo/Desktop/RedditVideoMakerBot/main.py", line 62, in run_many
    main()
  File "/home/dyolo/Desktop/RedditVideoMakerBot/main.py", line 54, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "/home/dyolo/Desktop/RedditVideoMakerBot/video_creation/final_video.py", line 72, in make_final_video
    VideoFileClip(f"assets/temp/{id}/background.mp4")
  File "/home/dyolo/.local/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/home/dyolo/.local/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "/home/dyolo/.local/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/x1sgnn/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
`
In asset/temp i have a file with mp3 and png folder. Beside that i have mp4  file  with  1  second duration.

### Reproduction Steps

Installing all  packages and run it 20+ times. All same results

### Expected behavior

Expected  to finish all.

### System Information

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
Python 3.10.4

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
Duplicate
