### ISSUE TITLE
[Bug]: Can't open the python script

### ISSUE THREAD

**Issue by lowegb** [elebumm/RedditVideoMakerBot#1249]
### Describe the bug

When I try open the python file I get an error message: 

Traceback (most recent call last):
  File "/Users/harrylowe/RedditVideoMakerBot-master/main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/Users/harrylowe/RedditVideoMakerBot-master/reddit/subreddit.py", line 44
    match e.response.status_code:
                ^
SyntaxError: invalid syntax

(I am on python 3.10.7)

### Reproduction Steps

Ran the main.py file

### Expected behavior

For it to run succesfully 

### System Information

Operating System : [macOS Monterey 12.5.1]
Python version : [e.g. Python 3.10.7]
MacBook air M1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by lowegb** [comment]
The syntax error is on the e in match e.response.status_code, it wouldn't let me move it

**Comment by lowegb** [comment]
fixed it
