### ISSUE TITLE
[Bug]: after fresh install subreddit.py has error and can't call reddit api, no config file in root

### ISSUE THREAD

**Issue by Archemike** [elebumm/RedditVideoMakerBot#1253]
### Describe the bug

config file won't exist or create on install. docs state there is config in root and can't find one.  

### Reproduction Steps

installed with the mac linux bash command after i hit y   to install then says config file issue can't call reddit api

### Expected behavior

bot runs and config file works on install

### Screenshots

The bot is installed, want to run it?Continue? (y/n)
y
Traceback (most recent call last):
  File "/Users/scripts/RedditVideoMakerBot-master/main.py", line 9, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/Users//scripts/RedditVideoMakerBot-master/reddit/subreddit.py", line 44
    match e.response.status_code:
          ^
SyntaxError: invalid syntax

### System Information

Operating System : [macbook air m1
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

have tried manually creating the config file and to no avail same error.  reinstalled repo and same error

**Comment by Archemike** [comment]
use python3.10 and update. repo on git clone still wrong version and not latest needs updating.
