### ISSUE TITLE
[Bug]: IOE/OSE errors when running main.py script

### ISSUE THREAD

**Issue by jdubindaclub** [elebumm/RedditVideoMakerBot#1256]
### Describe the bug

After setting up my configuration, I got the following error:
Traceback (most recent call last):
  File "/Users/jdubindaclub/Desktop/RedditVideoMakerBot/main.py", line 94, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/jdubindaclub/Desktop/RedditVideoMakerBot/main.py", line 62, in run_many
    main()
  File "/Users/jdubindaclub/Desktop/RedditVideoMakerBot/main.py", line 54, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "/Users/jdubindaclub/Desktop/RedditVideoMakerBot/video_creation/final_video.py", line 80, in make_final_video
    audio_clips = [AudioFileClip(f"assets/temp/{id}/mp3/{i}.mp3") for i in range(number_of_clips)]
  File "/Users/jdubindaclub/Desktop/RedditVideoMakerBot/video_creation/final_video.py", line 80, in <listcomp>
    audio_clips = [AudioFileClip(f"assets/temp/{id}/mp3/{i}.mp3") for i in range(number_of_clips)]
  File "/Users/jdubindaclub/opt/anaconda3/lib/python3.9/site-packages/moviepy/audio/io/AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "/Users/jdubindaclub/opt/anaconda3/lib/python3.9/site-packages/moviepy/audio/io/readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/Users/jdubindaclub/opt/anaconda3/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file assets/temp/wvumcf/mp3/0.mp3 could not be found!
Please check that you entered the correct path.

 I'm not sure what I could have pathed incorrectly. Not sure what is causing this issue. 

### Reproduction Steps

Tried reinstalling the repository, same issue.

### Expected behavior

After running main.py, I expected a the video to be sent to the results folder, but the video did not make it through the process.

### Screenshots

<img width="567" alt="Screen Shot 2022-09-17 at 3 20 54 AM" src="https://user-images.githubusercontent.com/92970259/190849805-b89bdad8-6637-4c25-b560-d209ff3a84f9.png">

### System Information

Operating System : Mac OS 12.5
Python version : 3.9.7
App version: 2.4.2 (latest)
Branch: develop

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by FlexingWithTech** [comment]
If it ain't broke don't fix it. It was working well 2 days ago now it's broken.

**Comment by jdubindaclub** [comment]
Are you saying this same thing is happening for everyone else? Or did I misunderstand your comment?

**Comment by FlexingWithTech** [comment]
Well, I don't know for anyone else but for me yes. It is broken with some subreddits for some reason.

**Comment by jdubindaclub** [comment]
I'm dumb. I actually watched my terminal run the script this time and noticed I didn't have the ffmpeg package installed. Up and running now that I have that.

**Comment by FlexingWithTech** [comment]
I'll try that and report back
