### ISSUE TITLE
re.error: nothing to repeat at position 2

### ISSUE THREAD

**Issue by diz-duckz** [elebumm/RedditVideoMakerBot#126]
not sure why this is happening

**Comment by diz-duckz** [comment]
Thanks for using this tool! 😊 Feel free to contribute to this project on GitHub!. If you have any questions, feel free to reach out to me on Twitter or submit a GitHub issue.


┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting AskReddit threads...                                                                                                                                                                                   │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Video will be: What’s a better phrase than “I’m cumming”? 👍
Received AskReddit threads Successfully.
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files 🎶                                                                                                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ---------------------------------------- 2.4 it/s
Saved Text to MP3 files Successfully.
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading Screenshots of Reddit Posts 📷                                                                                                                                                                     │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Post is NSFW. You are spicy... 🔥
Downloading screenshots... ---------------------------------------- 0.3 it/s
Screenshots downloaded Successfully.
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ We need to download the Minecraft background video. This is fairly large but it's only done once. 😎                                                                                                           │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Downloading the background video... please be patient 🙏
Traceback (most recent call last):
  File "C:\Users\liamr\Downloads\RedditVideoMakerBot-master\main.py", line 20, in <module>
    download_background()
  File "C:\Users\liamr\Downloads\RedditVideoMakerBot-master\video_creation\background.py", line 26, in download_background
    YouTube("https://www.youtube.com/watch?v=n_Dv4JMiwK8").streams.filter(
  File "C:\Users\liamr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\liamr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\liamr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\liamr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytube\cipher.py", line 30, in __init__
    var_regex = re.compile(r"^$*\w+\W")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\re.py", line 251, in compile
    return _compile(pattern, flags)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\sre_parse.py", line 950, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 2

**Comment by reinkdesigns** [comment]
getting same error

**Comment by null3000** [comment]
You only  need to download the background file once. This is a hacky soultion but it worked for me:
1. use a youtube to mp4 website like this one (https://onlinevideoconverter.pro/en81/youtube-downloader-mp4)
2. paste the youtube link into it (https://www.youtube.com/watch?v=n_Dv4JMiwK8)
3. download in 720p
4. rename the video to "background.mp4"
5. create a new folder inside of "assets" called "mp4"
6. drag the finished mp4 into the mp4 file
8. enjoy!
please lmk if you have any more issues.

**Comment by dizduckz** [comment]
> You only need to download the background file once. This is a hacky soultion but it worked for me:
> 
> 1. use a youtube to mp4 website like this one (https://onlinevideoconverter.pro/en81/youtube-downloader-mp4)
> 2. paste the youtube link into it (https://www.youtube.com/watch?v=n_Dv4JMiwK8)
> 3. download in 720p
> 4. rename the video to "background.mp4"
> 5. create a new folder inside of "assets" called "mp4"
> 6. drag the finished mp4 into the mp4 file
> 7. enjoy!
>    please lmk if you have any more issues.

Thank you so much man!

**Comment by FreebieII** [comment]
Hi @diz-duckz 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
