### ISSUE TITLE
[Bug]: Fail after skipping translation...

### ISSUE THREAD

**Issue by stogidout** [elebumm/RedditVideoMakerBot#1282]
### Describe the bug

When bot is running it get stuck on 

`Launching Headless Browser...
Skipping translation...
Traceback (most recent call last):
  File "/home/stogi/RedditVideoMakerBot/main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/home/stogi/RedditVideoMakerBot/main.py", line 62, in run_many
    main()
  File "/home/stogi/RedditVideoMakerBot/main.py", line 50, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "/home/stogi/RedditVideoMakerBot/video_creation/screenshot_downloader.py", line 77, in download_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path= postcontentpath)
  File "/home/stogi/.local/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13139, in screenshot
    self._sync(
  File "/home/stogi/.local/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 89, in _sync
    return task.result()
  File "/home/stogi/.local/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 394, in screenshot
    return await self._with_element(
  File "/home/stogi/.local/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "/home/stogi/.local/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 219, in element_handle
    handle = await self._frame.wait_for_selector(
  File "/home/stogi/.local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 307, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/home/stogi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/home/stogi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 370, in _
    return await result
  File "/home/stogi/.local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"
============================================================
`

### Reproduction Steps

Ran bot with python3 main.py

### Expected behavior

Bot finish with operations 

### System Information

Operating System : [ubuntu]
Python version : [Python 3.10.6]
App version / Branch [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by StephanWithPH** [comment]
Any temporary fixes for this bug?

**Comment by stogidout** [comment]
nope not yet. Started working for me but now randomly just astopped and cant figure it out
