### ISSUE TITLE
[Bug]: TikTok tts not working?

### ISSUE THREAD

**Issue by Kudretg** [elebumm/RedditVideoMakerBot#1295]
### Describe the bug

I get an error when I select the tiktok tts voice. does not give error for any other tts.\

Error:
Traceback (most recent call last):
  File "C:\Users\kudre\Downloads\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\kudre\Downloads\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\main.py", line 62, in run_many
    main()
  File "C:\Users\kudre\Downloads\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\kudre\Downloads\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\video_creation\voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\kudre\Downloads\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\TTS\engine_wrapper.py", line 61, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\kudre\Downloads\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\TTS\engine_wrapper.py", line 117, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\kudre\Downloads\RedditVideoMakerBot-2.4.2\RedditVideoMakerBot-2.4.2\TTS\TikTok.py", line 94, in run
    vstr = [r.json()["data"]["v_str"]][0]
KeyError: 'data'

### Reproduction Steps

Selecting tiktok as the tts sound

### Expected behavior

It should use tiktok audio to create tts.

### System Information

Operating System : Win 10
Python version : Latest Stable
App version / Branch: latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Kudretg** [comment]
i have tested on another pc with fresh install of everything and I still am not able to use tiktok tts.

**Comment by OpenSourceSimon** [comment]
The TikTok TTS currently doesn't work. We have a fix, but we're working on the documentation

**Comment by Kudretg** [comment]
thank you for your response. I will be waiting for the update.
