### ISSUE TITLE
[Bug]: Don't want to finish editing the video

### ISSUE THREAD

**Issue by enzovtrt** [elebumm/RedditVideoMakerBot#1300]
### Describe the bug

Translating Text...
Translating Text...
Traceback (most recent call last):
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\main.py", line 62, in run_many
    main()
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\video_creation\voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\TTS\engine_wrapper.py", line 62, in run
    processed_text = process_text(self.reddit_object["thread_post"])
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\TTS\engine_wrapper.py", line 136, in process_text
    translated_text = ts.google(text, to_language=lang)
  File "C:\Users\enzov\AppData\Local\Programs\Python\Python310\lib\site-packages\translators\apis.py", line 395, in google_api
    query_text = self.check_query_text(query_text, if_ignore_limit_of_length, limit_of_length=self.input_limit)
  File "C:\Users\enzov\AppData\Local\Programs\Python\Python310\lib\site-packages\translators\apis.py", line 134, in check_query_text
    raise TranslatorError('The length of the text to be translated exceeds the limit.')
translators.apis.TranslatorError: The length of the text to be translated exceeds the limit.

### Reproduction Steps

I just launched the Bot

### Expected behavior

I launched the bot via main.py and it close.

### System Information

Operating System : Windows 10
Python version : Python 3.10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
Can you change the max length comment in the config.toml and try again?

**Comment by enzovtrt** [comment]
> Can you change the max length comment in the config.toml and try again?

Got that : 

Traceback (most recent call last):
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\main.py", line 62, in run_many
    main()
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\video_creation\voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\TTS\engine_wrapper.py", line 62, in run
    processed_text = process_text(self.reddit_object["thread_post"])
  File "C:\Users\enzov\Documents\GitHub\RedditVideoMakerBot\TTS\engine_wrapper.py", line 136, in process_text
    translated_text = ts.google(text, to_language=lang)
  File "C:\Users\enzov\AppData\Local\Programs\Python\Python310\lib\site-packages\translators\apis.py", line 395, in google_api
    query_text = self.check_query_text(query_text, if_ignore_limit_of_length, limit_of_length=self.input_limit)
  File "C:\Users\enzov\AppData\Local\Programs\Python\Python310\lib\site-packages\translators\apis.py", line 134, in check_query_text
    raise TranslatorError('The length of the text to be translated exceeds the limit.')
translators.apis.TranslatorError: The length of the text to be translated exceeds the limit.

**Comment by enzovtrt** [comment]
Here is my config files if it can help : 


[settings]
allow_nsfw = true
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.2
storymode = false

[settings.background]
background_choice = "minecraft"

[settings.tts]
voice_choice = "tiktok"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "fr_001"
python_voice = "1"
py_voice_num = "2"

[reddit.creds]
client_id = "***************"
client_secret = "*************************"
username = "Physical-Rest5061"
password = "***********"
2fa = false

[reddit.thread]
random = false
subreddit = "LetsNotMeetFR"
post_id = ""
max_comment_length = 50
post_lang = "fr"
min_comments = 20

**Comment by OpenSourceSimon** [comment]
Hi, can you check if this error comes with another Subreddit and voice_choice?

**Comment by FrenchRiana** [comment]
Got the same exact error

Works first time I download and run the package, but when I try again, I get this
