### ISSUE TITLE
[Bug]: RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

### ISSUE THREAD

**Issue by yannickErp** [elebumm/RedditVideoMakerBot#1319]
### Describe the bug

When Running the script, this error comes up:

Traceback (most recent call last):
  File "/Users/yannickerpelding/RedditVideoMakerBot-master/main.py", line 16, in <module>
    from video_creation.background import (
  File "/Users/yannickerpelding/RedditVideoMakerBot-master/video_creation/background.py", line 8, in <module>
    from moviepy.editor import VideoFileClip
  File "/opt/homebrew/lib/python3.10/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/opt/homebrew/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/opt/homebrew/lib/python3.10/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/opt/homebrew/lib/python3.10/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/opt/homebrew/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/opt/homebrew/lib/python3.10/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/opt/homebrew/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 166, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/opt/homebrew/lib/python3.10/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

I have done pip install ffmpeg and pip3 install ffmpeg, but still the same error.

### Reproduction Steps

Done everything that is recommended for setup, then running python3 main.py.

### Expected behavior

No error

### System Information

Operating System : [MacOS 12.6]
Python version : [e.g. Python 3.10.8]
App version / Branch [latest]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by tejasmr** [comment]
Try installing brew and running `brew install ffmpeg`

**Comment by yannickErp** [comment]
It worked after doing manual install, not bash script.
