### ISSUE TITLE
screenshot_downloader.py timeout error

### ISSUE THREAD

**Issue by jacobjake1** [elebumm/RedditVideoMakerBot#132]
C:\Users\jacob\Desktop\RedditVideoMakerBot-master>python3 main.py

  Thanks for using this tool! 😊 Feel free to contribute to this project on GitHub!. If you have any questions, feel
                             free to reach out to me on Twitter or submit a GitHub issue.

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting AskReddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Video will be: Its official that the jury ruled in favor of Johnny Depp, What's your opinion on this??  👍
Received AskReddit threads Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files 🎶                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ----------------------------------------
Saved Text to MP3 files Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading Screenshots of Reddit Posts 📷                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Downloading screenshots... ----------------------------------------
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\jacob\Desktop\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 51, in download_screenshots_of_reddit_posts
    path=f"assets/png/comment_{idx}.png"
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\sync_api\_generated.py", line 13260, in screenshot
    mask=mapping.to_impl(mask),
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\_impl\_locator.py", line 395, in screenshot
    lambda h, timeout: h.screenshot(timeout=timeout, **params)
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\_impl\_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\_impl\_locator.py", line 220, in element_handle
    self._selector, strict=True, state="attached", **params
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\_impl\_frame.py", line 293, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.

**Comment by jacobjake1** [comment]
It was cause I was on proxy; closing thread

**Comment by ishaw18** [comment]
What do you mean on proxy? I am having the same error

**Comment by jacobjake1** [comment]
Turn off VPN
