### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cooperskickz** [elebumm/RedditVideoMakerBot#1331]
### Describe the bug

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/main.py", line 62, in run_many
    main()
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/video_creation/voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
           ^^^^^^^^^^^^^^^^^
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 64, in run
    self.call_tts("posttext", processed_text)
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 117, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/TTS/TikTok.py", line 94, in run
    vstr = [r.json()["data"]["v_str"]][0]
            ^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
cooperskickz@Matthews-MacBook-Air RedditVideoMakerBot-master % 

### Reproduction Steps

not sure

### Expected behavior

not sure

### Screenshots

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/main.py", line 62, in run_many
    main()
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/video_creation/voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
           ^^^^^^^^^^^^^^^^^
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 64, in run
    self.call_tts("posttext", processed_text)
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 117, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "/Users/cooperskickz/Documents/RedditVideoMakerBot-master/TTS/TikTok.py", line 94, in run
    vstr = [r.json()["data"]["v_str"]][0]
            ^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
cooperskickz@Matthews-MacBook-Air RedditVideoMakerBot-master % 

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The TikTok TTS currently doesn't work
