### ISSUE TITLE
loads of errors PLEASE HELP[Bug]: 

### ISSUE THREAD

**Issue by cooperskickz** [elebumm/RedditVideoMakerBot#1332]
### Describe the bug

Traceback (most recent call last):
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/main.py", line 23, in <module>
    from video_creation.voices import save_text_to_mp3
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/video_creation/voices.py", line 10, in <module>
    from TTS.aws_polly import AWSPolly
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/TTS/aws_polly.py", line 2, in <module>
    from boto3 import Session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/client.py", line 17, in <module>
    from botocore import waiter, xform_name
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/utils.py", line 35, in <module>
    import botocore.httpsession
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### Reproduction Steps

Traceback (most recent call last):
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/main.py", line 23, in <module>
    from video_creation.voices import save_text_to_mp3
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/video_creation/voices.py", line 10, in <module>
    from TTS.aws_polly import AWSPolly
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/TTS/aws_polly.py", line 2, in <module>
    from boto3 import Session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/client.py", line 17, in <module>
    from botocore import waiter, xform_name
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/utils.py", line 35, in <module>
    import botocore.httpsession
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### Expected behavior

Traceback (most recent call last):
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/main.py", line 23, in <module>
    from video_creation.voices import save_text_to_mp3
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/video_creation/voices.py", line 10, in <module>
    from TTS.aws_polly import AWSPolly
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/TTS/aws_polly.py", line 2, in <module>
    from boto3 import Session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/client.py", line 17, in <module>
    from botocore import waiter, xform_name
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/utils.py", line 35, in <module>
    import botocore.httpsession
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### Screenshots

Traceback (most recent call last):
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/main.py", line 23, in <module>
    from video_creation.voices import save_text_to_mp3
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/video_creation/voices.py", line 10, in <module>
    from TTS.aws_polly import AWSPolly
  File "/Users/cooperskickz/Documents/ New reddit video maker/RedditVideoMakerBot/TTS/aws_polly.py", line 2, in <module>
    from boto3 import Session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/client.py", line 17, in <module>
    from botocore import waiter, xform_name
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/client.py", line 14, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/utils.py", line 35, in <module>
    import botocore.httpsession
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/botocore/httpsession.py", line 46, in <module>
    from urllib3.contrib.pyopenssl import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### System Information

MacOS

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by LukaHietala** [comment]
What type of mac are you using?

**Comment by OpenSourceSimon** [comment]
Try using Python 3.10
