### ISSUE TITLE
[Bug]: Google TTS timing out

### ISSUE THREAD

**Issue by OttoGrotto** [elebumm/RedditVideoMakerBot#1343]
### Describe the bug

When trying to run the bot from the terminal `python main.py` I get to the point where it's trying to save the video and after a few seconds I get a traceback error that says Google TTS read timed out

### Reproduction Steps

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='translate.google.com', port=443): Read timed out. (read timeout=None)   

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Python-Scripts\RedditVideoMakerBot\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Admin\Desktop\Python-Scripts\RedditVideoMakerBot\main.py", line 62, in run_many
    main()
  File "C:\Users\Admin\Desktop\Python-Scripts\RedditVideoMakerBot\main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Admin\Desktop\Python-Scripts\RedditVideoMakerBot\video_creation\voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\Admin\Desktop\Python-Scripts\RedditVideoMakerBot\TTS\engine_wrapper.py", line 78, in run
    self.call_tts(f"{idx}", process_text(comment["comment_body"]))
  File "C:\Users\Admin\Desktop\Python-Scripts\RedditVideoMakerBot\TTS\engine_wrapper.py", line 136, in process_text
    translated_text = ts.google(text, to_language=lang)
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\translators\apis.py", line 416, in google_api
    r = ss.get(self.host_url, headers=self.host_headers, timeout=timeout, proxies=proxies)
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Admin\Desktop\Python-Scripts\venv\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='translate.google.com', port=443): Read timed out. (read timeout=None) 

### Expected behavior

Receive the output video

### System Information

Operating System : Windows 11
Python version : Python 3.10.5
App version / Branch: latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OttoGrotto** [comment]
When changing to streamlabspolly it sits around showing the Saving text (Twice) and doesn't nothing further

**Comment by Codechickdev** [comment]
Could you include some _screenshots or a recorded video_ maybe about the **issue** you facing ?
