### ISSUE TITLE
[Bug]: MoviePy error that keeps happening

### ISSUE THREAD

**Issue by Bunbun-bun** [elebumm/RedditVideoMakerBot#1351]
### Describe the bug

The issue seems to be with the background video (the audio and the screenshots are totally fine) but I am struggling to fix it.
Any suggestions? 

Background video chopped successfully!
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\REDDIT THING\RedditVideoMakerBot-master\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\REDDIT THING\RedditVideoMakerBot-master\main.py", line 62, in run_many
    main()
  File "C:\REDDIT THING\RedditVideoMakerBot-master\main.py", line 54, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\REDDIT THING\RedditVideoMakerBot-master\video_creation\final_video.py", line 72, in make_final_video
    VideoFileClip(f"assets/temp/{id}/background.mp4")
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/z1l0m4/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

### Reproduction Steps

Followed all the steps thoroughly

### Expected behavior

/

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by jeromejaune** [comment]
Same issue here.

**Comment by OpenSourceSimon** [comment]
Try deleting the whole assets folder

**Comment by 9anhayu1h** [comment]
i face the same problem, but then i change the background_choice to gta then it works.

**Comment by OpenSourceSimon** [comment]
> i face the same problem, but then i change the background_choice to gta then it works.

Yeah because the background file is corrupt. When changing your background choice it will redownload so it isn't corrupt anymore
