### ISSUE TITLE
[Bug]: run_many(config["settings"]["times_to_run"])

### ISSUE THREAD

**Issue by willewille** [elebumm/RedditVideoMakerBot#1353]
### Describe the bug

When i try to run main.py i get this error:
Traceback (most recent call last):
  File "C:\Users\wille\OneDrive\Skrivbord\RedditVideoMakerBot-2.4.2\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\wille\OneDrive\Skrivbord\RedditVideoMakerBot-2.4.2\main.py", line 62, in run_many
    main()
  File "C:\Users\wille\OneDrive\Skrivbord\RedditVideoMakerBot-2.4.2\main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\wille\OneDrive\Skrivbord\RedditVideoMakerBot-2.4.2\video_creation\voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\wille\OneDrive\Skrivbord\RedditVideoMakerBot-2.4.2\TTS\engine_wrapper.py", line 61, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\wille\OneDrive\Skrivbord\RedditVideoMakerBot-2.4.2\TTS\engine_wrapper.py", line 117, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\wille\OneDrive\Skrivbord\RedditVideoMakerBot-2.4.2\TTS\TikTok.py", line 94, in run
    vstr = [r.json()["data"]["v_str"]][0]
KeyError: 'data'

I have tried to disable nsfw but it didn't work. Pls help

### Reproduction Steps

1. I configured the bot
2. I ran main.py
3. It started to do its thing
4. the error appears
5. Go go to issues on github and find out you need nsfw disabled
6. I turn off nsfw
7. I run it again and get the same error

### Expected behavior

The video being created

### System Information

Operating System : [Windows 10]
Python version : [Python 3.10]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
The TikTok TTS currently doesn't work
