### ISSUE TITLE
[Bug]: KeyError: 'data'

### ISSUE THREAD

**Issue by MrTDS98** [elebumm/RedditVideoMakerBot#1354]
### Describe the bug

After running "python main.py" it all seems to be working as intended. I see the whole "video will be:" and "Saving text to mp3 files". but after that, I get 15ish lines I don't understand much of and in the end it says: KeyError: 'data'

### Reproduction Steps

Followed the steps as provided on https://reddit-video-maker-bot.netlify.app/docs/intro
though I did run into a bit of trouble, but I did seem to fix it, but I might be running some newer version of some of the programs in "requirements"

### Expected behavior

To work

### Screenshots

Translating Text...
Traceback (most recent call last):
  File "C:\Users\thor\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\thor\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 62, in run_many
    main()
  File "C:\Users\thor\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 48, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thor\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\voices.py", line 50, in save_text_to_mp3
    return text_to_mp3.run()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\thor\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 61, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\thor\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 117, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\thor\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\TikTok.py", line 94, in run
    vstr = [r.json()["data"]["v_str"]][0]
            ~~~~~~~~^^^^^^^^
KeyError: 'data'

### System Information

Operating System: Windows 10
Python version: Python 3.11.0



### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

_No response_

**Comment by MrTDS98** [comment]
Edit: tried with python 3.10.8 with the same results. I suspect it has something to do with my config

**Comment by borispopov** [comment]
Tiktok TTS is currently not working. If you set voice_choice = "" and run main.py, it will give you the other TTS options and you can choose from one of those.

**Comment by OpenSourceSimon** [comment]
TikTok TTS is currently not working, we're working on a fix!
