### ISSUE TITLE
[Bug]: Get an error on only specific reddit posts

### ISSUE THREAD

**Issue by killerpotato57** [elebumm/RedditVideoMakerBot#1366]
### Describe the bug

Have tried on 2 pcs, reinstalled and many other things to try and fix, every time ill get like 6 videos, get to one post (its one of the same posts every time that breaks it) it gets to when normally id have the video in my results, but instead i get this

Launching Headless Browser...
Skipping translation...
Traceback (most recent call last):
  File "C:\Users\tommy\Desktop\RedditVideoMakerBot-2.4.2\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\tommy\Desktop\RedditVideoMakerBot-2.4.2\main.py", line 62, in run_many
    main()
  File "C:\Users\tommy\Desktop\RedditVideoMakerBot-2.4.2\main.py", line 50, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\tommy\Desktop\RedditVideoMakerBot-2.4.2\video_creation\screenshot_downloader.py", line 77, in download_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path= postcontentpath)
  File "C:\Users\tommy\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 13139, in screenshot
    self._sync(
  File "C:\Users\tommy\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 89, in _sync
    return task.result()
  File "C:\Users\tommy\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 394, in screenshot
    return await self._with_element(
  File "C:\Users\tommy\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\tommy\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 219, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\tommy\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 307, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\tommy\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\tommy\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 370, in _
    return await result
  File "C:\Users\tommy\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"
============================================================

### Reproduction Steps

[config.txt](https://github.com/elebumm/RedditVideoMakerBot/files/10146814/config.txt)
Heres my config (creds removed and converted to txt) (i get same error with nsfw off, originally i had it set to false, the default, but changed it to true to see if it changed anything, it did not) happens on same posts every time

### Expected behavior

I get a video

### System Information

Operating System : Windows 10
Python version : Python 10
App version /Latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Pretty sure its the same issue here https://github.com/elebumm/RedditVideoMakerBot/issues/1344 but the author of this one said nsfw false fixed, which it did not for me

**Comment by killerpotato57** [comment]
got it to work for a bit, closed the program and relaunched, got same thing, i think the problem is that even though i had nsfw set to false it still tried it and failed

**Comment by killerpotato57** [comment]
> got it to work for a bit, closed the program and relaunched, got same thing, i think the problem is that even though i had nsfw set to false it still tried it and failed

nvm thats not the issue, it gets everything (the mp3s and pngs) and then fails after the t: bar is done

**Comment by OpenSourceSimon** [comment]
The error means that it can't get the post. Try with another post
