### ISSUE TITLE
[Bug]: Main.py does not run

### ISSUE THREAD

**Issue by aiden0023** [elebumm/RedditVideoMakerBot#1390]
### Describe the bug

Whenever main.py is called to run, there is an error.

### Reproduction Steps

Running main.py

### Expected behavior

For the program to work.

### Screenshots

Traceback (most recent call last):
  File "/Users/aidenfornalski/Downloads/RedditVideoMakerBot-2.4.2/main.py", line 16, in <module>
    from video_creation.background import (
  File "/Users/aidenfornalski/Downloads/RedditVideoMakerBot-2.4.2/video_creation/background.py", line 8, in <module>
    from moviepy.editor import VideoFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
                    ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/imageio/plugins/ffmpeg.py", line 166, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

### System Information

Operating System : [MacOS]
Python version : [Python 3.11]
App version / Branch [master]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by mannysoye** [comment]
I have a similar problem, its says : 
File "C:\Users\user\Desktop\Upstares\Git-shit\RedditVideoMakerBot-2.3\main.py", line 5, in <module>
    from reddit.subreddit import get_subreddit_threads
ModuleNotFoundError: No module named 'reddit.subreddit'

I didn't notice this in yours, so if theirs a package I need to install for this to work kindly tell me.

**Comment by OpenSourceSimon** [comment]
> I have a similar problem, its says : 
> File "C:\Users\user\Desktop\Upstares\Git-shit\RedditVideoMakerBot-2.3\main.py", line 5, in <module>
>     from reddit.subreddit import get_subreddit_threads
> ModuleNotFoundError: No module named 'reddit.subreddit'
> 
> I didn't notice this in yours, so if theirs a package I need to install for this to work kindly tell me.

Update to our latest version

**Comment by OpenSourceSimon** [comment]
Use Python 3.10, 3.11 won't work
