### ISSUE TITLE
[Bug]: Breaks at: "waiting for selector "[data-test-id="post-content"]""

### ISSUE THREAD

**Issue by wvoet** [elebumm/RedditVideoMakerBot#1393]
### Describe the bug

the bot breaks at:

waiting for selector "[data-test-id="post-content"]"

according to the logs.

### Reproduction Steps

configured the bot after new install, hasn't worked once.

### Expected behavior

It began fine so i expected it to just work fine but it breaks and i do not know why.

### Screenshots

Launching Headless Browser...
Skipping translation...
Traceback (most recent call last):
  File "C:\Users\Wout\Desktop\RedditVideoMakerBot-2.4.2\main.py", line 83, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Wout\Desktop\RedditVideoMakerBot-2.4.2\main.py", line 62, in run_many
    main()
  File "C:\Users\Wout\Desktop\RedditVideoMakerBot-2.4.2\main.py", line 50, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\Wout\Desktop\RedditVideoMakerBot-2.4.2\video_creation\screenshot_downloader.py", line 77, in download_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path= postcontentpath)
  File "C:\Users\Wout\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 13139, in screenshot
    self._sync(
  File "C:\Users\Wout\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 89, in _sync
    return task.result()
  File "C:\Users\Wout\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 394, in screenshot
    return await self._with_element(
  File "C:\Users\Wout\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\Wout\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 219, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\Wout\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 307, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\Wout\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Wout\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 370, in _
    return await result
  File "C:\Users\Wout\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"
============================================================

### System Information

Operating System : windows 10
Python version : 3.10
App version / Branch:  2.4.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by lierrejh** [comment]
pip3.10 install moviepy --upgrade

This is the fix. Tried and tested!

**Comment by wvoet** [comment]
> 
this strangely worked, it was already the updated version tho.
