### ISSUE TITLE
[Bug]: Develop branch does not run successfully

### ISSUE THREAD

**Issue by Matsumotorise** [elebumm/RedditVideoMakerBot#1414]
### Describe the bug

Running main.py on the develop branch fails on final.write_videofile

### Reproduction Steps

Try running with this toml file:

[config.zip](https://github.com/elebumm/RedditVideoMakerBot/files/10317391/config.zip)

### Expected behavior

No errors

### Screenshots

![image](https://user-images.githubusercontent.com/35851996/209898278-ac2ec640-ee4c-4f05-9dd5-72b273606857.png)

### System Information

Operating System : Windows 10
Python version : 3.10.8
App version / Branch: 6041cce53e33e4f3fb0b98e4941e4918df20a69b, develop

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Traceback (most recent call last):
  File "G:\My Drive\Personal\Development projects\Programming\Python\RedditVideoMakerBot\main.py", line 117, in <module>
    raise err
  File "RedditVideoMakerBot\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "RedditVideoMakerBot\main.py", line 63, in run_many
    main()
  File "RedditVideoMakerBot\main.py", line 55, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "RedditVideoMakerBot\video_creation\final_video.py", line 265, in make_final_video
┌─────────────────────────────────────────────────────────────────────────────┐
│                                                                             │
│             Sorry, something went wrong with this test version! Try again,  │
│ and feel free to report this issue at GitHub or the Discord community.      │
│                                                                             │
│             Version: 2.5.0                                                  │
│                                                                             │
│             Story mode: False                                               │
│                                                                             │
│             Story mode method: 1                                            │
│                                                                             │
└─────────────────────────────────────────────────────────────────────────────┘
    final.write_videofile(
  File "<decorator-gen-55>", line 2, in write_videofile
  File "lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "lib\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "site-packages\moviepy\video\VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "site-packages\moviepy\video\io\ffmpeg_writer.py", line 220, in ffmpeg_write_video
    for t,frame in clip.iter_frames(logger=logger, with_times=True,
  File "site-packages\moviepy\Clip.py", line 472, in iter_frames
    frame = self.get_frame(t)
  File "<decorator-gen-11>", line 2, in get_frame
  File "site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 111, in make_frame
    f = c.blit_on(f, t)
  File "lib\site-packages\moviepy\video\VideoClip.py", line 527, in blit_on
    img = self.get_frame(ct)
  File "<decorator-gen-11>", line 2, in get_frame
  File "site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 111, in make_frame
    f = c.blit_on(f, t)
  File "site-packages\moviepy\video\VideoClip.py", line 536, in blit_on
    pos = self.pos(ct)
  File "RedditVideoMakerBot\video_creation\background.py", line 28, in <lambda>
    background_options[name][3] = lambda t: ("center", pos + t)
TypeError: can only concatenate str (not "numpy.float64") to str

Process finished with exit code 1

**Comment by fin-github** [comment]
While looking through your config.toml file i noticed that the problem might be because arial im pretty sure is not spelt right.
![image](https://user-images.githubusercontent.com/70870542/210103719-3191479c-3f59-4ce7-ac01-dbef2447b819.png)
Check there. I'm not advanced in coding and I was trying to find the problem but it was hard for me.

**Comment by Matsumotorise** [comment]
> While looking through your config.toml file i noticed that the problem might be because arial im pretty sure is not spelt right. ![image](https://user-images.githubusercontent.com/70870542/210103719-3191479c-3f59-4ce7-ac01-dbef2447b819.png) Check there. I'm not advanced in coding and I was trying to find the problem but it was hard for me.

I'm pretty sure it's spelled right.

**Comment by Ika1009** [comment]
I got the exact same bug with the coming of 3.0, and the last version worked for me

**Comment by OpenSourceSimon** [comment]
Use Minecraft background
