### ISSUE TITLE
[Bug]: TypeError: can only concatenate str (not "numpy.float64") to str in runtime of main.py

### ISSUE THREAD

**Issue by Ika1009** [elebumm/RedditVideoMakerBot#1429]
### Describe the bug

When the process comes to background.py, it shows an error. I tried commenting it out, but then a new error appears that is probably connected to this one.

Here is the output:
subreddit: r/AskReddit+worldnews from TOML config
Video will be: what's something you've never tried and never will? 👍
Thread url is : https://reddit.com/r/AskReddit/comments/103zx6n/whats_something_youve_never_tried_and_never_will/ 👍
Thread has 4168 upvotes
Thread has a upvote ratio of 94.0%
Thread has 5332 comments
Received subreddit threads Successfully.
Thread ID is 103zx6n
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Saving Text to MP3 files...                                                                                                                          │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7 it/s  
Saved Text to MP3 files successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Downloading screenshots of reddit posts...                                                                                                           │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Launching Headless Browser...
Skipping translation...
Downloading screenshots... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Screenshots downloaded Successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Finding a spot in the backgrounds video to chop...✂️
│
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command successful
Background video chopped successfully!
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Creating the final video 🎥                                                                                                                          │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[22:00:02]  Video Will Be: 43 Seconds Long                                                                                            final_video.py:124Moviepy - Building video assets/temp/103zx6n/temp.mp4.
MoviePy - Writing audio in tempTEMP_MPY_wvf_snd.mp4
MoviePy - Done.
Moviepy - Writing video assets/temp/103zx6n/temp.mp4

t:   0%|                                                                                                            | 0/1411 [00:00<?, ?it/s, now=None╭ 
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ 
│                                                                                                                                                      ││             Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.         ││                                                                                                                                                      ││             Version: 3.0                                                                                                                             ││                                                                                                                                                      ││             Story mode: False                                                                                                                        ││                                                                                                                                                      ││             Story mode method: 1                                                                                                                     ││                                                                                                                                                      │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Traceback (most recent call last):
  File "D:\Programiranje\Python\Reddit Klipovi Bot\MojBot\RedditVideoMakerBot\main.py", line 104, in <module>
    raise err
  File "D:\Programiranje\Python\Reddit Klipovi Bot\MojBot\RedditVideoMakerBot\main.py", line 86, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\Programiranje\Python\Reddit Klipovi Bot\MojBot\RedditVideoMakerBot\main.py", line 50, in run_many
    main()
  File "D:\Programiranje\Python\Reddit Klipovi Bot\MojBot\RedditVideoMakerBot\main.py", line 42, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "D:\Programiranje\Python\Reddit Klipovi Bot\MojBot\RedditVideoMakerBot\video_creation\final_video.py", line 265, in make_final_video
    final.write_videofile(
  File "<decorator-gen-55>", line 2, in write_videofile
  File "D:\aplikacije\Python\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "D:\aplikacije\Python\lib\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "D:\aplikacije\Python\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "D:\aplikacije\Python\lib\site-packages\moviepy\video\VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "D:\aplikacije\Python\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 220, in ffmpeg_write_video
    for t,frame in clip.iter_frames(logger=logger, with_times=True,
  File "D:\aplikacije\Python\lib\site-packages\moviepy\Clip.py", line 472, in iter_frames
    frame = self.get_frame(t)
  File "<decorator-gen-11>", line 2, in get_frame
  File "D:\aplikacije\Python\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\aplikacije\Python\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "D:\aplikacije\Python\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 111, in make_frame
    f = c.blit_on(f, t)
  File "D:\aplikacije\Python\lib\site-packages\moviepy\video\VideoClip.py", line 527, in blit_on
    img = self.get_frame(ct)
  File "<decorator-gen-11>", line 2, in get_frame
  File "D:\aplikacije\Python\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\aplikacije\Python\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "D:\aplikacije\Python\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 111, in make_frame
    f = c.blit_on(f, t)
  File "D:\aplikacije\Python\lib\site-packages\moviepy\video\VideoClip.py", line 536, in blit_on
    pos = self.pos(ct)
  File "D:\Programiranje\Python\Reddit Klipovi Bot\MojBot\RedditVideoMakerBot\video_creation\background.py", line 28, in <lambda>
    background_options[name][3] = lambda t: ("center", pos + t)
TypeError: can only concatenate str (not "numpy.float64") to str

### Reproduction Steps

When the process comes to background.py, it shows an error. I tried commenting it out, but then a new error appears that is probably connected to this one.

### Expected behavior

The expected outcome is not to crash hahaha, man this GitHub really makes me type stupid things.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by JasonLovesDoggo** [comment]
add int()

**Comment by Glement** [comment]
update: for some reason the only background video that works is minecraft video

**Comment by JasonLovesDoggo** [comment]
It's been fixed in develop
