### ISSUE TITLE
[Bug]: Error when running main.py

### ISSUE THREAD

**Issue by byomartin** [elebumm/RedditVideoMakerBot#1438]
### Describe the bug

Error when I run -requirements.txt 
 Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement torch==1.12.1 (from versions: none)
ERROR: No matching distribution found for torch==1.12.1

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

After that error when I run main.py
C:\Users\admin\Desktop\RedditVideoMakerBot-3.0>python3 main.py
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\RedditVideoMakerBot-3.0\main.py", line 11, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\admin\Desktop\RedditVideoMakerBot-3.0\reddit\subreddit.py", line 11, in <module>
    from utils.subreddit import get_subreddit_undone
  File "C:\Users\admin\Desktop\RedditVideoMakerBot-3.0\utils\subreddit.py", line 6, in <module>
    from utils.ai_methods import sort_by_similarity
  File "C:\Users\admin\Desktop\RedditVideoMakerBot-3.0\utils\ai_methods.py", line 2, in <module>
    from transformers import AutoTokenizer, AutoModel
ModuleNotFoundError: No module named 'transformers'

### Reproduction Steps

I run pip install -r requirements.txt
then I run python3 main.py

### Expected behavior

It should work because I installed and run 2.4.2 successfully before.
But 3.0 I got error.

### System Information

Operating System : Windows 10
Python version : Python 3.10
App version / Branch : v3.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by byomartin** [comment]
I have python 3.11, don't know why, I removed 3.11 now python 3.10.9
I'm running requirements.txt again.
