### ISSUE TITLE
[Bug]: Errors after translating post

### ISSUE THREAD

**Issue by RedditHumorCentral** [elebumm/RedditVideoMakerBot#1443]
### Describe the bug

It runs until translating post and then gives the "something went wrong with this version!".

below is the error text:

`┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                     │
│             Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub  │
│ or the Discord community.                                                                                           │
│                                                                                                                     │
│             Version: 3.0                                                                                            │
│                                                                                                                     │
│             Story mode: False                                                                                       │
│                                                                                                                     │
│             Story mode method: 1                                                                                    │
│                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\steph\OneDrive\Documents\Bot\RedditVideoMakerBot\main.py", line 117, in <module>
    raise err
  File "C:\Users\steph\OneDrive\Documents\Bot\RedditVideoMakerBot\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\steph\OneDrive\Documents\Bot\RedditVideoMakerBot\main.py", line 63, in run_many
    main()
  File "C:\Users\steph\OneDrive\Documents\Bot\RedditVideoMakerBot\main.py", line 51, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\steph\OneDrive\Documents\Bot\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 100, in get_screenshots_of_reddit_posts
    page.evaluate(
  File "C:\Users\steph\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\sync_api\_generated.py", line 6786, in evaluate
    self._sync(
  File "C:\Users\steph\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_sync_base.py", line 89, in _sync
    return task.result()
  File "C:\Users\steph\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_page.py", line 412, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "C:\Users\steph\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_frame.py", line 262, in evaluate
    await self._channel.send(
  File "C:\Users\steph\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\steph\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 370, in _
    return await result
  File "C:\Users\steph\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: TypeError: Cannot set properties of null (setting 'textContent')
    at eval (eval at evaluate (:178:30), <anonymous>:1:114)
    at UtilityScript.evaluate (<anonymous>:185:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)`

### Reproduction Steps

I just ran main.py and configured it. I am running python 3.9.12

All packages installed properly.

### Expected behavior

The program should save screenshots but it is at this point that it fails.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.9.12]
App version / Branch : [e.g. latest, V3.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by RedditHumorCentral** [comment]
I changed some of the configuration and seems to work.
