### ISSUE TITLE
Error during "Download Minecraft Video"

### ISSUE THREAD

**Issue by MrSataana** [elebumm/RedditVideoMakerBot#146]
This is using the "New-Feature" branch.

![image](https://user-images.githubusercontent.com/79517524/171647657-fd55b690-e210-4ab5-8f8d-00ffa6702dd6.png)

`Traceback (most recent call last):
  File "C:\Users\conta\AppData\Roaming\Python\Python310\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\conta\AppData\Roaming\Python\Python310\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\conta\AppData\Roaming\Python\Python310\site-packages\pytube\cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\RedditVideoMakerBot\main.py", line 21, in <module>
    video_id = download_background()
  File "C:\Program Files\Python310\RedditVideoMakerBot\video_creation\background.py", line 34, in download_background
    YouTube(f"https://www.youtube.com/watch?v={video_id}").streams.filter(
  File "C:\Users\conta\AppData\Roaming\Python\Python310\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\conta\AppData\Roaming\Python\Python310\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\conta\AppData\Roaming\Python\Python310\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\conta\AppData\Roaming\Python\Python310\site-packages\pytube\cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W`

**Comment by null3000** [comment]
You only  need to download the background file once. This is a hacky soultion but it worked for me:

1. use a youtube to mp4 website like this one (https://onlinevideoconverter.pro/en81/youtube-downloader-mp4)
2. paste the youtube link into it (https://www.youtube.com/watch?v=n_Dv4JMiwK8)
3. download in 720p
4. rename the video to "background.mp4"
5. create a new folder inside of "assets" called "mp4"
6. drag the finished mp4 into the mp4 file
8. enjoy!
please lmk if you have any more issues.

**Comment by MDAmirPathan** [comment]
Thank You @null3000 !! The file Is >1GB And I have a Slow Internet Connection 
So I Was Getting **TimeoutError: Timeout 30000ms exceeded.** Error
