### ISSUE TITLE
[Bug]: probably the aid value isn't correct

### ISSUE THREAD

**Issue by hoainam125** [elebumm/RedditVideoMakerBot#1467]
### Describe the bug

Translating Text...
Traceback (most recent call last):
  File "C:\Users\ADMIN\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 117, in <module>
    raise err
  File "C:\Users\ADMIN\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\ADMIN\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 63, in run_many
    main()
  File "C:\Users\ADMIN\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\ADMIN\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\voices.py", line 51, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\ADMIN\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 59, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\ADMIN\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 138, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\ADMIN\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\TTS\TikTok.py", line 108, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.

### Reproduction Steps

I just set up all steps and program can not run due to this error 

### Expected behavior

run normally

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by ccogh** [comment]
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.


I got that error, have you put the tiktok sessionID into the .toml file?

**Comment by rmadduku** [comment]
The problem is linked to the voice_choice="tiktok". I changed it to googletranslate and it worked fine.

**Comment by codentacos** [comment]
I'm also experiencing this issue. I put my sessionid into the config and I get an error for the aid value as well.

**Comment by hoainam125** [comment]
> The problem is linked to the voice_choice="tiktok". I changed it to googletranslate and it worked fine.

oh, it worked for me so, thank you!
