### ISSUE TITLE
[Bug]: RuntimeError when try to run main.py

### ISSUE THREAD

**Issue by neoxcorp** [elebumm/RedditVideoMakerBot#1469]
### Describe the bug

I try to go step by step - https://reddit-video-maker-bot.netlify.app/docs/configuring
When I try to run on my mac 
python3 main.py
get - RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

### Reproduction Steps

Open terminal on mac
Go to RedditVideoMakerBot-master
Run python3 main.py

get

`Traceback (most recent call last):
  File "/Users/andrew/workspace/RedditVideoMakerBot-master/main.py", line 17, in <module>
    from video_creation.background import (
  File "/Users/andrew/workspace/RedditVideoMakerBot-master/video_creation/background.py", line 8, in <module>
    from moviepy.editor import VideoFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 173, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/imageio_ffmpeg/_utils.py", line 33, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
`

### Expected behavior

I can setup a bot

### System Information

Operating System : MacOs Ventura 13.1 (22C65)
Python version : Python 3.10.9
App version / Branch : V3.0, master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by sahariarpku** [comment]
same issue!

**Comment by OpenSourceSimon** [comment]
Install ffmpeg
