### ISSUE TITLE
[Bug]: Issue with downloading a video

### ISSUE THREAD

**Issue by RiddSarav** [elebumm/RedditVideoMakerBot#1472]
### Describe the bug

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/riddhishsaravanan/githubtesting/RedditVideoMakerBot/main.py", line 117, in <module>
    raise err
  File "/Users/riddhishsaravanan/githubtesting/RedditVideoMakerBot/main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/riddhishsaravanan/githubtesting/RedditVideoMakerBot/main.py", line 63, in run_many
    main()
  File "/Users/riddhishsaravanan/githubtesting/RedditVideoMakerBot/main.py", line 53, in main
    download_background(bg_config)
  File "/Users/riddhishsaravanan/githubtesting/RedditVideoMakerBot/video_creation/background.py", line 75, in download_background
    YouTube(uri, on_progress_callback=on_progress).streams.filter(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

### Reproduction Steps

run main.py wait till you download the background video

### Expected behavior

the code to work

### System Information

Operating System : [e.g. Mac BigSur]
Python version : [e.g. Python 3.10.9]
App version / Branch : [3.0]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OpenSourceSimon** [comment]
https://stackoverflow.com/a/70495761/17174109

**Comment by Brandon4466** [comment]
I am also having this issue, the stackoverflow article did not help
