### ISSUE TITLE
[Bug]: Error in the end of the script

### ISSUE THREAD

**Issue by FouziGit** [elebumm/RedditVideoMakerBot#1481]
### Describe the bug

Hello, at the end of the script I get this : 

Traceback (most recent call last):
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\main.py", line 117, in <module>
    raise err
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])    
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\main.py", line 63, in run_many
    main()
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 51, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 59, in run   
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 138, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\TTS\TikTok.py", line 108, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't 
load speech. Try again.

### Reproduction Steps

All the script

### Expected behavior

The video uploaded

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by MehdiNdj** [comment]
Hi,
You need to add your TikTok session ID in the config.toml file.
You can either do it by editing it manually or through the GUI version (by typing **python GUI.py**)

To find your TikTok session ID, you need to install the Cookie Editor plug-in in your browser, then go to TikTok's website and login. Then open the plug-in and search for the sessionid section.

**Comment by FouziGit** [comment]
Thank you very much for the answer !

**Comment by MehdiNdj** [comment]
You're welcome, hoping it helped you solve the issue!

**Comment by FouziGit** [comment]
Hello, 

I have an other issues with the script, when I finnaly create it, it writes me that : 
Background video chopped successfully!


╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│ Creating the final video 🎥                                                                                                                                                                                                  │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮│                                                                                                                                                                                                                              ││             Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                                 ││                                                                                                                                                                                                                              ││             Version: 3.0                                                                                                                                                                                                     ││                                                                                                                                                                                                                              ││             Story mode: False                                                                                                                                                                                                ││                                                                                                                                                                                                                              ││             Story mode method: 1                                                                                                                                                                                             ││                                                                                                                                                                                                                              │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Traceback (most recent call last):
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\main.py", line 117, in <module>
    raise err
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\main.py", line 63, in run_many
    main()
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\main.py", line 55, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 99, in make_final_video
    background_clip = prepare_background(reddit_id, W=W, H=H)
  File "C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 51, in prepare_background
    VideoFileClip(f"assets/temp/{reddit_id}/background.mp4")
  File "C:\Users\Benzidane\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\Benzidane\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\video\io\ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "C:\Users\Benzidane\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\video\io\ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/117cwyu/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
PS C:\Users\Benzidane\Desktop\RedditVideoMakerBot-master>

**Comment by MehdiNdj** [comment]
You should try updating it if not done yet.

**Comment by ImDini** [comment]
Same issue still occurs
