### ISSUE TITLE
[Bug]: all time filters have been checked you absolute madlad

### ISSUE THREAD

**Issue by CherryDT** [elebumm/RedditVideoMakerBot#1485]
### Describe the bug

I'm getting this error:

```
This post has under the specified minimum of comments (20). Skipping...

This post has under the specified minimum of comments (20). Skipping...

all submissions have been done going by top submission order

all time filters have been checked you absolute madlad 

submission.id =  fpgquw , index =  6 , len =  6 , timed_checked = 5

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮

│                                                                                                                               │

│             Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the     │

│ Discord community.                                                                                                            │

│                                                                                                                               │

│             Version: 3.0                                                                                                      │

│                                                                                                                               │

│             Story mode: False                                                                                                 │

│                                                                                                                               │

│             Story mode method: 1                                                                                              │

│                                                                                                                               │

╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Traceback (most recent call last):

  File "/home/cherry/proj/RedditVideoMakerBot-master/main.py", line 117, in <module>

    raise err

  File "/home/cherry/proj/RedditVideoMakerBot-master/main.py", line 99, in <module>

    run_many(config["settings"]["times_to_run"])

  File "/home/cherry/proj/RedditVideoMakerBot-master/main.py", line 63, in run_many

    main()

  File "/home/cherry/proj/RedditVideoMakerBot-master/main.py", line 47, in main

    reddit_object = get_subreddit_threads(POST_ID)

  File "/home/cherry/proj/RedditVideoMakerBot-master/reddit/subreddit.py", line 99, in get_subreddit_threads

    submission = get_subreddit_undone(threads, subreddit)

  File "/home/cherry/proj/RedditVideoMakerBot-master/utils/subreddit.py", line 70, in get_subreddit_undone

    return get_subreddit_undone(

  File "/home/cherry/proj/RedditVideoMakerBot-master/utils/subreddit.py", line 70, in get_subreddit_undone

    return get_subreddit_undone(

  File "/home/cherry/proj/RedditVideoMakerBot-master/utils/subreddit.py", line 70, in get_subreddit_undone

    return get_subreddit_undone(

  [Previous line repeated 2 more times]

  File "/home/cherry/proj/RedditVideoMakerBot-master/utils/subreddit.py", line 72, in get_subreddit_undone

    time_filter=VALID_TIME_FILTERS[index],

IndexError: list index out of range
```

I added some extra log: `submission.id =  fpgquw , index =  6 , len =  6 , timed_checked = 5`

### Reproduction Steps

Try default settings with subreddit `funnyanswers`

### Expected behavior

Working

### System Information

Operating System : Ubuntu 22.04.1
Python version : 3.10.6
App version / Branch : 3.0, was installed with bash script

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by CherryDT** [comment]
Not fixed, but closed as completed 😑

I will never understand the purpose of stale bots if they are not configured in such a way that they act only if the last message is from a maintainer, especially if the maintainers don't even respond to issues quickly enough to handle them before the bot closes them. It only makes people angry and frustrated, because it means our time invested in writing bug reports is not valued. Nobody expects a quick response in a hobby project, but then don't let a stele bot loose on it either!

**Comment by cwjacklin** [comment]
utils/subreddit.py  
        if settings.config["settings"]["storymode"] and not submission.is_self:
            continue

somewhere in the doc probabaly says storymode is only for your own posts.
otherwise all posts get skipped over.   and then VALID_TIME_FILTERS[index] craps out.
