### ISSUE TITLE
[Bug]: First few videos work but then it crashes after downloading screenshots phase

### ISSUE THREAD

**Issue by denigth** [elebumm/RedditVideoMakerBot#1486]
### Describe the bug

after generating a few videos it just randomly starts malfunctioning and giving me the following error
i've downloaded everything that's listed and tried messing about with the config but this error keeps coming back

Traceback (most recent call last):
  File "C:\Users\curti\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 117, in <module>
    raise err
  File "C:\Users\curti\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\curti\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 63, in run_many
    main()
  File "C:\Users\curti\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 51, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\curti\OneDrive\Desktop\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 108, in get_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path=postcontentpath)
  File "C:\Users\curti\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 13139, in screenshot
    self._sync(
  File "C:\Users\curti\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 89, in _sync
    return task.result()
  File "C:\Users\curti\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 394, in screenshot
    return await self._with_element(
  File "C:\Users\curti\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\curti\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 219, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\curti\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 307, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\curti\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\curti\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 370, in _
    return await result
  File "C:\Users\curti\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"

### Reproduction Steps

tried to run the main.py a few times

### Expected behavior

gather the screenshots successfully and compile the video as intended

### System Information

Operating System : [Windows 11]
Python version : [Python 3.10]
App version / Branch : [V3.0]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Jan64X** [comment]
Having this issue aswell, did you find a solution?

**Comment by Brandon4466** [comment]
NOT stale, having this exact issue

**Comment by SynchronDEV** [comment]
Same issue

**Comment by SynchronDEV** [comment]
I seem to have fixed the issue.

For some reason, it wasn't working on one of my Reddit accounts. I switched to another account I had, made a new application, and selected it as "web app". It was selected as "script" on my first account (No clue if this had anything to do with the issue).

After this, I successfully passed the downloading screenshots step.

**Comment by ImDini** [comment]
Still getting this

**Comment by OpenSourceSimon** [comment]
Some posts don't work, use a different post
