### ISSUE TITLE
[Bug]: TikTokTTSException(5) TypeError: __init__() missing 1 required positional argument: 'message'

### ISSUE THREAD

**Issue by Anthonyh426** [elebumm/RedditVideoMakerBot#1503]
### Describe the bug

When I run the code it gets to the point where it has chosen a reddit post but then this error occurs. The following error is produced:

Traceback (most recent call last):
  File "C:\Users\user\Dev\shortsgenerator\RedditVideoMakerBot-master\main.py", line 115, in <module>
    raise err
  File "C:\Users\user\Dev\shortsgenerator\RedditVideoMakerBot-master\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\user\Dev\shortsgenerator\RedditVideoMakerBot-master\main.py", line 63, in run_many
    main()
  File "C:\Users\user\Dev\shortsgenerator\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\user\Dev\shortsgenerator\RedditVideoMakerBot-master\video_creation\voices.py", line 37, in save_text_to_mp3
    text_to_mp3 = TTSEngine(
  File "C:\Users\user\Dev\shortsgenerator\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 44, in __init__
    self.tts_module = tts_module()
  File "C:\Users\user\Dev\shortsgenerator\RedditVideoMakerBot-master\TTS\TikTok.py", line 83, in __init__
    raise TikTokTTSException(5)

### Reproduction Steps

Started my virtual environment then ran "python main.py"

### Expected behavior

The programme to produce an output video

### System Information

Operating System : Windows 10
Python version : Python 3.9
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by jaykeerti** [comment]
https://github.com/elebumm/RedditVideoMakerBot/issues/1495#issue-1594676951
