### ISSUE TITLE
[Bug]: main.py doesn't run properly - no attribute "span"

### ISSUE THREAD

**Issue by Serbienx** [elebumm/RedditVideoMakerBot#1525]
### Describe the bug

The bug is that I get this error when I run the main.py file:

╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this      │
│ issue at GitHub or the Discord community.                                                   │
│ Version: 3.0.1,Story mode: False, Story mode method: 1,                                     │
│ Postid : {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9,          │
│ 'transition': 0.2, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000,  │
│ 'fps': 30, 'resolution_w': 1080, 'resolution_h': 1920, 'background': {'background_choice':  │
│ 'minecraft', 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',    │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'},    │
│ 'tts': {'voice_choice': 'googletranslate', 'aws_polly_voice': 'Matthew',                    │
│ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_003', 'tiktok_sessionid': '',   │
│ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis':             │
│ False}},allownsfw :False,is_nsfw : False                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "F:\Downloads\RedditVideoMaker\RedditVideoMakerBot\main.py", line 115, in <module>
    raise err
  File "F:\Downloads\RedditVideoMaker\RedditVideoMakerBot\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "F:\Downloads\RedditVideoMaker\RedditVideoMakerBot\main.py", line 63, in run_many
    main()
  File "F:\Downloads\RedditVideoMaker\RedditVideoMakerBot\main.py", line 53, in main
    download_background(bg_config)
  File "F:\Downloads\RedditVideoMaker\RedditVideoMakerBot\video_creation\background.py", line 75, in download_background
    YouTube(uri, on_progress_callback=on_progress).streams.filter(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\cipher.py", line 411, in get_throttling_plan
    transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
AttributeError: 'NoneType' object has no attribute 'span'

### Reproduction Steps

I ran the main.py file after doing the setup.py

### Expected behavior

Expected: The video to be created

### Screenshots

![image](https://user-images.githubusercontent.com/112068520/226425778-5eac3820-a2ab-4013-8806-4143259d8c97.png)
![image](https://user-images.githubusercontent.com/112068520/226425870-9677c08c-9292-4a89-99d8-7273301df7cb.png)

### System Information

Operating System : Windows 11
Python version : Python 3.10
App version / Branch : latest as of 20/03/2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Quercus25** [comment]
modifying {home}/.local/lib/python3.10/site-packages/pytube/cipher.py
Line 411

`transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)`
to
`transform_plan_raw = js`

that helped me

**Comment by Serbienx** [comment]
Just tried that and the progress bar is starting, which is different to usual.
I'll see if that means it will work.

**Comment by Serbienx** [comment]
That worked, thank's a lot mate!
