### ISSUE TITLE
hi, here i come with another issue

### ISSUE THREAD

**Issue by Sgegsdge** [elebumm/RedditVideoMakerBot#155]
after running main.py this is what i get:

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting AskReddit threads...                                                                                     │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\(my username)\RedditVideoMakerBot\main.py", line 16, in <module>
    reddit_object = get_askreddit_threads()
  File "C:\Users\(my username)\RedditVideoMakerBot\reddit\askreddit.py", line 26, in get_askreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\(my username)\anaconda3\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\(my username)\anaconda3\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\(my username)\anaconda3\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\(my username)\anaconda3\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\(my username)\anaconda3\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\(my username)\anaconda3\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\(my username)\anaconda3\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\(my username)\anaconda3\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\(my username)\anaconda3\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\(my username)\anaconda3\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\(my username)\anaconda3\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\(my username)\anaconda3\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\(my username)\anaconda3\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\(my username)\anaconda3\lib\site-packages\prawcore\auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: unauthorized_client error processing request (Only script apps may use password auth)

what should i do???

**Comment by JasonLovesDoggo** [comment]
When you made the Reddit app you accidentally didn't select script

**Comment by JasonLovesDoggo** [comment]
you put the variables in wrong.
keep the quotes

**Comment by JasonLovesDoggo** [comment]
all good for asking!

**Comment by binbohrawa** [comment]
> you put the variables in wrong. keep the quotes

Hey, I have the same issue, I did leave quotations as it is and I'm getting the same error, any further instructions, I'm not very familiar with Python nor coding..

**Comment by totalsoda** [comment]
> all good for asking!

Hi, I believe I'm doing everything correctly however I'm getting this error which I think is to do with the praw.ini /.env
I'd appreciate it if you could take a look:

Traceback (most recent call last):
  File "/Users/(USERNAME)/Desktop/Projects/Git/RedditVideoMakerBot-master/main.py", line 16, in <module>
    reddit_object = get_subreddit_threads()
  File "/Users/(USERNAME)/Desktop/Projects/Git/RedditVideoMakerBot-master/reddit/subreddit.py", line 17, in get_subreddit_threads
    reddit = praw.Reddit(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/praw/reddit.py", line 258, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing. 
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.

**Comment by Furilo19** [comment]
@JasonLovesDoggo I have the same prawcore issue but i already checked multiple times if my .env variables are correct
what could be the issue for me?

**Comment by JasonLovesDoggo** [comment]
Are you absolutely sure the variables are correct.
And is it the exact same error msg
And do you have the quotes in the .env

**Comment by Furilo19** [comment]
@JasonLovesDoggo If the Username and Password thats asked for is supposed to be the information i Login with then yes it is correct

**Comment by JasonLovesDoggo** [comment]
Also the client ID and client secret

**Comment by Furilo19** [comment]
Client ID i Put the String below the App Name and Secret the Secret

**Comment by Privatexoxo** [comment]
I have the same issue did yall solve it ?

**Comment by Privatexoxo** [comment]
and if yes where was the issue ?

**Comment by FreebieII** [comment]
> and if yes where was the issue ?

Seems like it was in issue with the 2FA system.

**Comment by FreebieII** [comment]
Hi @Sgegsdge 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
