### ISSUE TITLE
[Bug]: playwright._impl._api_types.Error: TypeError: Cannot set properties of null (setting 'textContent')

### ISSUE THREAD

**Issue by leesinger** [elebumm/RedditVideoMakerBot#1621]
### Describe the bug

When using post_lang = "pt" (I don't know if it happens with any other language, only tried with "pt"), and post_id = "something", this happens:

Traceback (most recent call last):
  File "path\RedditVideoMakerBot-master\main.py", line 130, in <module>
    raise err
  File "path\RedditVideoMakerBot-master\main.py", line 108, in <module>
    main(post_id)
  File "path\RedditVideoMakerBot-master\main.py", line 52, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "path\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 152, in get_screenshots_of_reddit_posts
    page.evaluate(
  File "path\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 6786, in evaluate
    self._sync(
  File "path\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 89, in _sync
    return task.result()
  File "path\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_page.py", line 412, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "path\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 262, in evaluate
    await self._channel.send(
  File "path\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "path\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 370, in _
    return await result
  File "path\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: TypeError: Cannot set properties of null (setting 'textContent')
    at eval (eval at evaluate (:178:30), <anonymous>:1:114)
    at UtilityScript.evaluate (<anonymous>:185:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)

I have set in post_id around 35 threads, separated by +, and I noticed that the first one gives me this error, the second one goes fine, the third one gives me this error again, which means it probably happens fairly often. Still haven't tested with more than the 3, but can do if necessary.

### Reproduction Steps

1 - post_lang = "pt"
2 - post_id = "gjmajm+himsju+tlmlnw" (for example)
3 - run main.py

### Expected behavior

It should run normally, translating both the TTS and Screenshots, but when disabling headless mode I can see that it crashes after opening the Reddit thread and closing the "set interests" popup.

### System Information

Operating System : Windows 10
Python version : Python 3.10
App version / Branch : latest with some changes I did to the code, but I don't think anything that could've messed with this. This should probably be reproducible in latest.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by zezo-monobola** [comment]
bump
