### ISSUE TITLE
[Bug]: Screenshots stopped working

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1647]
### Describe the bug

Whenever it gets to the part where it downloads screenshots, it times out.  

```Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Something went wrong!
Something went wrong with making the screenshots! Do you want to skip the post? (y/n) n
Do you want the error traceback for debugging purposes? (y/n)y
```
I did look at the error traceback for debugging purposes and this was the result. 

```
Traceback (most recent call last):
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot-master/main.py", line 136, in <module>
    raise err
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot-master/main.py", line 114, in <module>
    main(post_id)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot-master/main.py", line 53, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot-master/video_creation/screenshot_downloader.py", line 194, in get_screenshots_of_reddit_posts
    raise e
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot-master/video_creation/screenshot_downloader.py", line 167, in get_screenshots_of_reddit_posts
    location = page.locator('[data-test-id="post-content"]').bounding_box()
  File "/usr/local/anaconda3/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 12114, in bounding_box
    self._sync(self._impl_obj.bounding_box(timeout=timeout))
  File "/usr/local/anaconda3/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 89, in _sync
    return task.result()
  File "/usr/local/anaconda3/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 115, in bounding_box
    return await self._with_element(
  File "/usr/local/anaconda3/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 219, in element_handle
    handle = await self._frame.wait_for_selector(
  File "/usr/local/anaconda3/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 307, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/usr/local/anaconda3/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/anaconda3/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 370, in _
    return await result
  File "/usr/local/anaconda3/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"
==========================================================
```

### Reproduction Steps

- Plug a reddit thread ID into your config file
- Start the bot
- Wait til it gets to downloading screenshots.

### Expected behavior

Download screenshots as normal

### System Information

Operating System : MacOS 13.4
Python version : Python 3.10
App version / Branch : master (3.1)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by tekmunki** [comment]
Double check you haven't set old.reddit.com as the default on the reddit account you're using with the bot.  This is what was causing the screenshot function to fail for me as the [data-test-id="post-content"] is only present with the new reddit design.  You can find the toggle for old/new reddit at the bottom of the account preferences.
