### ISSUE TITLE
[Bug]: Error when trying to run script

### ISSUE THREAD

**Issue by MoltaExlips** [elebumm/RedditVideoMakerBot#1651]
### Describe the bug

 Saving Text to MP3 files...                                                                      │╰──────────────────────────────────────────────────────────────────────────────────────────────────╯╭──────────────────────────────────────────────────────────────────────────────────────────────────╮│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at  ││ GitHub or the Discord community.                                                                 ││ Version: 3.1                                                                                     ││ Error: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try ││ again.                                                                                           ││ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'transition':  ││ 0.2, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w':     ││ 1080, 'resolution_h': 1920, 'background': {'background_choice': 'minecraft',                     ││ 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',                      ││ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts':  ││ {'voice_choice': 'tiktok', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew',    ││ 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1',                ││ 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                               │╰──────────────────────────────────────────────────────────────────────────────────────────────────╯Traceback (most recent call last):
  File "main.py", line 130, in <module>
    raise err
  File "main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "main.py", line 64, in run_many
    main()
  File "main.py", line 50, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/home/ubuntu/RedditVideoMakerBot-master/video_creation/voices.py", line 51, in save_text_to_mp3
    return text_to_mp3.run()
  File "/home/ubuntu/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 67, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "/home/ubuntu/RedditVideoMakerBot-master/TTS/engine_wrapper.py", line 144, in call_tts
    self.tts_module.run(text, filepath=f"{self.path}/{filename}.mp3")
  File "/home/ubuntu/RedditVideoMakerBot-master/TTS/TikTok.py", line 111, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn't load speech. Try again.
ubuntu@instance-20230519-2225:~$ 

### Reproduction Steps

ran the bash install script got session id and ran it not wokring

### Expected behavior

It would make the video! But it gave a error

### System Information

Operating System : [Ubuntu 22.04 LTS]
Python version : [Python 3.8.10]
App version / Branch : [used the install script so latest?]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by MoltaExlips** [comment]
Forgot to add I am using oracle linux to host this
