### ISSUE TITLE
[Bug]: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by benginN** [elebumm/RedditVideoMakerBot#1652]
### Describe the bug

`Traceback (most recent call last):
  File "C:\Users\orhan\OneDrive\Belgeler\RedditVideoMakerBot-master\main.py", line 130, in <module>
    raise err
  File "C:\Users\orhan\OneDrive\Belgeler\RedditVideoMakerBot-master\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\orhan\OneDrive\Belgeler\RedditVideoMakerBot-master\main.py", line 64, in run_many
    main()
  File "C:\Users\orhan\OneDrive\Belgeler\RedditVideoMakerBot-master\main.py", line 56, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\orhan\OneDrive\Belgeler\RedditVideoMakerBot-master\video_creation\final_video.py", line 155, in make_final_video
    audio_clips_durations = [
  File "C:\Users\orhan\OneDrive\Belgeler\RedditVideoMakerBot-master\video_creation\final_video.py", line 157, in <listcomp>
    ffmpeg.probe(f"assets/temp/{reddit_id}/mp3/{i}.mp3")["format"][
  File "C:\Users\orhan\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\orhan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\orhan\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

### Reproduction Steps

I just executed the code and this happened

### Expected behavior

It to work obv

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/88718878/a3fafb7a-ea1f-457f-ae3b-b6c6075a2492)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by SiouxxieSixxsta** [comment]
this might be due to how imagemagick/moviepy is installed (another debug would be to install image magick). you can maybe be able to fix this by using a virtual environment and after installing all the requirements/libraries you can go into venv/lib/sitpackages/moviepy and go into config_defaults.py. Next scroll down to "IMAGEMAGICK_BINARY = os.getenv('IMAGEMAGICK_BINARY', 'auto-detect')" and replace it with "IMAGEMAGICK_BINARY = "C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe"" replace the path with the path to YOUR image magick exe file path and make sure there are two slashes when you paste your path. Lastly run the main py file and it should have fixed it. Hopefully that helped.

**Comment by FernandoPelarich** [comment]
> this might be due to how imagemagick/moviepy is installed (another debug would be to install image magick). you can maybe be able to fix this by using a virtual environment and after installing all the requirements/libraries you can go into venv/lib/sitpackages/moviepy and go into config_defaults.py. Next scroll down to "IMAGEMAGICK_BINARY = os.getenv('IMAGEMAGICK_BINARY', 'auto-detect')" and replace it with "IMAGEMAGICK_BINARY = "C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe"" replace the path with the path to YOUR image magick exe file path and make sure you put two slashes where there is only one slash after you paste it. Lastly save the file and run the main py file and it should have fixed it. Hopefully that helped.

This didn't work for me. I keep getting the same error...
