### ISSUE TITLE
Modules not running correctly

### ISSUE THREAD

**Issue by andrewweir410** [elebumm/RedditVideoMakerBot#166]
These are the errors I am getting:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from video_creation.background import download_background, chop_background_video
  File "/home/runner/MessyGratefulSphere/video_creation/background.py", line 4, in <module>
    from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
  File "/home/runner/MessyGratefulSphere/venv/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_tools.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/home/runner/MessyGratefulSphere/venv/lib/python3.8/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/home/runner/MessyGratefulSphere/venv/lib/python3.8/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/home/runner/MessyGratefulSphere/venv/lib/python3.8/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

**Comment by andrewweir410** [comment]
> have you ran `pip install -r requirements.txt`

Yes I have run it already.
