### ISSUE TITLE
[Bug]: module 'translators' has no attribute 'google'

### ISSUE THREAD

**Issue by MaxDeepCoder** [elebumm/RedditVideoMakerBot#1661]
### Describe the bug

Traceback (most recent call last):
  File "C:\Users\stefa\Downloads\RedditVideoMakerBot-3.1\main.py", line 130, in <module>
    raise err
  File "C:\Users\stefa\Downloads\RedditVideoMakerBot-3.1\main.py", line 111, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\stefa\Downloads\RedditVideoMakerBot-3.1\main.py", line 64, in run_many
    main()
  File "C:\Users\stefa\Downloads\RedditVideoMakerBot-3.1\main.py", line 50, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\Downloads\RedditVideoMakerBot-3.1\video_creation\voices.py", line 51, in save_text_to_mp3
    return text_to_mp3.run()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\Downloads\RedditVideoMakerBot-3.1\TTS\engine_wrapper.py", line 67, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stefa\Downloads\RedditVideoMakerBot-3.1\TTS\engine_wrapper.py", line 175, in process_text
    translated_text = ts.google(text, to_language=lang)
                      ^^^^^^^^^
AttributeError: module 'translators' has no attribute 'google'

### Reproduction Steps

Installed and setup?

### Expected behavior

Make the video

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.

**Comment by MaxDeepCoder** [comment]
UPDATE TRANSLATORS TO 5.3.1 USING

pip install translators==5.3.1

**Comment by melvbouv** [comment]
thanks a lot !
