### ISSUE TITLE
[Bug]: GUI not launching on 3.2

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1675]
### Describe the bug

When I do python3 GUI.py and go to "Settings" i get this error:

```
[2023-05-30 17:43:32,611] ERROR in app: Exception on /settings [GET]
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/GUI.py", line 85, in settings
    return render_template(
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/GUI/settings.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/GUI/layout.html", line 130, in top-level template code
    {% block main %}{% endblock %}
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/GUI/settings.html", line 208, in block 'main'
    {% for background in checks["background_choice"]["options"][1:] %}
  File "/usr/local/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'background_choice'
```

background_choice is no longer an option, its background_videos. So the GUI needs to be updated as such.

### Reproduction Steps

Launch GUI by

```
python3 GUI.py
````

Go to "Settings" in the web browser.

### Expected behavior

It's supposed to pull up the /settings page, but I get unexpected error instead.

### System Information

Operating System : MacOS 13.4
Python version : Python 3.10
App version / Branch : latest (3.2)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by joshholly** [comment]
Tried changing background_choice to background_video and get this error now

```
127.0.0.1 - - [30/May/2023 17:58:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/May/2023 17:58:08] "GET /videos.json HTTP/1.1" 200 -
[2023-05-30 17:58:09,415] ERROR in app: Exception on /settings [GET]
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/GUI.py", line 110, in settings
    return render_template(
  File "/usr/local/anaconda3/lib/python3.10/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/anaconda3/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/GUI/settings.html", line 208, in template
    {% for background in checks["background_video]["options"][1:] %}
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'options'
```

**Comment by joshholly** [comment]
Please update the GUI interface to include the new options like Background Audio and Background Video and others.

**Comment by joshholly** [comment]
Yeah the GUI is out of date. It doesn't take into account for the new background_video param for the background video. So the GUI needs to be updated for 3.2

**Comment by OpenSourceSimon** [comment]
Thanks for reporting the bug! The current GUI is indeed out dated, I'll keep this issue open to track the progress
