### ISSUE TITLE
if os.getenv("REDDIT_2FA").lower() == "yes":

### ISSUE THREAD

**Issue by Antartiida** [elebumm/RedditVideoMakerBot#168]
Getting new issue with latest build, thanks for the help. 

C:\Users\camus\Desktop\Tikitaka>python main.py

  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
                                to reach out to me on Twitter or submit a GitHub issue.

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting AskReddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\camus\Desktop\Tikitaka\main.py", line 17, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\camus\Desktop\Tikitaka\reddit\subreddit.py", line 18, in get_subreddit_threads
    if os.getenv("REDDIT_2FA").lower() == "yes":
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by Antartiida** [comment]
Nevermind, i didnt noticed the env. template was changed and i left the previous one as it had my details already. 
switched .env and filled information and worked.
