### ISSUE TITLE
[Bug]: What does this errror mean?

### ISSUE THREAD

**Issue by donperawn** [elebumm/RedditVideoMakerBot#1697]
### Describe the bug

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.2                                                                                                        │
│ Error: [WinError 2] The system cannot find the file specified                                                       │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,               │
│ 'storymodemethod': 1, 'storymode_max_length': 200, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,         │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,        │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',            │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':    │
│ 'tiktok', 'random_voice': False, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',                │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_007', 'tiktok_sessionid': │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\Ilias\RedditVideoMakerBot\main.py", line 132, in <module>
    raise err
  File "C:\Users\Ilias\RedditVideoMakerBot\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Ilias\RedditVideoMakerBot\main.py", line 69, in run_many
    main()
  File "C:\Users\Ilias\RedditVideoMakerBot\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\Ilias\RedditVideoMakerBot\video_creation\final_video.py", line 189, in make_final_video
    audio_clips_durations = [
  File "C:\Users\Ilias\RedditVideoMakerBot\video_creation\final_video.py", line 191, in <listcomp>
    ffmpeg.probe(f"assets/temp/{reddit_id}/mp3/{i}.mp3")["format"][
  File "C:\Users\Ilias\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
PS C:\Users\Ilias\RedditVideoMakerBot>

### Reproduction Steps

python3 main.py

### Expected behavior

I exptected the video to be produced but it didnt

### System Information

Operating System : win 11
Python version : 3.10
App version / Branch : 3.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by FernandoPelarich** [comment]
I have the same issue
