### ISSUE TITLE
[Bug]: ffmpeg crashes during "Creating Final Video

### ISSUE THREAD

**Issue by joshholly** [elebumm/RedditVideoMakerBot#1702]
### Describe the bug

Right when it gets to "Collecting Audio Files" then it goes to 100%. I get the following error:

```
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Creating the final video 🎥                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Collecting the audio files... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.         │
│ Version: 3.2                                                                                                                             │
│ Error: ffmpeg error (see stderr output for detail)                                                                                       │
│ Config: {'allow_nsfw': True, 'theme': 'light', 'times_to_run': 10, 'opacity': 0.85, 'transition': 1.0, 'storymode': True,                │
│ 'storymodemethod': 1, 'storymode_max_length': 3000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.2, 'sub_overlay': False,       │
│ 'background': {'background_video': 'satisfying8', 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',            │
│ 'background_thumbnail_font_size': 20, 'background_thumbnail_font_color': '255,255,255', 'background_audio': 'lofi',                      │
│ 'background_audio_volume': 0.15, 'enable_extra_audio': True}, 'tts': {'voice_choice': 'elevenlabs', 'aws_polly_voice': 'Joanna',         │
│ 'elevenlabs_voice_name': 'Arnold', 'elevenlabs_api_key': 'REDACTED', 'streamlabs_polly_voice': 'Arnold', 'tiktok_voice': 'en_us_007',    │
│ 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 1.0, 'no_emojis': True, 'random_voice':    │
│ True}}                                                                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/main.py", line 132, in <module>
    raise err
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/main.py", line 111, in <module>
    main(post_id)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "/Users/wafflehacker/Sites/RedditVideoMakerBot/video_creation/final_video.py", line 206, in make_final_video
    ffmpeg.output(
  File "/usr/local/anaconda3/lib/python3.10/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

```

### Reproduction Steps

Run main.py on a reddit thread
Let it go through the whole process
Crash on ffmpeg

### Expected behavior

Create video

### System Information

Operating System : MacOS
Python version : Python 3.10
App version / Branch : Latest (master)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by joshholly** [comment]
I'm an idot. I had it in story mode , forgot to disable it for an AskReddit thread. Toggled story mode to false and it worked!
