### ISSUE TITLE
[Bug]: TypeError: GTTS.run() got an unexpected keyword argument 'random_voice'

### ISSUE THREAD

**Issue by Player2Seven** [elebumm/RedditVideoMakerBot#1706]
### Describe the bug

Traceback (most recent call last):
  File "C:\Users\User\Downloads\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\main.py", line 132, in <module>
    raise err
  File "C:\Users\User\Downloads\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\User\Downloads\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\main.py", line 69, in run_many
    main()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\User\Downloads\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\video_creation\voices.py", line 53, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\TTS\engine_wrapper.py", line 77, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\User\Downloads\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\TTS\engine_wrapper.py", line 154, in call_tts
    self.tts_module.run(
TypeError: GTTS.run() got an unexpected keyword argument 'random_voice'

### Reproduction Steps

Ran main.py

### Expected behavior

for it to make a video

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by electro199** [comment]
will be fixed

**Comment by rafaelsoley** [comment]
Apparently it will be fixed in the next  update, until then, heres a temporary fix:

Go to file `engine_wrapper.py`, go to line 157 (`random_voice=settings.config["settings"]["tts"]["random_voice"], `, and comment that line.

Line 157 then should look something like this:
`#random_voice=settings.config["settings"]["tts"]["random_voice"],`

Notice, this is an experimental and temporary fix. This will fix this specific issue with the Google TTS voice setting, but might break some options (like the random_voice for other TTS services)

@Player2Seven
