### ISSUE TITLE
[Bug]: error at Creating final video 

### ISSUE THREAD

**Issue by jonniz123** [elebumm/RedditVideoMakerBot#1721]
### Describe the bug

Screenshots from reddit, audio, and video are created in the temp folder. However, once its up to the 'Creating the final video' step,  I received an error Reddit

### Reproduction Steps

Ran python main.py

 Creating the final video 🎥                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[08:59:10]  Video Will Be: 49 Seconds Long                                                            final_video.py:210
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Rendering the video 🎥                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Progress:   0%|                                                                                                        ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the        │
│ Discord community.                                                                                                   │
│ Version: 3.2                                                                                                         │
│ Error: ffmpeg error (see stderr output for detail)                                                                   │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,                │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,         │
│ 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,         │
│ 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',             │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':     │
│ 'tiktok', 'random_voice': False, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',                 │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid':  │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}

Traceback (most recent call last):
  File "C:\Users\rx7_j\Downloads\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "C:\Users\rx7_j\Downloads\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\rx7_j\Downloads\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "C:\Users\rx7_j\Downloads\RedditVideoMakerBot-master\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\rx7_j\Downloads\RedditVideoMakerBot-master\video_creation\final_video.py", line 376, in make_final_video
    ffmpeg.output(

### Expected behavior

Final video to be created

### Screenshots

![Screenshot 2023-06-26 090305](https://github.com/elebumm/RedditVideoMakerBot/assets/137732765/2cda3cf2-911a-4f39-b09b-8ceff0f8a3aa)
![Screenshot 2023-06-26 090324](https://github.com/elebumm/RedditVideoMakerBot/assets/137732765/0fb280dc-ec33-439b-ba38-d54b4ed07f7b)

### System Information

Operating System :  Windows 11]
Python version :  Python 3.1
App version / Branch : 3.2

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by jonniz123** [comment]
I replaced ffmpeg, ffplay and ffprobe from the official website.
working now!
