### ISSUE TITLE
[Bug]: Error when Translating Text

### ISSUE THREAD

**Issue by MAXLOL2965** [elebumm/RedditVideoMakerBot#1734]
### Describe the bug

Translating Text...

Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the        │
Discord community.                                                                                                   │
Version: 3.2                                                                                                         │
Error: module 'translators' has no attribute 'google'                                                                │
Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,                 │
'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,         │
'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15,         │
'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',             │
'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice':     │
'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',                  │
'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid':  │
'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                  │

Traceback (most recent call last):
  File "X:\Desktop\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "X:\Desktop\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "X:\Desktop\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "X:\Desktop\RedditVideoMakerBot-master\main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "X:\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 53, in save_text_to_mp3
    return text_to_mp3.run()
  File "X:\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 77, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "X:\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 189, in process_text
    translated_text = translators.google(text, to_language=lang)
AttributeError: module 'translators' has no attribute 'google'

### Reproduction Steps

ran python main.py after configuring everything

### Expected behavior

for it to generate the video

### Screenshots

![grafik](https://github.com/elebumm/RedditVideoMakerBot/assets/83956322/fc5bf1c6-5660-4cac-9c64-738ed3c33407)

### System Information

Operating System : Windows 11
Python version : Python 3.10.0
App version / Branch : latest, master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

i have found a similar issue [here](https://github.com/elebumm/RedditVideoMakerBot/issues/1377), however i used the awspolly and not the tiktok voice option. Also the issue thread is a bit old so i wasn't sure if tiktok voices still weren't working.

**Comment by MAXLOL2965** [comment]
Ok, i found the issue (my error). had to change `post_lang = "en-US"` to `post_lang = ""`
