### ISSUE TITLE
[Bug]: Cannot render video due to ffmpeg error.

### ISSUE THREAD

**Issue by Icaru-s** [elebumm/RedditVideoMakerBot#1747]
### Describe the bug

During the final video render the program stops and outputs an ffmpeg error stating to check the stderr output for the error. ffmpeg has been uninstalled and reinstalled multiple times both manually and through pip with no success.

### Reproduction Steps

Ran the fully set up program. The program runs successfully until the render step where the error occurs.

### Expected behavior

The video should render and be output to the folder.

### Screenshots

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\RedditVideoMakerBot\main.py", line 132, in <module>
    raise err
  File "C:\Users\\AppData\Local\Programs\Python\Python310\RedditVideoMakerBot\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\\AppData\Local\Programs\Python\Python310\RedditVideoMakerBot\main.py", line 69, in run_many
    main()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\RedditVideoMakerBot\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\RedditVideoMakerBot\video_creation\final_video.py", line 376, in make_final_video
    ffmpeg.output(
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

### System Information

Operating System : Windows 10
Python version : 3.10
App version / Branch : latest

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by kadudutra** [comment]
try to remove FFmpeg from the root of the project and install it globally, it worked for me.

**Comment by Stokke93** [comment]
I've gone down the rabbit hole...

I installed ffmpeg globally as kadudutra  pointed out.


altho it seems that it is the actual displaying of progress that is the issue.

I removed an exit(1) statement in an exception handler, and it worked. Altho, not a fix, but a workaround x)

I also implemented some print functions to see more of what was going into the calculation that was supposed to return out of the function "get_latest_ms_progress"



[07:06:53]  Video Will Be: 72 Seconds Long                   final_video.py:214
┌─────────────────────────────────────────────────────────────────────────────┐
│ Rendering the video 🎥                                                      │
└─────────────────────────────────────────────────────────────────────────────┘

Progress:   0%|          File Path: <tempfile._TemporaryFileWrapper object at 0x0000012E38DB13F0>
File Path: <tempfile._TemporaryFileWrapper object at 0x0000012E38DB13F0>
Line: frame=0
Line: fps=0.00
Line: stream_0_0_q=0.0
Line: bitrate=N/A
Line: total_size=0
Line: out_time_us=N/A
Line: out_time_ms=N/A
Extracted Value: N/A

Exception in thread ProgressFfmpeg:
Traceback (most recent call last):
  File "C:\Users\Stokk\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Stokk\OneDrive\Documents\GitHub\RedditVideoMakerBot\video_creation\final_video.py", line 37, in run
    latest_progress = self.get_latest_ms_progress()
  File "C:\Users\Stokk\OneDrive\Documents\GitHub\RedditVideoMakerBot\video_creation\final_video.py", line 53, in get_latest_ms_progress
    return int(out_time_ms) / 1000000.0
ValueError: invalid literal for int() with base 10: 'N/A\n'
