### ISSUE TITLE
[Bug]: ffmpeg 

### ISSUE THREAD

**Issue by dolev765** [elebumm/RedditVideoMakerBot#1753]
### Describe the bug

I have installed the latest ffmpeg from the website I put it  
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/84907179/d73bd314-2ff9-4d3d-97e0-c650401668ae)
and I put the it in user variables (path ) C:\Users\dolev\OneDrive\Desktop\RedditVideoMakerBot like this 
but I still get this error  : 
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/84907179/75788536-c836-4576-82d4-5137b02e10a5)

### Reproduction Steps

python main.py 

### Expected behavior

just work 

### Screenshots

the error 
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/84907179/54ab5d0c-a0e4-4d46-9112-23652bb6cb60)

### System Information

Operating System : [e.g. Windows 10]
Python version : [e.g. Python 3.10]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by dolev765** [comment]
the error has changed into this 
`Traceback` (most recent call last):
  File "C:\Users\dolev\OneDrive\Desktop\RedditVideoMakerBot\main.py", line 132, in <module>
    raise err
  File "C:\Users\dolev\OneDrive\Desktop\RedditVideoMakerBot\main.py", line 111, in <module>
    main(post_id)
  File "C:\Users\dolev\OneDrive\Desktop\RedditVideoMakerBot\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\dolev\OneDrive\Desktop\RedditVideoMakerBot\video_creation\final_video.py", line 206, in make_final_video
    ffmpeg.output(
  File "C:\Python310\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x0000027A387360E0>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\moviepy\audio\io\readers.py", line 254, in __del__
    self.close_proc()
  File "C:\Python310\lib\site-packages\moviepy\audio\io\readers.py", line 149, in close_proc
    self.proc.terminate()
  File "C:\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid``

**Comment by dolev765** [comment]
Error still up

**Comment by KeMa0** [comment]
This fixed the bug in my case:

- pip uninstall ffmpeg
- pip uninstall ffmpeg-python
- pip install ffmpeg-python

**Comment by thisisrick25** [comment]
This doesn't work
