### ISSUE TITLE
[Bug]: Unable to generate video due to FileNotFound Error

### ISSUE THREAD

**Issue by OperationOfTheCloud** [elebumm/RedditVideoMakerBot#1759]
### Describe the bug

The bug makes the code error at the end at is unable to find some file (I can't figure out which file)

### Reproduction Steps

Honestly, I don't know how to reproduce it, it just happened to me.

### Expected behavior

I was expecting a video to be generated at the end.

### Screenshots

Traceback (most recent call last):
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\main.py", line 132, in <module>
    raise err
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\main.py", line 69, in run_many
    main()
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\video_creation\final_video.py", line 189, in make_final_video
    audio_clips_durations = [
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\video_creation\final_video.py", line 191, in <listcomp>
    ffmpeg.probe(f"assets/temp/{reddit_id}/mp3/{i}.mp3")["format"][
  File "C:\Users\Chase\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
![image](https://github.com/elebumm/RedditVideoMakerBot/assets/90874854/e7d6ccfa-2666-4742-86a4-0c12e8054b72)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by OperationOfTheCloud** [comment]
Additionally, the following error appears when trying to generate a video after reinstalling ffmpeg-python.
Traceback (most recent call last):
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\main.py", line 132, in <module>
    raise err
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\main.py", line 69, in run_many
    main()
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\main.py", line 61, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\video_creation\final_video.py", line 189, in make_final_video
    audio_clips_durations = [
  File "D:\AI Video Generators\Reddit Story Time\RedditVideoMakerBot\video_creation\final_video.py", line 191, in <listcomp>
    ffmpeg.probe(f"assets/temp/{reddit_id}/mp3/{i}.mp3")["format"][
  File "C:\Users\Chase\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x000001DF12576560>
Traceback (most recent call last):
  File "C:\Users\Chase\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\audio\io\readers.py", line 254, in __del__
    self.close_proc()
  File "C:\Users\Chase\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\audio\io\readers.py", line 149, in close_proc
    self.proc.terminate()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1573, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
