### ISSUE TITLE
[Bug]: i get this when i am runing the code 

### ISSUE THREAD

**Issue by shviam-2018** [elebumm/RedditVideoMakerBot#1773]
### Describe the bug

Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.  │
│ Version: 3.2                                                                                                                      │
│ Error: 'silence_duration'                                                                                                         │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1,       │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'background': {'background_video':         │
│ 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail':    │
│ False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':      │
│ '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': True, 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key':   │
│ 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid':   │
│ 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'no_emojis': False}}                                                        │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\sikok\OneDrive\Desktop\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\main.py", line 132, in <module>
    raise err
  File "C:\Users\sikok\OneDrive\Desktop\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\sikok\OneDrive\Desktop\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\main.py", line 69, in run_many
    main()
  File "C:\Users\sikok\OneDrive\Desktop\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\sikok\OneDrive\Desktop\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\video_creation\voices.py", line 53, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\sikok\OneDrive\Desktop\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\TTS\engine_wrapper.py", line 105, in run
    self.split_post(comment["comment_body"], idx)  # Split the comment
  File "C:\Users\sikok\OneDrive\Desktop\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\TTS\engine_wrapper.py", line 120, in split_post
    self.create_silence_mp3()
  File "C:\Users\sikok\OneDrive\Desktop\RedditVideoMakerBot-3.2\RedditVideoMakerBot-3.2\TTS\engine_wrapper.py", line 172, in create_silence_mp3
    silence_duration = settings.config["settings"]["tts"]["silence_duration"]
KeyError: 'silence_duration'

### Reproduction Steps

i ran the script

### Expected behavior

it should have created the video

### Screenshots

![image](https://github.com/elebumm/RedditVideoMakerBot/assets/122033083/c259a2f4-4a90-4c37-942d-0c2e30c6ac81)
<img width="960" alt="Screenshot 2023-08-02 133902" src="https://github.com/elebumm/RedditVideoMakerBot/assets/122033083/c4df6599-7415-4202-8ea4-933c26ddb2ab">

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by shviam-2018** [comment]
k
