### ISSUE TITLE
received 401 HTTP response

### ISSUE THREAD

**Issue by v6r** [elebumm/RedditVideoMakerBot#178]
I can normal run main.py. It gives me this output: 

```
C:\Users\Max\Downloads\RedditVideoMakerBot-master>main.py


  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
                                to reach out to me on Twitter or submit a GitHub issue.


╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Getting AskReddit threads...                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\Max\Downloads\RedditVideoMakerBot-master\main.py", line 17, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\Max\Downloads\RedditVideoMakerBot-master\reddit\subreddit.py", line 52, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

C:\Users\Max\Downloads\RedditVideoMakerBot-master>
```

I dont know why i have this error the only thing i could think is i pasted somethign wrong in the .env. I was not sure what to put into Clien_ID so i just pasted the name of my app in.

![image](https://user-images.githubusercontent.com/83277314/171748876-bba78304-0fdb-4d8e-be5a-025801d354dd.png)

and this is my application settings:
![image](https://user-images.githubusercontent.com/83277314/171749121-d6594806-569a-4c88-9116-56ae141dd955.png)

**Comment by ProjectSlxsh** [comment]
The Name is not what you are supposed to use for the id you are supposed to use the letters and numbers that you have scratched out under the words personal use script and from what i can see its a z

**Comment by v6r** [comment]
> The Name is not what you are supposed to use for the id you are supposed to use the letters and numbers that you have scratched out under the words personal use script and from what i can see its a z

ah thanks. i was not shure about this. Works now ty

**Comment by ProjectSlxsh** [comment]
your welcome, trying to get my own issue request fixed, so right now I am sitting here bored trying to help people with the same thing i accidentally did
