### ISSUE TITLE
Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by IStayThatWayCoding** [elebumm/RedditVideoMakerBot#18]
$ python3 main.py
Traceback (most recent call last):
  File "C:\Users\justi\RedditVideoMakerBot\main.py", line 3, in <module>
    from reddit.askreddit import get_askreddit_threads
  File "C:\Users\justi\RedditVideoMakerBot\reddit\askreddit.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by vradinolfi** [comment]
pip install python-dotenv fixes this
