### ISSUE TITLE
Runtime Error Asking for FFMPEG EXE

### ISSUE THREAD

**Issue by M4ttiG** [elebumm/RedditVideoMakerBot#183]
Here's all the message it gives me, I'm not sure what im doing wrong. Im using a M1 MacBook if that makes any difference?

Traceback (most recent call last):
  File "/Users/me/Downloads/Safari/RedditVideoMakerBot-master-2/main.py", line 5, in <module>
    from video_creation.background import download_background, chop_background_video
  File "/Users/me/Downloads/Safari/RedditVideoMakerBot-master-2/video_creation/background.py", line 6, in <module>
    from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_tools.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

**Comment by benf2004** [comment]
Thank you! Brew coming in clutch. I did not get the sox error.

**Comment by D3FUZED** [comment]
> I solved this error by typing brew install ffmpeg now i’m getting a new error “ModuleNotFoundError: No module named sox”
> […](#)
> On 3 Jun 2022, at 01:04, benf2004 ***@***.***> wrote: ﻿ Getting the same errror — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

Did you run 'playwright install' and 'playwright install-deps' ?

**Comment by M4ttiG** [comment]
i did mate and confirmed it

**Comment by FreebieII** [comment]
Hi @M4ttiG,

Sox is not used in the `master` branch so this issue will not be solved, as it's not part of the code.



I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
