### ISSUE TITLE
[Bug]: NSFW screenshots not getting captured

### ISSUE THREAD

**Issue by shridharke** [elebumm/RedditVideoMakerBot#1879]
### Describe the bug

When I try to enable allow_nsfw flag in the config.toml file, all the processes go through fine. But in the screenshot capture stage, it fails with the below error.

Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Something went wrong!
Something went wrong with making the screenshots! Do you want to skip the post? (y/n) n
Do you want the error traceback for debugging purposes? (y/n)y
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                         │
│ Version: 3.2.1                                                                                                                                           │
│ Error: Timeout 30000ms exceeded.                                                                                                                         │
│ =========================== logs ===========================                                                                                             │
│ waiting for locator("[data-test-id=\"post-content\"]")                                                                                                   │
│ ============================================================                                                                                             │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length':      │
│ 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'background': {'background_video': 'minecraft', 'background_audio': 'lofi',               │
│ 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial',                │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': True,         │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice':   │
│ 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "D:\RedditAutomation\RedditVideoMakerBot\main.py", line 132, in <module>
    raise err
  File "D:\RedditAutomation\RedditVideoMakerBot\main.py", line 111, in <module>
    main(post_id)
  File "D:\RedditAutomation\RedditVideoMakerBot\main.py", line 53, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "D:\RedditAutomation\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 203, in get_screenshots_of_reddit_posts
    raise e
  File "D:\RedditAutomation\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 185, in get_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path=postcontentpath)
  File "C:\Users\91915\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 17568, in screenshot
    self._sync(
  File "C:\Users\91915\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 109, in _sync
    return task.result()
  File "C:\Users\91915\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 529, in screenshot
    return await self._with_element(
  File "C:\Users\91915\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 115, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\91915\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 315, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\91915\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 322, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\91915\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\91915\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
  File "C:\Users\91915\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("[data-test-id=\"post-content\"]")

### Reproduction Steps

1. Set allow_nsfw="true" in the config file
2. Run the main.py file and start the bot

### Expected behavior

Fetch the screenshots from the reddit post and create the video.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by salam133** [comment]
Bro pls i am facing this issue too

**Comment by testacc123-create** [comment]
@shridharke  Found the fix: Log into Reddit(I did it on pc, don't know if it will work on phone), click on your icon on the top right, User Settings>Feed Settings, and turn on "Show mature (18+) content". That will remove the warning when entering NSFW posts. Worked for me, hope it works for you. Be well

**Comment by yasdev08** [comment]
bruh same for me as well !!
