### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'toml'

### ISSUE THREAD

**Issue by danilorcsilva** [elebumm/RedditVideoMakerBot#1924]
### Describe the bug

C:\Users\USER\Desktop\Robô do Reddit 3.2 (1)\RedditVideoMakerBot-3.2> python3 main.py
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Robô do Reddit 3.2 (1)\RedditVideoMakerBot-3.2\main.py", line 11, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\USER\Desktop\Robô do Reddit 3.2 (1)\RedditVideoMakerBot-3.2\reddit\subreddit.py", line 5, in <module>
    from utils import settings
  File "C:\Users\USER\Desktop\Robô do Reddit 3.2 (1)\RedditVideoMakerBot-3.2\utils\settings.py", line 4, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'

### Reproduction Steps

C:\Users\USER\Desktop\Robô do Reddit 3.2 (1)\RedditVideoMakerBot-3.2> python3 main.py

### Expected behavior

C:\Users\USER\Desktop\Robô do Reddit 3.2 (1)\RedditVideoMakerBot-3.2> python3 main.py

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by robinaerts** [comment]
Did you install the requirements?

```
pip install -r requirements.txt
```
