### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ffmpeg' on Mac

### ISSUE THREAD

**Issue by Diwas37** [elebumm/RedditVideoMakerBot#193]
ERROR AT:
│ Finding a spot in the background video to chop...✂️                                                                                                                                   

ERROR:
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    chop_background_video(length)
  File "/Users/diwas/tiktok_bot/RedditVideoMakerBot/video_creation/background.py", line 37, in chop_background_video
    background = VideoFileClip("assets/mp4/background.mp4")
  File "/Users/diwas/Library/Python/3.8/lib/python/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/Users/diwas/Library/Python/3.8/lib/python/site-packages/moviepy/video/io/ffmpeg_reader.py", line 35, in __init__
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration,
  File "/Users/diwas/Library/Python/3.8/lib/python/site-packages/moviepy/video/io/ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/ffmpeg'

 I can't do any thing to usr/bin folder as mac won't let me and the last line tells I should add ffmpeg there. so any one know how to get around this error .btw I'm on MAC m1 and tried disabling SIP.

**Comment by unethicalwhitehat** [comment]
brew install ffmpeg

**Comment by FreebieII** [comment]
Hi @Diwas37,

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
