### ISSUE TITLE
[Bug]:  TTS.TikTok.TikTokTTSException: Code: 2, reason: the text is too long, message: Text too long to create speech audio

### ISSUE THREAD

**Issue by devrhis** [elebumm/RedditVideoMakerBot#1951]
### Describe the bug

Traceback (most recent call last):
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 88, in run
    self.call_tts(f"postaudio-{idx}", process_text(text))
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 149, in call_tts
    self.tts_module.run(
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\TikTok.py", line 109, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 2, reason: the text is too long, message: Text too long to create speech audio

### Reproduction Steps

Traceback (most recent call last):
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 88, in run
    self.call_tts(f"postaudio-{idx}", process_text(text))
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 149, in call_tts
    self.tts_module.run(
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\TikTok.py", line 109, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 2, reason: the text is too long, message: Text too long to create speech audio

### Expected behavior

Traceback (most recent call last):
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 88, in run
    self.call_tts(f"postaudio-{idx}", process_text(text))
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 149, in call_tts
    self.tts_module.run(
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\TikTok.py", line 109, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 2, reason: the text is too long, message: Text too long to create speech audio

### Screenshots

Traceback (most recent call last):
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 132, in <module>
    raise err
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 69, in run_many
    main()
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\main.py", line 51, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 88, in run
    self.call_tts(f"postaudio-{idx}", process_text(text))
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\engine_wrapper.py", line 149, in call_tts
    self.tts_module.run(
  File "C:\Users\Cigaax\Desktop\RedditVideoMakerBot-master\TTS\TikTok.py", line 109, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 2, reason: the text is too long, message: Text too long to create speech audio

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

Could anyone help with this error?

**Comment by devrhis** [comment]
Solved, I deleted the config.toml file and redid the entire process
