### ISSUE TITLE
Postprocessing error

### ISSUE THREAD

**Issue by realcompi** [elebumm/RedditVideoMakerBot#197]
i get this error:

`[download] Destination: assets/mp4/background.f308.webm
[download] 100% of 5.84GiB in 00:59
[download] Destination: assets/mp4/background.f251.webm
[download] 100% of 80.34MiB in 00:00
[Merger] Merging formats into "assets/mp4/background.mp4"
ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3204, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3374, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3361, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3340, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 827, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 282, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 321, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    download_background()
  File "/root/RedditVideoMakerBot/video_creation/background.py", line 35, in download_background
    ydl.download("https://www.youtube.com/watch?v=n_Dv4JMiwK8")
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3254, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3230, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1479, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1535, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 2640, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3206, in process_info
    self.report_error('Postprocessing: %s' % str(err))
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
`

**Comment by jpdeleon** [comment]
I also encountered this issue. Seems like a ytd-dl issue: https://github.com/yt-dlp/yt-dlp/issues/871

**Comment by CallumIO** [comment]
Closing due to being stale, try with newest version
