### ISSUE TITLE
[Bug]: Help me the resolv this error

### ISSUE THREAD

**Issue by godblessu** [elebumm/RedditVideoMakerBot#2044]
### Describe the bug

| Getting subreddit threads...                                                |
+-----------------------------------------------------------------------------+
Using subreddit: r/AskReddit+Redditdev from TOML config
You are trying to use story mode on post with no post text
Traceback (most recent call last):
  File "D:\soft\python\RedditVideoMakerBot\main.py", line 114, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\soft\python\RedditVideoMakerBot\main.py", line 69, in run_many
    main()
  File "D:\soft\python\RedditVideoMakerBot\main.py", line 49, in main
    reddit_object = get_subreddit_threads(POST_ID)
  File "D:\soft\python\RedditVideoMakerBot\reddit\subreddit.py", line 111, in get_subreddit_threads
    print_substep(f"Video will be: {submission.title} :thumbsup:", style="bold green")
  File "D:\soft\python\RedditVideoMakerBot\utils\console.py", line 35, in print_substep
    console.print(text, style=style)
  File "D:\soft\python\lib\site-packages\rich\console.py", line 1672, in print
    with self:
  File "D:\soft\python\lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "D:\soft\python\lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "D:\soft\python\lib\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "D:\soft\python\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "D:\soft\python\lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "D:\soft\python\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f44d' in position 32: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\soft\python\RedditVideoMakerBot\main.py", line 126, in <module>
    print_step(
  File "D:\soft\python\RedditVideoMakerBot\utils\console.py", line 24, in print_step
    console.print(panel)
  File "D:\soft\python\lib\site-packages\rich\console.py", line 1672, in print
    with self:
  File "D:\soft\python\lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "D:\soft\python\lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "D:\soft\python\lib\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "D:\soft\python\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "D:\soft\python\lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "D:\soft\python\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f44d' in position 32: illegal multibyte sequence

### Reproduction Steps

Using subreddit: r/AskReddit+Redditdev from TOML config

### Expected behavior

set subreddit: AskReddit+Redditdev  error？

### Screenshots

![屏幕截图 2024-05-08 223338](https://github.com/elebumm/RedditVideoMakerBot/assets/4978287/22337c2c-3d31-4901-958a-3bef418a738f)

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.10.8 ]
App version / Branch : [master]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Cyteon** [comment]
Change your password to only have latin characters
