### ISSUE TITLE
[Bug]: TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn’t load speech. Try again.

### ISSUE THREAD

**Issue by gitgit12312** [elebumm/RedditVideoMakerBot#2122]
### Describe the bug

this is my first time using python and all that and when I run the bot it says TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn’t load speech. Try again.

### Reproduction Steps

i tried to run the bot

### Expected behavior

make a video

### Screenshots

Traceback (most recent call last):
  File "C:\Users\wacim\OneDrive\Documents\RedditVideoMakerBot\main.py", line 131, in <module>
    raise err
  File "C:\Users\wacim\OneDrive\Documents\RedditVideoMakerBot\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\wacim\OneDrive\Documents\RedditVideoMakerBot\main.py", line 68, in run_many
    main()
  File "C:\Users\wacim\OneDrive\Documents\RedditVideoMakerBot\main.py", line 50, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\wacim\OneDrive\Documents\RedditVideoMakerBot\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\wacim\OneDrive\Documents\RedditVideoMakerBot\TTS\engine_wrapper.py", line 74, in run
    self.call_tts("title", process_text(self.reddit_object["thread_title"]))
  File "C:\Users\wacim\OneDrive\Documents\RedditVideoMakerBot\TTS\engine_wrapper.py", line 147, in call_tts
    self.tts_module.run(
  File "C:\Users\wacim\OneDrive\Documents\RedditVideoMakerBot\TTS\TikTok.py", line 109, in run
    raise TikTokTTSException(status_code, data["message"])
TTS.TikTok.TikTokTTSException: Code: 1, reason: probably the aid value isn't correct, message: Couldn’t load speech. Try again.

### System Information

Operating System : [e.g. Windows 11]
Python version : [e.g. Python 3.6]
App version / Branch : [e.g. latest, V2.0, master, develop]

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Antoinewf3** [comment]
Hey everyone, just want to say i love the project, just started to try it. 

Here to add that i've been getting the same error here. 

cfg.toml was configured using shell and modified via vscode and i dnt get any errors regarding username or session id but still get the same error as my neighbour from up here.

I added screenshot maybe this will help. Thx :)

![Error2](https://github.com/user-attachments/assets/44c53170-6c4d-4964-9ce1-ea51c4748cd7)
![Error1](https://github.com/user-attachments/assets/eca327c8-8dde-432c-8976-e84a5db1b847)

**Comment by khalid-121** [comment]
same here

**Comment by aimericdrk** [comment]
fixed here : https://github.com/elebumm/RedditVideoMakerBot/issues/1582#issuecomment-1526285672
