### ISSUE TITLE
[Bug]: Screenshot Error

### ISSUE THREAD

**Issue by SureelWillows** [elebumm/RedditVideoMakerBot#2129]
### Describe the bug

It starts off fine, makes mp3 files and while taking screen shots, it shows a error:
"Something went wrong!
Something went wrong with making the screenshots! Do you want to skip the post? (y/n)"

### Reproduction Steps

Launch the program (py main.py)
wait..

### Expected behavior

it would work as fine and error wouldnt occur

### Screenshots

![image](https://github.com/user-attachments/assets/e47a63ac-c5cb-4cb9-b8b7-b78125eec34c)

![image](https://github.com/user-attachments/assets/9e490bb3-8c9b-431e-8708-4f4d3cef08af)

![image](https://github.com/user-attachments/assets/d2810e1f-e860-4689-bdac-59fb1926df9a)

### System Information

Operating System : Windows 10
Python version : Python 3.10
App version / Branch : 3.3.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by UsmanChatha** [comment]
### Having the same issue:

Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Something went wrong!
Something went wrong with making the screenshots! Do you want to skip the post? (y/n) n
Do you want the error traceback for debugging purposes? (y/n)y
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the       │
│ Discord community.                                                                                                  │
│ Version: 3.3.0                                                                                                      │
│ Error: Locator.screenshot: Timeout 30000ms exceeded.                                                                │
│ Call log:                                                                                                           │
│ waiting for locator("[data-test-id=\"post-content\"]")                                                              │
│                                                                                                                     │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,               │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,        │
│ 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi',         │
│ 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False,                        │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                                  │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': True,          │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew',                   │
│ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice':   │
│ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\dell\Downloads\RedditVideoMakerBot-master\main.py", line 131, in <module>
    raise err
  File "C:\Users\dell\Downloads\RedditVideoMakerBot-master\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\dell\Downloads\RedditVideoMakerBot-master\main.py", line 68, in run_many
    main()
  File "C:\Users\dell\Downloads\RedditVideoMakerBot-master\main.py", line 52, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\dell\Downloads\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 203, in get_screenshots_of_reddit_posts
    raise e
  File "C:\Users\dell\Downloads\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 185, in get_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path=postcontentpath)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 16703, in screenshot
    self._sync(
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 531, in screenshot
    return await self._with_element(
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-test-id=\"post-content\"]")

**Comment by Gnlop** [comment]
Having the same issue, so I checked the elements of the web page and found that there was no "data-test-id" element

**Comment by Gnlop** [comment]
**I have the same problem as you, but I do not know the cause of this error. I have tried several times and found that this error does not occur every time, but even if I find data-test-id="post-content", the screenshot cannot be taken. I have checked the cache file. Found that the interface of the post is normally taken down, but the screenshot of the comment area can not be taken.**

Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Downloading screenshots... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the        │
│ Discord community.                                                                                                   │
│ Version: 3.3.0                                                                                                       │
│ Error: Locator.screenshot: Timeout 30000ms exceeded.                                                                 │
│ Call log:                                                                                                            │
│ waiting for locator("#t1_lk64262")                                                                                   │
│                                                                                                                      │
│ Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False,                 │
│ 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,         │
│ 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi',          │
│ 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False,                         │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                                   │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': True,           │
│ 'elevenlabs_voice_name': 'Domi', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew',                     │
│ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice':    │
│ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "F:\autovideototiktok\RedditVideoMakerBot\main.py", line 131, in <module>
    raise err
  File "F:\autovideototiktok\RedditVideoMakerBot\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "F:\autovideototiktok\RedditVideoMakerBot\main.py", line 68, in run_many
    main()
  File "F:\autovideototiktok\RedditVideoMakerBot\main.py", line 52, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "F:\autovideototiktok\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 258, in get_screenshots_of_reddit_posts
    page.locator(f"#t1_{comment['comment_id']}").screenshot(
  File "F:\autovideototiktok\RedditVideoMakerBot\venv\lib\site-packages\playwright\sync_api\_generated.py", line 16703, in screenshot
    self._sync(
  File "F:\autovideototiktok\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "F:\autovideototiktok\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 531, in screenshot
    return await self._with_element(
  File "F:\autovideototiktok\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "F:\autovideototiktok\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "F:\autovideototiktok\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "F:\autovideototiktok\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "F:\autovideototiktok\RedditVideoMakerBot\venv\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
Call log:
waiting for locator("#t1_lk64262")

**Comment by zizo-pro** [comment]
Same Error with me

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                               │
│ Version: 3.3.0                                                                                                                                                                                                 │
│ Error: Locator.screenshot: Timeout 30000ms exceeded.                                                                                                                                                           │
│ Call log:                                                                                                                                                                                                      │
│ waiting for locator("[data-test-id=\"post-content\"]")                                                                                                                                                         │
│                                                                                                                                                                                                                │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom':  │
│ 1.0, 'channel_name': 'Reddit Tales', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False,  │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': True,                  │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',            │
│ 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                                                                                                        │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "D:\Projects\RedditVideoMakerBot\main.py", line 131, in <module>
    raise err
  File "D:\Projects\RedditVideoMakerBot\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\Projects\RedditVideoMakerBot\main.py", line 68, in run_many
    main()
  File "D:\Projects\RedditVideoMakerBot\main.py", line 52, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "D:\Projects\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 203, in get_screenshots_of_reddit_posts
    raise e
  File "D:\Projects\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 185, in get_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path=postcontentpath)
  File "C:\Program Files\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 16703, in screenshot
    self._sync(
  File "C:\Program Files\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Program Files\Python310\lib\site-packages\playwright\_impl\_locator.py", line 531, in screenshot
    return await self._with_element(
  File "C:\Program Files\Python310\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Program Files\Python310\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Program Files\Python310\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Program Files\Python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\Python310\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-test-id=\"post-content\"]")

**Comment by Dofamen** [comment]
any solution for this issue?

**Comment by salih-g** [comment]
It's occur when story mode disabled

**Comment by VanshMarda** [comment]
> It's occur when story mode disabled

It still occurs when I enable it.
Should I change anything else in the config.toml?

**Comment by Roostydoo2** [comment]
It works for me when enabling story mode but for anyone where it still occurs afterwards here's my config.toml file so you can copy the settings

`[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
storymode = true
storymodemethod = 1
storymode_max_length = 1000
resolution_w = 1080
resolution_h = 1920
zoom = 1.0
channel_name = "Reddit Stories"

[settings.background]
background_video = "minecraft"
background_audio = "lofi"
background_audio_volume = 0.15
enable_extra_audio = false
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
voice_choice = "pyttsx"
random_voice = true
elevenlabs_voice_name = "Bella"
elevenlabs_api_key = ""
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = ""
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false

[reddit.creds]
client_id = ""
client_secret = ""
username = ""
password = ""
2fa = false

[reddit.thread]
random = true
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = "en-US"
min_comments = 20
`

**Comment by nssharmaofficial** [comment]
@SureelWillows @UsmanChatha @Roostydoo2 @salih-g @Gnlop @Dofamen @VanshMarda @zizo-pro Check [working recently updated repo](https://github.com/nssharmaofficial/reddit-hole).

**Comment by Dofamen** [comment]
Thank you, I'll test it and let you know if its works for me, once again thank you for your help

**Comment by tahatsahin** [comment]
hi [#2138](https://github.com/elebumm/RedditVideoMakerBot/pull/2138) fixes this.

**Comment by Mregy1** [comment]
> hi [#2138](https://github.com/elebumm/RedditVideoMakerBot/pull/2138) fixes this.

Actually, it doesn't. I tried it!
