### ISSUE TITLE
Received this Error:

### ISSUE THREAD

**Issue by orelmeister** [elebumm/RedditVideoMakerBot#213]
Traceback (most recent call last):
  File "\RedditVideoMakerBot\main.py", line 17, in <module>
    reddit_object = get_subreddit_threads()
  File "\RedditVideoMakerBot\reddit\subreddit.py", line 52, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "\Python\Python310\lib\site-packages\prawcore\sessions.py", line 266, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response

**Comment by FreebieII** [comment]
Are you using `Askreddit` as your subreddit, or are you using another subreddit, and if you are please let me know which!

**Comment by jayc331** [comment]
I've got the same error and I was using the AskReddit sub. I tried changing it but it didn't seem to make a difference. Could you confirm whether the SUBREDDIT option in the .env file is supposed to be a url or just r/AskReddit?

**Comment by jayc331** [comment]
Nevermind. Solved by changing to SUBREDDIT="AskReddit".

It shouldn't be r/ or a url for anyone else who might have this issue.

**Comment by FreebieII** [comment]
> Nevermind. Solved by changing to SUBREDDIT="AskReddit".
> 
> It shouldn't be r/ or a url for anyone else who might have this issue.

Great, we will note this issue as well.   Closing as **Solved**

Happy Coding 👋
