### ISSUE TITLE
[Bug]: Locator.screenshot: Timeout 30000ms exceeded.   

### ISSUE THREAD

**Issue by Martico2432** [elebumm/RedditVideoMakerBot#2161]
### Describe the bug

Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                  │
│ Version: 3.3.0                                                                                                                                    │
│ Error: Locator.screenshot: Timeout 30000ms exceeded.                                                                                              │
│ Call log:                                                                                                                                         │
│ waiting for locator("[data-test-id=\"post-content\"]")                                                                                            │
│                                                                                                                                                   │
│ Config: {'allow_nsfw': False, 'theme': 'light', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1,                      │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0, 'channel_name': 'Reddit Tales', 'background':              │
│ {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False,                       │
│ 'background_thumbnail': False, 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                                 │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'pyttsx', 'random_voice': True, 'elevenlabs_voice_name': 'Bella',      │
│ 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001',                 │
│ 'tiktok_sessionid': 'REDACTED', 'python_voice': '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}             

Traceback (most recent call last):
  File "d:\RedditVideoMakerBot\main.py", line 131, in <module>
    raise err
  File "d:\RedditVideoMakerBot\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "d:\RedditVideoMakerBot\main.py", line 68, in run_many
    main()
  File "d:\RedditVideoMakerBot\main.py", line 52, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "d:\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 203, in get_screenshots_of_reddit_posts
    raise e
  File "d:\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 185, in get_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path=postcontentpath)
  File "D:\RedditVideoMakerBot\.venv\lib\site-packages\playwright\sync_api\_generated.py", line 16703, in screenshot
    self._sync(
  File "D:\RedditVideoMakerBot\.venv\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "D:\RedditVideoMakerBot\.venv\lib\site-packages\playwright\_impl\_locator.py", line 531, in screenshot
    return await self._with_element(
  File "D:\RedditVideoMakerBot\.venv\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "D:\RedditVideoMakerBot\.venv\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "D:\RedditVideoMakerBot\.venv\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "D:\RedditVideoMakerBot\.venv\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "D:\RedditVideoMakerBot\.venv\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-test-id=\"post-content\"]")   

### Reproduction Steps

I just ran the program

### Expected behavior

Do what it is suposed

### System Information

Operating System : Windows 11
Python version : Python 3.10.11 .venv
App version / Branch : 3.3.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

**Comment by Teknoist** [comment]
same bug with python 3.10.7 /Windows 11

**Comment by perk34** [comment]
i am having the same problem

**Comment by MadsMMP** [comment]
Same problem here.

**Comment by Eruuac** [comment]
i also have the same problem

**Comment by emilienbev** [comment]
Same problem here on Ubuntu and Python 3.12.3

**Comment by Roostydoo2** [comment]
#2138 Fixes this (Only on the first run through though then reddits servers block you)

**Comment by Gaming8288383838** [comment]
issue is still not fixed

**Comment by Raffandrea** [comment]
issue still not fixed
