### ISSUE TITLE
[Bug]: You've been blocked by network security.

### ISSUE THREAD

**Issue by mjerk** [elebumm/RedditVideoMakerBot#2221]
### Describe the bug

When running the bot, Reddit blocks the browser with the following message:

"You've been blocked by network security. To continue, log in to your Reddit account or use your developer token. If you think you've been blocked by mistake, file a ticket below and we'll look into it."

This happens even though I have configured the bot with a valid Reddit developer token in the `config.toml` file.

### Reproduction Steps

1. Clone the repository and set up the bot as per the documentation.
2. Configure the `config.toml` file with valid Reddit credentials and a developer token.
3. Modify the `screenshot_downloader.py` file:
   - Change `headless=True` to `headless=False` to manually solve the CAPTCHA:
     ```python
     browser = p.chromium.launch(headless=False)
     ```
   - Add a delay to allow time for solving the CAPTCHA:
     ```python
     page.wait_for_timeout(15000)  # Wait for 15 seconds
     ```
4. Run the bot using the command: `python3 main.py`.
5. Observe the error message: "You've been blocked by network security."

### Expected behavior

The bot should log in to Reddit, fetch subreddit threads, and generate videos without encountering network security blocks or CAPTCHA issues.

### System Information

Operating System: Windows Server 2025 Datacenter (Google Cloud Platform)
Processor: AMD EPYC 7B12 @ 2.25 GHz
Installed RAM: 16 GB
Python Version: Python 3.10
App Version / Branch: latest, master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
       to join my Discord server or submit a GitHub issue. You can find solutions to many common problems in the
                               documentation: https://reddit-video-maker-bot.netlify.app/

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ You are using the newest version (3.3.0) of the bot                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
###############################
#                             #
# Checking TOML configuration #
#                             #
###############################
If you see any prompts, that means that you have unset/incorrectly set variables, please input the correct values.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ on the 1st iteration of 4                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Logging into Reddit.
Version 7.7.1 of praw is outdated. Version 7.8.1 was released Friday October 25, 2024.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Getting subreddit threads...                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Using subreddit: r/TwoSentenceHorror from TOML config
This post was pinned by moderators. Skipping...
This post was pinned by moderators. Skipping...
Video will be: Mommy said that she used a little bit of the sugar that she kept in her purse when the sweetness of the
coffee just wasn't doing it for her. 👍
Thread url is:
https://new.reddit.com//r/TwoSentenceHorror/comments/1hp4p6x/mommy_said_that_she_used_a_little_bit_of_the/ 👍
Thread has 652 upvotes
Thread has a upvote ratio of 98.0%
Thread has 32 comments
Received subreddit threads Successfully.
Thread ID is 1hp4p6x
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Saved Text to MP3 files successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Downloading screenshots of reddit posts...                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Launching Headless Browser...
Logging in to Reddit...
Skipping translation...
Something went wrong!
Something went wrong with making the screenshots! Do you want to skip the post? (y/n) y
The post is successfully skipped! You can now restart the program and this post will skipped.
Do you want the error traceback for debugging purposes? (y/n)y
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the        │
│ Discord community.                                                                                                   │
│ Version: 3.3.0                                                                                                       │
│ Error: Locator.screenshot: Timeout 30000ms exceeded.                                                                 │
│ Call log:                                                                                                            │
│ waiting for locator("[data-test-id=\"post-content\"]")                                                               │
│                                                                                                                      │
│ Config: {'allow_nsfw': False, 'theme': 'dark', 'times_to_run': 4, 'opacity': 0.9, 'storymode': True,                 │
│ 'storymodemethod': 0, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920, 'zoom': 1.0,         │
│ 'channel_name': '2Sentences', 'background': {'background_video': 'minecraft', 'background_audio': 'lofi',            │
│ 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': True,                          │
│ 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96,                                   │
│ 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice': True,  │
│ 'elevenlabs_voice_name': 'Josh', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew',                     │
│ 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice':    │
│ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\Users\dlup\RedditVideoMakerBot\main.py", line 131, in <module>
    raise err
  File "C:\Users\dlup\RedditVideoMakerBot\main.py", line 113, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\dlup\RedditVideoMakerBot\main.py", line 68, in run_many
    main()
  File "C:\Users\dlup\RedditVideoMakerBot\main.py", line 52, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\dlup\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 203, in get_screenshots_of_reddit_posts
    raise e
  File "C:\Users\dlup\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 185, in get_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(path=postcontentpath)
  File "C:\Users\dlup\redbot\lib\site-packages\playwright\sync_api\_generated.py", line 16703, in screenshot
    self._sync(
  File "C:\Users\dlup\redbot\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\dlup\redbot\lib\site-packages\playwright\_impl\_locator.py", line 531, in screenshot
    return await self._with_element(
  File "C:\Users\dlup\redbot\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\dlup\redbot\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\dlup\redbot\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\dlup\redbot\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\dlup\redbot\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.screenshot: Timeout 30000ms exceeded.
Call log:
waiting for locator("[data-test-id=\"post-content\"]")

**Comment by JasonLovesDoggo** [comment]
try using a commercial IP VPN. or proxy your connection to a different device.
