### ISSUE TITLE
DownloadError when Merging formats into mp4

### ISSUE THREAD

**Issue by MonkaMaczna** [elebumm/RedditVideoMakerBot#254]
```
[download] Destination: assets/mp4/background.f308.webm
[download] 100% of 5.84GiB in 03:41
[download] Destination: assets/mp4/background.f251.webm
[download] 100% of 80.34MiB in 00:02
[Merger] Merging formats into "assets/mp4/background.mp4"
ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3204, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3374, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3361, in run_all_pps
    info = self.run_pp(pp, info)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3340, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 827, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 282, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 321, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 24, in <module>
    download_background()
  File "/home/monka/RedditVideoMakerBot/video_creation/background.py", line 35, in download_background
    ydl.download("https://www.youtube.com/watch?v=n_Dv4JMiwK8")
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3254, in download
    self.__download_wrapper(self.extract_info)(
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3230, in wrapper
    res = func(*args, **kwargs)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1479, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1535, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2640, in process_video_result
    self.process_info(new_info)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3206, in process_info
    self.report_error('Postprocessing: %s' % str(err))
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/monka/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
```

**Comment by MonkaMaczna** [comment]
I can't find a fix for it at the moment, but I found a workaround. 

There's problem with downloading the video and merging it, so I downloaded it manually with yt_dlp using command `yt-dlp https://www.youtube.com/watch?v=n_Dv4JMiwK8 -S res,ext:mp4:m4a --recode mp4` renamed it to `background.mp4` and moved it to `assets/mp4/`.
