### ISSUE TITLE
Mac Os not running the file

### ISSUE THREAD

**Issue by PGC-Talha** [elebumm/RedditVideoMakerBot#268]
File "/Users/my name/Desktop/school stuff/RedditVideoMakerBot-master/main.py", line 19, in <module>
    reddit_object = get_subreddit_threads()
  File "/Users/my name/Desktop/school stuff/RedditVideoMakerBot-master/reddit/subreddit.py", line 18, in get_subreddit_threads
    if os.getenv("REDDIT_2FA").lower() == "yes":
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by CallumIO** [comment]
Is your environment file definitely .env?
In that directory run the command `ls -la` and paste the output here please.

**Comment by PGC-Talha** [comment]
nadeemiqbal@192 RedditVideoMakerBot-master % ls -la
total 72
drwxrwxr-x@ 15 nadeemiqbal  staff   480 Jun  4 15:00 .
drwxr-xr-x@ 23 nadeemiqbal  staff   736 Jun  3 22:04 ..
-rw-rw-r--@  1 nadeemiqbal  staff    10 Jun  3 20:25 .dockerignore
-rw-rw-r--@  1 nadeemiqbal  staff   273 Jun  4 15:00 .env.template
-rw-rw-r--@  1 nadeemiqbal  staff    64 Jun  3 20:25 .gitignore
-rw-rw-r--@  1 nadeemiqbal  staff   476 Jun  3 20:25 Dockerfile
-rw-rw-r--@  1 nadeemiqbal  staff  2823 Jun  3 20:25 README.md
-rwxr-xr-x@  1 nadeemiqbal  staff    22 Jun  3 20:25 build.sh
drwxrwxr-x@  4 nadeemiqbal  staff   128 Jun  3 20:25 examples
-rw-rw-r--@  1 nadeemiqbal  staff   978 Jun  3 20:25 main.py
drwxrwxr-x@  4 nadeemiqbal  staff   128 Jun  3 21:04 reddit
-rw-rw-r--@  1 nadeemiqbal  staff   127 Jun  3 20:25 requirements.txt
-rwxr-xr-x@  1 nadeemiqbal  staff    71 Jun  3 20:25 run.sh
drwxrwxr-x@  4 nadeemiqbal  staff   128 Jun  3 21:04 utils
drwxrwxr-x@  8 nadeemiqbal  staff   256 Jun  3 21:04 video_creation

**Comment by CallumIO** [comment]
Type `cp .env.template .env` and try running it again

You didn't rename the .env.template file

**Comment by PGC-Talha** [comment]
It has given me an entirely new error

 File "/Users/nadeemiqbal/Desktop/school stuff/RedditVideoMakerBot-master/main.py", line 19, in <module>
    reddit_object = get_subreddit_threads()
  File "/Users/nadeemiqbal/Desktop/school stuff/RedditVideoMakerBot-master/reddit/subreddit.py", line 52, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "/usr/local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/usr/local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/usr/local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/praw/reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/usr/local/lib/python3.9/site-packages/praw/reddit.py", line 739, in _objectify_request
    self.request(
  File "/usr/local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/usr/local/lib/python3.9/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/usr/local/lib/python3.9/site-packages/prawcore/sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/prawcore/sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "/usr/local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "/usr/local/lib/python3.9/site-packages/prawcore/sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "/usr/local/lib/python3.9/site-packages/prawcore/auth.py", line 425, in refresh
    self._request_token(
  File "/usr/local/lib/python3.9/site-packages/prawcore/auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by CallumIO** [comment]
Your Reddit tokens are not set correctly

**Comment by PGC-Talha** [comment]
I fixed my Reddit Tokens and it gives me another error


Getting AskReddit threads...                                                                                                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/nadeemiqbal/Desktop/school stuff/RedditVideoMakerBot-master/main.py", line 19, in <module>
    reddit_object = get_subreddit_threads()
  File "/Users/nadeemiqbal/Desktop/school stuff/RedditVideoMakerBot-master/reddit/subreddit.py", line 52, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "/usr/local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/usr/local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/usr/local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/praw/reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/usr/local/lib/python3.9/site-packages/praw/reddit.py", line 739, in _objectify_request
    self.request(
  File "/usr/local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/usr/local/lib/python3.9/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/usr/local/lib/python3.9/site-packages/prawcore/sessions.py", line 266, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.BadRequest: received 400 HTTP response

**Comment by CallumIO** [comment]
What did you set subreddit to in your .env file?

**Comment by PGC-Talha** [comment]
r/AskReddit

**Comment by CallumIO** [comment]
Change it to just 'askreddit'

**Comment by PGC-Talha** [comment]
I did that and it created the mp3 text to speech audios but it still gave errors and didnt make the mp4



nadeemiqbal@192 RedditVideoMakerBot-master % python3 main.py
                                                                                
                                                                                
     Thanks for using this tool! Feel free to contribute to this project on     
   GitHub! If you have any questions, feel free to reach out to me on Twitter   
                           or submit a GitHub issue.                            
                                                                                
                                                                                
╭──────────────────────────────────────────────────────────────────────────────╮
│ Getting AskReddit threads...                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
Video will be: what subreddit isn't what it sounds like? 👍
Received AskReddit threads successfully.
╭──────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4 it/s  
Saved Text to MP3 files successfully.
╭──────────────────────────────────────────────────────────────────────────────╮
│ Downloading Screenshots of Reddit Posts 📷                                   │
╰──────────────────────────────────────────────────────────────────────────────╯
Launching Headless Browser...
Traceback (most recent call last):
  File "/Users/nadeemiqbal/Desktop/school stuff/RedditVideoMakerBot-master/main.py", line 23, in <module>
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments, os.getenv("THEME"))
  File "/Users/nadeemiqbal/Desktop/school stuff/RedditVideoMakerBot-master/video_creation/screenshot_downloader.py", line 33, in download_screenshots_of_reddit_posts
    page.goto(reddit_object["thread_url"])
  File "/usr/local/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 7413, in goto
    self._sync(
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 88, in _sync
    return task.result()
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.reddit.com/r/AskReddit/comments/v4m0a0/what_subreddit_isnt_what_it_sounds_like/", waiting until "load"
============================================================
