### ISSUE TITLE
No such file or directory edge case

### ISSUE THREAD

**Issue by arjun-dureja** [elebumm/RedditVideoMakerBot#294]
Just came across the following error:

```
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    final_video = make_final_video(number_of_comments)
  File "/Users/arjundureja/RedditVideoMakerBot/video_creation/final_video.py", line 70, in make_final_video
    final.write_videofile(filename, fps=30, audio_codec="aac", audio_bitrate="192k")
  File "<decorator-gen-55>", line 2, in write_videofile
  File "/Users/arjundureja/.pyenv/versions/3.7.8/lib/python3.7/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "/Users/arjundureja/.pyenv/versions/3.7.8/lib/python3.7/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "/Users/arjundureja/.pyenv/versions/3.7.8/lib/python3.7/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/Users/arjundureja/.pyenv/versions/3.7.8/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 307, in write_videofile
    logger=logger)
  File "/Users/arjundureja/.pyenv/versions/3.7.8/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 228, in ffmpeg_write_video
    writer.write_frame(frame)
  File "/Users/arjundureja/.pyenv/versions/3.7.8/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file assets/What do bullies think/feel when they watch a scene (that is supposed to induce empathy) where someone is being bullied in a show or movie.mp4:

 b'assets/What do bullies think/feel when they watch a scene (that is supposed to induce empathy) where someone is being bullied in a show or movie.mp4: No such file or directory\n'
```

I believe it's due to a forward slash (/) being present in the name of the question. We'll need to exclude any slashes and characters that are not allowed in file names in respective operating systems. It's also not great having files with extremely long names, I suggest leaving it as something shorter.

**Comment by JasonLovesDoggo** [comment]
Length fix:
https://github.com/JasonLovesDoggo/RedditVideoMakerBot/blob/master/video_creation/final_video.py#L45-L48
