### ISSUE TITLE
Error module not found

### ISSUE THREAD

**Issue by j0p3s** [elebumm/RedditVideoMakerBot#295]
C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0>python3 main.py
Traceback (most recent call last):
  File "C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0\main.py", line 1, in <module>
    from utils.console import print_markdown
  File "C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0\utils\console.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0>

**Comment by j0p3s** [comment]
Running on windows 10

**Comment by j0p3s** [comment]
C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0>pip3 install rich
Requirement already satisfied: rich in c:\users\joao\appdata\local\programs\python\python310\lib\site-packages (12.4.4)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\joao\appdata\local\programs\python\python310\lib\site-packages (from rich) (2.12.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\joao\appdata\local\programs\python\python310\lib\site-packages (from rich) (0.9.1)

And still the same issue

**Comment by j0p3s** [comment]
Closing command line and opening it i get a module not found for dotenv but when i try to install it i get this:
`C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0>pip install dotenv
Collecting dotenv
  Downloading dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error

        python setup.py egg_info did not run successfully.
        exit code: 1

        [16 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 14, in <module>
          File "C:\Users\Joao\AppData\Local\Temp\pip-wheel-z6jag1mz\distribute_42b73d2e30d94486b12e7dcb5aace791\setuptools\__init__.py", line 2, in <module>
            from setuptools.extension import Extension, Library
          File "C:\Users\Joao\AppData\Local\Temp\pip-wheel-z6jag1mz\distribute_42b73d2e30d94486b12e7dcb5aace791\setuptools\extension.py", line 5, in <module>
            from setuptools.dist import _get_unpatched
          File "C:\Users\Joao\AppData\Local\Temp\pip-wheel-z6jag1mz\distribute_42b73d2e30d94486b12e7dcb5aace791\setuptools\dist.py", line 7, in <module>
            from setuptools.command.install import install
          File "C:\Users\Joao\AppData\Local\Temp\pip-wheel-z6jag1mz\distribute_42b73d2e30d94486b12e7dcb5aace791\setuptools\command\__init__.py", line 8, in <module>
            from setuptools.command import install_scripts
          File "C:\Users\Joao\AppData\Local\Temp\pip-wheel-z6jag1mz\distribute_42b73d2e30d94486b12e7dcb5aace791\setuptools\command\install_scripts.py", line 3, in <module>
            from pkg_resources import Distribution, PathMetadata, ensure_directory
          File "C:\Users\Joao\AppData\Local\Temp\pip-wheel-z6jag1mz\distribute_42b73d2e30d94486b12e7dcb5aace791\pkg_resources.py", line 1518, in <module>
            register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
        AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\Joao\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Joao\\AppData\\Local\\Temp\\tmpbvjtn6ll', '--quiet', 'distribute']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Joao\AppData\Local\Temp\pip-install-awdtihwi\dotenv_be0f0e51213a4f29bdd792902a759531\setup.py", line 13, in <module>
          setup(name='dotenv',
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 806, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
          return installer(requirement)
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['C:\\Users\\Joao\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Joao\\AppData\\Local\\Temp\\tmpbvjtn6ll', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0>`

**Comment by j0p3s** [comment]
Ok so i installed all missing modules but running main.py i still get errors:

Traceback (most recent call last):
  File "C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0\main.py", line 38, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0\reddit\subreddit.py", line 49, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0>

**Comment by MonkaMaczna** [comment]
> Ok so i installed all missing modules but running main.py i still get errors:
> 
> Traceback (most recent call last): File "C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0\main.py", line 38, in reddit_object = get_subreddit_threads() File "C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0\reddit\subreddit.py", line 49, in get_subreddit_threads submission = list(threads)[random.randrange(0, 25)] File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in **next** self._next_batch() File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch self._listing = self._reddit.get(self.url, params=self.params) File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped return func(**dict(zip(_old_args, args)), **kwargs) File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get return self._objectify_request(method="GET", params=params, path=path) File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request self.request( File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped return func(**dict(zip(_old_args, args)), **kwargs) File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request return self._core.request( File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request return self._request_with_retries( File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries response, saved_exception = self._make_request( File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request response = self._rate_limiter.call( File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call kwargs["headers"] = set_header_callback() File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback self._authorizer.refresh() File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 425, in refresh self._request_token( File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token response = self._authenticator._post(url, **data) File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 38, in _post raise ResponseException(response) prawcore.exceptions.ResponseException: received 401 HTTP response
> 
> C:\Users\Joao\Desktop\RedditVideoMakerBot-1.0.0>

Oh, it was mentioned previously mentioned in a few issues like #83 #255 . There's a problem with stuff you put in .env file or you didn't choose "script" option in the Reddit developer application creation step.

**Comment by j0p3s** [comment]
I did choose script in the developer options on reddit.
I did fill up the info according the readme on gitbub

**Comment by j0p3s** [comment]
What I think can be interfering, can be either: the password that has special characters on reddit or the 2fa step

**Comment by JasonLovesDoggo** [comment]
Solved in newer versions If you still have this issue reopen
