### ISSUE TITLE
help

### ISSUE THREAD

**Issue by riveX7** [elebumm/RedditVideoMakerBot#298]
Traceback (most recent call last):
  File "C:\Users\migue\Desktop\RedditVideoMakerBot-master\main.py", line 38, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\migue\Desktop\RedditVideoMakerBot-master\reddit\subreddit.py", line 49, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\migue\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by RenkeDhr** [comment]
Instead of `python3 main.py` type `python main.py` hope this helps. It helped my when I had this problem.

**Comment by iaacornus** [comment]
> Instead of `python3 main.py` type `python main.py` hope this helps. It helped my when I had this problem.

`python3` and `python` is the same, it is just different package naming, `OAuthException` occurs due to wrong env variables.

**Comment by CallumIO** [comment]
Closing due to being stale
