### ISSUE TITLE
script crashes when getting the screenshots

### ISSUE THREAD

**Issue by nono17k** [elebumm/RedditVideoMakerBot#3]
realy didn't know what happened just used it and then boom just crashed , can't realy get it bc i have 0 experiance ith headless browser

```
Launching Headless Browser...
Traceback (most recent call last):
  File "C:\Users\Megaport\Desktop\RedditVideoMakerBot-master\main.py", line 19, in <module>
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\Megaport\Desktop\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 22, in download_screenshots_of_reddit_posts
    browser = p.chromium.launch()
  File "C:\Users\Megaport\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\sync_api\_generated.py", line 11538, in launch
    self._sync(
  File "C:\Users\Megaport\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\Megaport\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\Megaport\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\Megaport\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Megaport\AppData\Local\ms-playwright\chromium-1005\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

```

**Comment by nonowastaken** [comment]
thanks , you should realy make a option to make multiple videos / choose the output file name  (i might maybe do it myself)
