### ISSUE TITLE
Error yt_dlp post processing

### ISSUE THREAD

**Issue by mdalsi** [elebumm/RedditVideoMakerBot#304]
`ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3204, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3374, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3361, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3340, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 827, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 282, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 321, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)`

Trying to run using run.sh to solve other issues with python but it's not working at all

**Comment by MonkaMaczna** [comment]
Oh yeah, I had the same error before when downloading Minecraft background video. I, unfortunately, couldn't find an exact fix, but I went around it by downloading manually Minecraft background using command.

Command is in #254

**Comment by CallumIO** [comment]
Closing due to being stale and no longer relevant

**Comment by BSarmady** [comment]
Why no longer relevant? Latest release throwing this same error on some videos. here is an example

youtube-dl -f 397+140 -o 1.mp4 https://www.youtube.com/watch?v=nUfvSczd6T8

even without specifying the output and selecting stream still throws same error when merging streams

**Comment by megahypercat** [comment]
My ffmpeg is a bit old, true, but this is because the newer versions has bugs(Well presumably) that gives bad output. Over all, the older version(s) have worked much better for me.
So this is very unfortunate.
