### ISSUE TITLE
No moduel named 'rich'

### ISSUE THREAD

**Issue by luis02020202** [elebumm/RedditVideoMakerBot#32]
"C:\Users\user\Desktop\RedditVideoMakerBot-master> python3 main.py
Traceback (most recent call last):
  File "C:\Users\user\Desktop\RedditVideoMakerBot-master\main.py", line 1, in <module>
    from utils.console import print_markdown
  File "C:\Users\user\Desktop\RedditVideoMakerBot-master\utils\console.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich' "

**this is the cmd output after executing "python3  main.py"**

**Comment by FreebieII** [comment]
Try this in your console `pip3 install rich`

**Comment by FreebieII** [comment]
If this doesn't work, refer to #29

**Comment by cryocet** [comment]
> 

i tried that and it says i already have it
