### ISSUE TITLE
TypeError: attrib() got an unexpected keyword argument 'eq'

### ISSUE THREAD

**Issue by PrintedScript** [elebumm/RedditVideoMakerBot#337]
When I executed `python main.py`

```
C:\Users\User\Documents\RedditVideoMakerBot>python main.py
Traceback (most recent call last):
  File "C:\Users\User\Documents\RedditVideoMakerBot\main.py", line 10, in <module>
    from video_creation.screenshot_downloader import download_screenshots_of_reddit_posts
  File "C:\Users\User\Documents\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 1, in <module>
    from playwright.sync_api import sync_playwright, ViewportSize
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\sync_api\__init__.py", line 25, in <module>
    import playwright.sync_api._generated
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\sync_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_connection.py", line 22, in <module>
    from pyee import AsyncIOEventEmitter, EventEmitter
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pyee\__init__.py", line 71, in <module>
    from pyee._trio import TrioEventEmitter  # noqa
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\pyee\_trio.py", line 4, in <module>
    import trio
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trio\__init__.py", line 18, in <module>
    from ._core import (
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trio\_core\__init__.py", line 29, in <module>
    from ._run import (
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\trio\_core\_run.py", line 28, in <module>
    from outcome import Error, Outcome, Value, capture
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\outcome\__init__.py", line 3, in <module>
    from ._impl import Error, Outcome, Value, acapture, capture
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\outcome\_impl.py", line 39, in <module>
    class Outcome(abc.ABC):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\outcome\_impl.py", line 54, in Outcome
    _unwrapped = attr.ib(default=False, eq=False, init=False)
TypeError: attrib() got an unexpected keyword argument 'eq'
```
I get the error message 
```
TypeError: attrib() got an unexpected keyword argument 'eq'
```
I had followed the documentation maybe it has to do something with my python installation? I am not really sure

**Comment by CallumIO** [comment]
`pip install attrs`

Pretty sure your attrs library is out of date
