### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by FreebieII** [elebumm/RedditVideoMakerBot#34]
`playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.`
`=========================== logs ===========================`
`waiting for selector "[data-test-id="post-content"]"`
`============================================================`

Any ideas why I might be getting a timeout error?

**Comment by FreebieII** [comment]
Solved! 

Added `, timeout = 0` to **disable** the timeout completely.

If you get the same error, add it to **Line 26** in  **.\video_creation\screenshot_downloader.py**

`page.goto(reddit_object["thread_url"], timeout = 0)`

**Comment by reinkdesigns** [comment]
i added timeout to line 26 and its still timing out

**Comment by FreebieII** [comment]
> It also is still timing out for me as well despite the change.


At which stage of the script does it time out?

**Comment by reinkdesigns** [comment]
![image](https://user-images.githubusercontent.com/104669790/171794577-60648eb4-b170-4794-a7df-d8141cbee90a.png)

if that helps

**Comment by FireHe4d** [comment]
@FreebieII in my case 
![image](https://user-images.githubusercontent.com/54643109/172072617-08cd5ed9-e0f1-438c-a0a1-00f6ab142114.png)

**Comment by ajprabhu09** [comment]
Is there any update to this ? I'm still getting

`Launching Headless Browser...
Traceback (most recent call last):
  File "/home/ajprabhu/Documents/RedditVideoMakerBot/main.py", line 95, in <module>
    download_screenshots_of_reddit_posts(
  File "/home/ajprabhu/Documents/RedditVideoMakerBot/video_creation/screenshot_downloader.py", line 41, in download_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(
  File "/home/ajprabhu/.local/share/virtualenvs/RedditVideoMakerBot-5bpedBX8/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13249, in screenshot
    self._sync(
  File "/home/ajprabhu/.local/share/virtualenvs/RedditVideoMakerBot-5bpedBX8/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 88, in _sync
    return task.result()
  File "/home/ajprabhu/.local/share/virtualenvs/RedditVideoMakerBot-5bpedBX8/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 394, in screenshot
    return await self._with_element(
  File "/home/ajprabhu/.local/share/virtualenvs/RedditVideoMakerBot-5bpedBX8/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "/home/ajprabhu/.local/share/virtualenvs/RedditVideoMakerBot-5bpedBX8/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 219, in element_handle
    handle = await self._frame.wait_for_selector(
  File "/home/ajprabhu/.local/share/virtualenvs/RedditVideoMakerBot-5bpedBX8/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 293, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/home/ajprabhu/.local/share/virtualenvs/RedditVideoMakerBot-5bpedBX8/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/ajprabhu/.local/share/virtualenvs/RedditVideoMakerBot-5bpedBX8/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"
============================================================
`

**Comment by susgsus** [comment]
> page.goto(reddit_object["thread_url"], timeout = 0)

this didnt fix the problem

**Comment by ajprabhu09** [comment]
So apparently it got solved after I set it to light mode

**Comment by DylanDelobel** [comment]
Same issue
