### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by Haterxpro** [elebumm/RedditVideoMakerBot#353]
File "C:\Users\jakub\Desktop\RedditVideoMakerBot-1.1\main.py", line 93, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\jakub\Desktop\RedditVideoMakerBot-1.1\reddit\subreddit.py", line 58, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

>> Any solutions??

**Comment by Tudorhc5** [comment]
I think you probably entered some data wrong in the .env file (the settings file), or you have some missing dependencies.

**Comment by j0p3s** [comment]
I was able to create one video and .env is created sucessfully (the video was created and uploaded already to tiktok).

But this issue came along after running the script a second time too so dependencies and .env is not the issue since i have it too

**Comment by j0p3s** [comment]
Traceback (most recent call last):
  File "C:\RedditVideoMakerBot-1.1\main.py", line 93, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\RedditVideoMakerBot-1.1\reddit\subreddit.py", line 60, in get_subreddit_threads
    print_substep(f"Video will be: {submission.title} :thumbsup:")
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\reddit\base.py", line 34, in __getattr__
    self._fetch()
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\reddit\submission.py", line 632, in _fetch
    data = self._fetch_data()
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\reddit\submission.py", line 629, in _fetch_data
    return self._reddit.request(method="GET", params=params, path=path)
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 253, in _request_with_retries
    return self._do_retry(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 162, in _do_retry
    return self._request_with_retries(
  File "C:\Users\Joao\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 266, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 504 HTTP response

**Comment by Haterxpro** [comment]
> I think you probably entered some data wrong in the .env file (the settings file), or you have some missing dependencies.

nah, I already take a look at my .env file and everything seems fine, tbh idk where's the problem

**Comment by Haterxpro** [comment]
Okay, solved. In .env file was really problem. ,,REDDIT_CLIENT_ID" have to be YOUR ID, not USERNAME 
>It's under your ,,script name" and "personal use script". It's next to the logo.
