### ISSUE TITLE
something dont work?

### ISSUE THREAD

**Issue by everythxxgs** [elebumm/RedditVideoMakerBot#361]
What can i do?
````  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
                                to reach out to me on Twitter or submit a GitHub issue.


[14:16:54] Checking environment variables...                                                                  main.py:48
[14:16:55] Enviroment Variables are set! Continuing...                                                        main.py:90
Traceback (most recent call last):
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\1122\Downloads\RedditVideoMakerBot-master\main.py", line 93, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\1122\Downloads\RedditVideoMakerBot-master\reddit\subreddit.py", line 58, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\1122\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request
PS C:\Users\1122\Downloads\RedditVideoMakerBot-master>`
````

**Comment by FreebieII** [comment]
Please double check your Reddit Username and Password, as well as the client_id and and client_secret

**Comment by FreebieII** [comment]
> 

That all details are correctly recorded in the `.env` file

**Comment by everythxxgs** [comment]
thanks
