### ISSUE TITLE
'charmap' codec can't encode character '\U0001f60a' in position 1: character maps to <undefined>

### ISSUE THREAD

**Issue by 2vsh** [elebumm/RedditVideoMakerBot#37]
I followed the steps in installation process, but i get this:

$ python3 main.py

   Thanks for using this tool!Traceback (most recent call last):
  File "C:\Users\jacer\Desktop\WORKTHISTIMEPLACE\RedditVideoMakerBot\main.py", line 9, in <module>
    print_markdown(
  File "C:\Users\jacer\Desktop\WORKTHISTIMEPLACE\RedditVideoMakerBot\utils\console.py", line 14, in print_markdown
    console.print(md)
  File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 1635, in print
    with self:
  File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 838, in __exit__
    self._exit_buffer()
  File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 796, in _exit_buffer
    self._check_buffer()
  File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 1988, in _check_buffer
    legacy_windows_render(
  File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\_win32_console.py", line 418, in write_styled
    self.write_text(text)
  File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\_win32_console.py", line 379, in write_text
    self.write(text)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60a' in position 1: character maps to <undefined>

any ideas?

**Comment by baggot4** [comment]
> I followed the steps in installation process, but i get this:
> 
> $ python3 main.py
> 
> Thanks for using this tool!Traceback (most recent call last): File "C:\Users\jacer\Desktop\WORKTHISTIMEPLACE\RedditVideoMakerBot\main.py", line 9, in print_markdown( File "C:\Users\jacer\Desktop\WORKTHISTIMEPLACE\RedditVideoMakerBot\utils\console.py", line 14, in print_markdown console.print(md) File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 1635, in print with self: File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 838, in **exit** self._exit_buffer() File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 796, in _exit_buffer self._check_buffer() File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 1988, in _check_buffer legacy_windows_render( File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich_windows_renderer.py", line 17, in legacy_windows_render term.write_styled(text, style) File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich_win32_console.py", line 418, in write_styled self.write_text(text) File "C:\Users\jacer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich_win32_console.py", line 379, in write_text self.write(text) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0] UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60a' in position 1: character maps to
> 
> any ideas?

what I did was go through the code and in 2 places there were emojis, I just deleted them.

**Comment by CallumIO** [comment]
Closed as emoji's have been removed
