### ISSUE TITLE
program dont work win 11 8gb ram i5-9400f 240gb m2 ssd gt 710

### ISSUE THREAD

**Issue by chico-525** [elebumm/RedditVideoMakerBot#372]
I do the things said on the document and my program puts this error
Traceback (most recent call last):
  File "C:\Users\ASUS\OneDrive\Ambiente de Trabalho\RedditVideoMakerBot-master\main.py", line 32, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\ASUS\OneDrive\Ambiente de Trabalho\RedditVideoMakerBot-master\reddit\subreddit.py", line 50, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\ASUS\AppData\Roaming\Python\Python310\site-packages\prawcore\auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by djjhani** [comment]
Hello @noblesaji. I also have the problem and have tried logging in manually, afterwards. And I cant. How long does one have to wait to try again?

**Comment by JasonLovesDoggo** [comment]
Exactly what noblesaji said.
Closed for inactivity
Please reopen if you still have a problem
