### ISSUE TITLE
FileNotFoundError: [WinError 2] Can't find the specified file: 'assets'

### ISSUE THREAD

**Issue by duckGameGH** [elebumm/RedditVideoMakerBot#375]
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\hugoa\Documents\RedditVideoMakerBot-master\video_creation\voices.py", line 18, in save_text_to_mp3
    Path("assets/mp3").mkdir(parents=True, exist_ok=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1277, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1278, in mkdir
    self.mkdir(mode, parents=False, exist_ok=exist_ok)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1273, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 2] Can't find the specified file: 'assets'

**Comment by matrix2113** [comment]
Do you have an assets folder? If you do, is there anything inside it?

**Comment by duckGameGH** [comment]
Oh yes thank you, i did not have an assets folder...
