### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by BasicCorruption** [elebumm/RedditVideoMakerBot#377]
I tried to run `python3 main.py` but got an error

```
C:\Users\saytl\Desktop\RedditVideoMakerBot-master>python main.py


  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
                                to reach out to me on Twitter or submit a GitHub issue.


[15:47:38] Checking environment variables...                                                                 main.py:48
[15:47:39] Enviroment Variables are set! Continuing...                                                       main.py:90
Traceback (most recent call last):
  File "C:\Users\saytl\Desktop\RedditVideoMakerBot-master\main.py", line 93, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\saytl\Desktop\RedditVideoMakerBot-master\reddit\subreddit.py", line 58, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\saytl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prawcore\auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request
```

I am using python 3.10.5 and windows 10.0.19044.1706
I made sure that my application is a script and I put in the right info in the .env file. But I have signed up for reddit with my google account and I dont know if that is an issue.

**Comment by noblesaji** [comment]
Hi @BasicCorruption . Please refer to #372 .Thanks

**Comment by OGreeni** [comment]
I was facing the same issue. Go back to your .env file and ensure that all the provided info is correct.

**Comment by CallumIO** [comment]
Closing due to being stale, try again in latest version
