### ISSUE TITLE
error in main.py

### ISSUE THREAD

**Issue by alexgarciiaa** [elebumm/RedditVideoMakerBot#384]
Traceback (most recent call last):
  File "/home/alexgarcia/RedditVideoMakerBot/main.py", line 8, in <module>
    from video_creation.background import download_background, chop_background_video
  File "/home/alexgarcia/RedditVideoMakerBot/video_creation/background.py", line 3, in <module>
    from yt_dlp import YoutubeDL
ModuleNotFoundError: No module named 'yt_dlp'

**Comment by emil314** [comment]
Have you done `pip3 install -r requirements.txt`? If yes, try directly installing the yt_dlp package by doing `pip3 install yt_dlp`.
