### ISSUE TITLE
Runtime error in main.py

### ISSUE THREAD

**Issue by BradTFT** [elebumm/RedditVideoMakerBot#386]
Hi,

I followed all setup instructions and ran 'python3 main.py` and got this error:

```
Traceback (most recent call last):
  File "/home/BradTFT/fork/RedditVideoMakerBot/main.py", line 4, in <module>
    from video_creation.background import download_background, chop_background_video
  File "/home/BradTFT/fork/RedditVideoMakerBot/video_creation/background.py", line 4, in <module>
    from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_tools.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
```

only error i could have made was inside of the env file.

just to make sure, the client id is covered in green and black in the below picture, correct?. In the env folder i put MY reddit login information. is this correct?

![Screenshot 2022-06-08 11 18 16 AM](https://user-images.githubusercontent.com/50968931/172654634-51943cb4-2952-48c8-9608-d5c8f293eaa2.png)

**Comment by micziz** [comment]
The error says it all. You do not have FFMPeg installed in your system. Download it [here](https://ffmpeg.org)

**Comment by BradTFT** [comment]
worked thanks
