### ISSUE TITLE
Headless Browser not working??

### ISSUE THREAD

**Issue by JuniorWolfgamingDE** [elebumm/RedditVideoMakerBot#426]
Hey, I ran into an issue where the browser isn't working anymore I guess?

`Launching Headless Browser...
Traceback (most recent call last):
  File "E:\RedditVideoMakerBot\code\main.py", line 95, in <module>
    download_screenshots_of_reddit_posts(
  File "E:\RedditVideoMakerBot\code\video_creation\screenshot_downloader.py", line 41, in download_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 13249, in screenshot
    self._sync(
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 394, in screenshot
    return await self._with_element(
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 219, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 293, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"
============================================================`

**Comment by DylanDelobel** [comment]
Duplicate of #34

**Comment by Norbertschaefer** [comment]
add this in your screenshot_downloader.py

`        if "reddit.com" in page.url:
            page.locator('[data-test-id="post-content"]').screenshot(
                path="./assets/png/title.png"
            )
        else:
            img_data = requests.get(page.url).content
            with open('./assets/png/title.png', 'wb') as handler:
                handler.write(img_data)
`

**Comment by hamzah-sajid-code** [comment]
> add this in your screenshot_downloader.py
> 
> ` if "reddit.com" in page.url: page.locator('[data-test-id="post-content"]').screenshot( path="./assets/png/title.png" ) else: img_data = requests.get(page.url).content with open('./assets/png/title.png', 'wb') as handler: handler.write(img_data)`

Where shall i add this

**Comment by Norbertschaefer** [comment]
screenshot_downloader.py in the \video_creation dir replace line 48-50 with it 
```
        page.locator('[data-test-id="post-content"]').screenshot(
            path="assets/temp/png/title.png"
        )
```

`if "reddit.com" in page.url: page.locator('[data-test-id="post-content"]').screenshot( path="./assets/png/title.png" ) else: img_data = requests.get(page.url).content with open('./assets/png/title.png', 'wb') as handler: handler.write(img_data)`

**Comment by luisadrianpuga** [comment]
this worked for me, thank you!

**Comment by hakupila** [comment]
I have this issuse right now and im not sure where to put the solution code in, because I think after the updates the lines kinda moved to and I can't find the right spot to replace it

**Comment by FQQD** [comment]
I also just had this Problem. I inserted the text here:
![image](https://user-images.githubusercontent.com/96952506/176193109-147f15b3-547b-450a-98ba-0004d117bb49.png)
but that didn't stop it.

**Comment by yrncollo** [comment]
I am having the same error
