### ISSUE TITLE
401 HTTP response

### ISSUE THREAD

**Issue by newbieverse** [elebumm/RedditVideoMakerBot#443]
Traceback (most recent call last):
  File "C:\Users\Noman\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 93, in <module>
    reddit_object = get_subreddit_threads()
  File "C:\Users\Noman\Desktop\RedditVideoMakerBot-master\RedditVideoMakerBot-master\reddit\subreddit.py", line 58, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\Noman\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

**Comment by evfus** [comment]
In the .env you probably put at reddit client id the name of the app instead of the id. This is the ID.
![image](https://user-images.githubusercontent.com/80192555/173189198-e1811fd0-95e3-4541-9fcb-068187e0054a.png)
Also check that you have the correct secret and the right reddit username + password.

**Comment by newbieverse** [comment]
Thx for the reply...but its giving me another error i beleive that the username and password i have put is correct
![Capture](https://user-images.githubusercontent.com/107300892/173192679-44186d72-5550-4014-946e-b2cdf979133d.PNG)

**Comment by JasonLovesDoggo** [comment]
401 means access denied so exactly what evfus said

**Comment by newbieverse** [comment]
Thx working now
