### ISSUE TITLE
Moviepy error

### ISSUE THREAD

**Issue by rkleczek457** [elebumm/RedditVideoMakerBot#457]
I get the error message that i have seen others get too but the solution does not work

```
> ` Thanks for using this tool! Feel free to contribute to this project on     
>    GitHub! If you have any questions, feel free to reach out to me on Twitter   
>                            or submit a GitHub issue.                            
>                                                                                 
>                                                                                 
> [23:08:58] Checking environment variables...                          main.py:48
> [23:08:59] Enviroment Variables are set! Continuing...                main.py:90
> What subreddit would you like to pull from? r/askreddit
> Video will be: Redditors who grew up with strict parents, what was the most 
> absurd rule you had to follow? 👍
> [23:09:08] Getting video comments...                             subreddit.py:61
> Received AskReddit threads successfully.
> ╭──────────────────────────────────────────────────────────────────────────────╮
> │ Saving Text to MP3 files...                                                  │
> ╰──────────────────────────────────────────────────────────────────────────────╯
> Saving... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.2 it/s  
> Saved Text to MP3 files successfully.
> ╭──────────────────────────────────────────────────────────────────────────────╮
> │ Downloading Screenshots of Reddit Posts 📷                                   │
> ╰──────────────────────────────────────────────────────────────────────────────╯
> Launching Headless Browser...
> Downloading screenshots... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.2 it/s  
> Screenshots downloaded Successfully.
> ╭──────────────────────────────────────────────────────────────────────────────╮
> │ We need to download the Minecraft background video. This is fairly large but │
> │ it's only done once.                                                         │
> ╰──────────────────────────────────────────────────────────────────────────────╯
> Downloading the background video... please be patient.
> [youtube] n_Dv4JMiwK8: Downloading webpage
> [youtube] n_Dv4JMiwK8: Downloading android player API JSON
> [info] n_Dv4JMiwK8: Downloading 1 format(s): 308+251
> [download] assets/mp4/background.f308.webm has already been downloaded
> [download] 100% of 5.84GiB
> [download] assets/mp4/background.f251.webm has already been downloaded
> [download] 100% of 80.34MiB
> [Merger] Merging formats into "assets/mp4/background.mp4"
>         Deleting original file assets/mp4/background.f251.webm (pass -k to keep)
> Deleting original file assets/mp4/background.f308.webm (pass -k to keep)
> Background video downloaded successfully!
> ╭──────────────────────────────────────────────────────────────────────────────╮
> │ Finding a spot in the background video to chop...                            │
> ╰──────────────────────────────────────────────────────────────────────────────╯
> Moviepy - Running:
> >>> "+ " ".join(cmd)
> Moviepy - Command returned an error
> Traceback (most recent call last):
>   File "main.py", line 99, in <module>
>     chop_background_video(length)
>   File "/home/robert/RedditVideoMakerBot/video_creation/background.py", line 45, in chop_background_video
>     ffmpeg_extract_subclip(
>   File "/home/robert/.local/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_tools.py", line 41, in ffmpeg_extract_subclip
>     subprocess_call(cmd)
>   File "/home/robert/.local/lib/python3.8/site-packages/moviepy/tools.py", line 54, in subprocess_call
>     raise IOError(err.decode('utf8'))
> OSError: ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
>   built with gcc 8 (Debian 8.3.0-6)
>   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
>   libavutil      56. 31.100 / 56. 31.100
>   libavcodec     58. 54.100 / 58. 54.100
>   libavformat    58. 29.100 / 58. 29.100
>   libavdevice    58.  8.100 / 58.  8.100
>   libavfilter     7. 57.100 /  7. 57.100
>   libswscale      5.  5.100 /  5.  5.100
>   libswresample   3.  5.100 /  3.  5.100
>   libpostproc    55.  5.100 / 55.  5.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/mp4/background.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2mp41
>     encoder         : Lavf58.76.100
>   Duration: 01:20:13.08, start: 0.000000, bitrate: 10571 kb/s
>     Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 2560x1440, 10419 kb/s, SAR 1:1 DAR 16:9, 59.90 fps, 59.94 tbr, 16k tbn, 16k tbc (default)
>     Metadata:
>       handler_name    : VideoHandler
>     Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 137 kb/s (default)
>     Metadata:
>       handler_name    : SoundHandler
> [mp4 @ 0x66f9180] track 1: codec frame size is not set
> [mp4 @ 0x66f9180] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
> Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
> Stream mapping:
>   Stream #0:0 -> #0:0 (copy)
>   Stream #0:1 -> #0:1 (copy)
>     Last message repeated 1 times
> `
```

**Comment by SammysDiscussion** [comment]
try pip3 install Moviepy, or python install Moviepy, or python3 install Moviepy, or pipwin install Moviepy.

**Comment by micziz** [comment]
There was an error with movie.py. Try uninstalling It by running `pip3 uninstall moviepy` and then re installing it by running `pip3 install moviepy`

**Comment by rkleczek457** [comment]
Still nothing,same error

**Comment by rkleczek457** [comment]
> `[mp4 @ 0x5e69180] track 1: codec frame size is not set
[mp4 @ 0x5e69180] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
`
Appears to may be the problem. How would i enable the features?

**Comment by micziz** [comment]
You need to eneble it in the moviepy settings. dunno how to do it

**Comment by rkleczek457** [comment]
That helps me in no way whatsoever

**Comment by micziz** [comment]
I traced back the issue. Seems to be something faulty with either your moveipy installation or your ffmpeg one. Please re-install them and try again!

**Comment by Lath08** [comment]
I have uninstalled both the ffmpeg and moviepy and reinstalled them both, nothing has changed, I'm still getting the error.

```
Saving... ---------------------------------------- 4.0 it/s
Saved Text to MP3 files successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading Screenshots of Reddit Posts 📷                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Downloading screenshots... ---------------------------------------- 0.3 it/s
Screenshots downloaded Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Finding a spot in the background video to chop...                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command returned an error
Traceback (most recent call last):
  File "C:\Users\Lath\Downloads\RedditVideoMakerBot-master\main.py", line 99, in <module>
    chop_background_video(length)
  File "C:\Users\Lath\Downloads\RedditVideoMakerBot-master\video_creation\background.py", line 45, in chop_background_video
    ffmpeg_extract_subclip(
  File "C:\Users\Lath\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_tools.py", line 41, in ffmpeg_extract_subclip
    subprocess_call(cmd)
  File "C:\Users\Lath\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'assets/mp4/background.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.24.100
  Duration: 01:20:13.08, start: 0.000000, bitrate: 10571 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 2560x1440, 10419 kb/s, SAR 1:1 DAR 16:9, 59.90 fps, 59.94 tbr, 16k tbn, 16k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 137 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
[mp4 @ 0000026662bafb80] track 1: codec frame size is not set
[mp4 @ 0000026662bafb80] opus in MP4 support is experimental, add '-strict -2' if you want to use it.
Could not write header for output file #0 (incorrect codec parameters ?): Experimental feature
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
    Last message repeated 1 times


```

**Comment by Lath08** [comment]
I've found the fix, it's in my thread here: https://github.com/elebumm/RedditVideoMakerBot/issues/496#issuecomment-1159206027

**Comment by micziz** [comment]
If you found the fix, Cloud you close the issue

**Comment by rkleczek457** [comment]
> I've found the fix, it's in my thread here: https://github.com/elebumm/RedditVideoMakerBot/issues/496#issuecomment-1159206027

Problem is I'm on Linux so can't find that file. Linux should be able to work as well but I can't find that file

**Comment by micziz** [comment]
home/robert/.local/lib/python3.8/site-packages/moviepy/tools.py

**Comment by micziz** [comment]
Try there

**Comment by micziz** [comment]
Or in that directory

**Comment by JasonLovesDoggo** [comment]
stale
