### ISSUE TITLE
Headless Browser Error

### ISSUE THREAD

**Issue by Justice-hub** [elebumm/RedditVideoMakerBot#462]
Help me whit this, please:

```
Launching Headless Browser...
Traceback (most recent call last):
  File "C:\Users\bonec\Desktop\RedditVideoMakerBot-1.1\main.py", line 95, in <module>
    download_screenshots_of_reddit_posts(
  File "C:\Users\bonec\Desktop\RedditVideoMakerBot-1.1\video_creation\screenshot_downloader.py", line 23, in download_screenshots_of_reddit_posts 
    browser = p.chromium.launch()
  File "C:\Users\bonec\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 11538, in launch        
    self._sync(
  File "C:\Users\bonec\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\bonec\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\bonec\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\bonec\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> C:\Users\bonec\AppData\Local\ms-playwright\chromium-1005\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\bonec\AppData\Local\Temp\playwright_chromiumdev_profile-FM3H5N --remote-debugging-pipe --no-startup-window
<launched> pid=15172
============================================================
```

**Comment by JasonLovesDoggo** [comment]
This is most probably caused by you having unstable internet

**Comment by Justice-hub** [comment]
> This is most probably caused by you having unstable internet

Thanks man, now i get It!
