### ISSUE TITLE
yt_dlp cannot download video (i am on arch linux)

### ISSUE THREAD

**Issue by Lushioe** [elebumm/RedditVideoMakerBot#470]
this is the following terminal input:
Downloading the background video... please be patient.
[youtube] n_Dv4JMiwK8: Downloading webpage
[youtube] n_Dv4JMiwK8: Downloading android player API JSON
[info] n_Dv4JMiwK8: Downloading 1 format(s): 308+251
[download] Destination: assets/mp4/background.f308.webm
[download]   2.3% of 5.84GiB at  2.49MiB/s ETA 39:11[download] Got server HTTP error: <urlopen error [Errno -3] Temporary failure in name resolution>
ERROR: giving up after 0 retries
Traceback (most recent call last):
  File "/home/samuel/RedditVideoMakerBot/main.py", line 98, in <module>
    download_background()
  File "/home/samuel/RedditVideoMakerBot/video_creation/background.py", line 35, in download_background
    ydl.download("https://www.youtube.com/watch?v=n_Dv4JMiwK8")
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3254, in download
    self.__download_wrapper(self.extract_info)(
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3230, in wrapper
    res = func(*args, **kwargs)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1479, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1535, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2640, in process_video_result
    self.process_info(new_info)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3112, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2838, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 445, in download
    ret = self.real_download(filename, info_dict)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 387, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/samuel/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: giving up after 0 retries
[samuel@SamuelUsesArchBTW RedditVideoMakerBot]$ 

also can i manually download the video and rename it so the script will think that the video is already downloaded?

**Comment by M00nMission** [comment]
just do it manually and name it "background.mp4" stick it in `assets/` or `out/mp4/`
