### ISSUE TITLE
Movie.py Error Broken pipe

### ISSUE THREAD

**Issue by BradTFT** [elebumm/RedditVideoMakerBot#493]
this may be a dupe of #468 

getting this error at the end of running main.py

```

Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command successful
Background video chopped successfully!
╭──────────────────────────────────────────────────────────────────────────────────────────╮
│ Creating the final video...                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
<thread info>

t:   0%|                                                 | 0/1850 [00:00<?, ?it/s, now=None]Traceback (most recent call last):
  File "/home/bradtft/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_writer.py", line 136, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bradtft/fork/RedditVideoMakerBot/main.py", line 100, in <module>
    final_video = make_final_video(number_of_comments)
  File "/home/bradtft/fork/RedditVideoMakerBot/video_creation/final_video.py", line 84, in make_final_video
    final.write_videofile(filename, fps=30, audio_codec="aac", audio_bitrate="192k")
  File "<decorator-gen-55>", line 2, in write_videofile
  File "/home/bradtft/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "/home/bradtft/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "/home/nradtft/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/bradtft/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/home/bradtft/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_writer.py", line 228, in ffmpeg_write_video
    writer.write_frame(frame)
  File "/home/bradtft/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file assets/thread.mp4:

 b"Unrecognized option 'preset'.\nError splitting the argument list: Option not found\n"
```

(everything in "thread" was replaced. i didnt actually put "thread" as my answer)

**Comment by Bust2191** [comment]
maybe lol?

**Comment by BradTFT** [comment]
and the solution is?
