### ISSUE TITLE
.env wotn read

### ISSUE THREAD

**Issue by UnripePocketWatch** [elebumm/RedditVideoMakerBot#494]
the program wont read the .env files on my computer an keeps returning empty values

**Comment by CordlessCoder** [comment]
@Rufluenza your answer does assume they're on a Linux system, as `nano` and `mv` aren't present in CMD or Powershell.
@UnripePocketWatch are you sure your .env file is correctly configured? If not, you can do `python3 setup.py` to launch the configuration wizard to generate a correct .env file for you.

**Comment by UnripePocketWatch** [comment]
> @Rufluenza your answer does assume they're on a Linux system, as `nano` and `mv` aren't present in CMD or Powershell. @UnripePocketWatch are you sure your .env file is correctly configured? If not, you can do `python3 setup.py` to launch the configuration wizard to generate a correct .env file for you. (The setup.py file is rather outdated in the master branch, my updates to it will get merged on next release)

It wont let my use python3 main.py 
and also i cant get the .env to stop being a template

**Comment by UnripePocketWatch** [comment]
ok fixed that but @CordlessCoder i keep getting this error


Downloading the background video... please be patient.
[youtube] n_Dv4JMiwK8: Downloading webpage
[youtube] n_Dv4JMiwK8: Downloading android player API JSON
[info] n_Dv4JMiwK8: Downloading 1 format(s): 22
[download] Destination: assets\mp4\background.mp4
[download]   2.3% of 1.09GiB at  2.88MiB/s ETA 06:18[download] Got server HTTP error: Downloaded 26686302 bytes, expected 1167614097 bytes
ERROR: giving up after 0 retries
Traceback (most recent call last):
  File "C:\Users\Samwise\OneDrive\Documents\RedditVideoMakerBot\main.py", line 98, in <module>
    download_background()
  File "C:\Users\Samwise\OneDrive\Documents\RedditVideoMakerBot\video_creation\background.py", line 35, in download_background
    ydl.download("https://www.youtube.com/watch?v=n_Dv4JMiwK8")
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3254, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3230, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1479, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1535, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2640, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3130, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2838, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 445, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 387, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Samwise\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 879, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: giving up after 0 retries

**Comment by JasonLovesDoggo** [comment]
invalid
