### ISSUE TITLE
error in main.py

### ISSUE THREAD

**Issue by alexgarciiaa** [elebumm/RedditVideoMakerBot#497]
Traceback (most recent call last):
  File "/home/alexgarcia/RedditVideoMakerBot/main.py", line 93, in <module>
    reddit_object = get_subreddit_threads()
  File "/home/alexgarcia/RedditVideoMakerBot/reddit/subreddit.py", line 58, in get_subreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/praw/reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/praw/reddit.py", line 739, in _objectify_request
    self.request(
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/prawcore/auth.py", line 425, in refresh
    self._request_token(
  File "/home/alexgarcia/.local/lib/python3.9/site-packages/prawcore/auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by FreebieII** [comment]
## Hi! 

# Please refer to [**THIS**](https://immaharry.gitbook.io/reddit-automated-video-bot/final-words/error-1)


### https://immaharry.gitbook.io/reddit-automated-video-bot/final-words/error-1

**Comment by FreebieII** [comment]
> 

Is everything in your `.env` file correct? Please send a screenshot of it here, blurring important credentials!

**Comment by alexgarciiaa** [comment]
![WhatsApp Image 2022-06-15 at 10 37 24 AM](https://user-images.githubusercontent.com/96591872/173783353-214ffe11-3776-4d32-8e7e-3dfa99a11edf.jpeg)

**Comment by UserOneXX** [comment]
Ohh, im so stupid lol. When you create developer app under reddit.com/pref/apps you have to choose third option aka SCRIPT. Now it's working.
