### ISSUE TITLE
Issues while installing playwright

### ISSUE THREAD

**Issue by yungbunfg** [elebumm/RedditVideoMakerBot#505]
OS: Windows 10 
Using admin command prompt to run the commands

When I try and run main.py everything works flawlessly until the screenshots part where a pop-up comes up:

C:\Users\CENSORED\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master>python3 main.py

  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
                                to reach out to me on Twitter or submit a GitHub issue.

[19:20:13] Checking environment variables...                                                                 main.py:48
[19:20:14] Enviroment Variables are set! Continuing...                                                       main.py:90
Video will be: What things should be kept private from your SO, no matter how healthy your relationship is? 👍
[19:20:15] Getting video comments...                                                                    subreddit.py:61
Received AskReddit threads successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... ---------------------------------------- 0.5 it/s
Saved Text to MP3 files successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading Screenshots of Reddit Posts 📷                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Traceback (most recent call last):
  File "C:\Users\CENSORED\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 95, in <module>
    download_screenshots_of_reddit_posts(
  File "C:\Users\CENSORED\\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 23, in download_screenshots_of_reddit_posts
    browser = p.chromium.launch()
  File "C:\Users\CENSORED\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\sync_api\_generated.py", line 11538, in launch
    self._sync(
  File "C:\Users\CENSORED\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\CENSORED\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\CENSORED\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\CENSORED\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\CENSORED\\AppData\Local\ms-playwright\chromium-1005\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

I have attempted to solve this by:

Re-installing requirements.txt - Says all requirements are met
Re-installing playwright via pip3 playwright install: Says all requirements are met
Re-doing playwright-deps:  I get the following error:

C:\Users\CENSORED\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master>pip3 install playwright-deps
ERROR: Could not find a version that satisfies the requirement playwright-deps (from versions: none)
ERROR: No matching distribution found for playwright-deps

Please help me in solving this issue. If it makes any difference I am running a fairly crappy pentium silver laptop with 2 gigs of disk space left. Thanks in advance!

**Comment by micziz** [comment]
Have you done `playwright install`, without pip?

**Comment by yungbunfg** [comment]
I don't know if I am doing anything wrong but typing playwright install into command prompt just gives you "this command is not recognised as an internal or external command" text.

**Comment by yungbunfg** [comment]
Update: Doing ``python3 -m playwright install`` seems to have fixed the issue. I will re-open it if persists after testing. Thank you.
