### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by sarimwaniR** [elebumm/RedditVideoMakerBot#531]
![hin](https://user-images.githubusercontent.com/101258901/174337625-bb38e9d1-24e2-4b4f-b678-a8856685ffef.png)
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
**pleas help**

**Comment by sarimwaniR** [comment]
https://drive.google.com/file/d/1jhiM2CZ2XUO36X71q1xDRKhs8eOT0XOw/view?usp=sharing

**Comment by sarimwaniR** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
video link

**Comment by sarimwaniR** [comment]
youtube link
https://youtu.be/bIebyGtplFE

**Comment by micziz** [comment]
You are not in the directory of the reddit bot.

**Comment by JasonLovesDoggo** [comment]
Exactly what Mic said

**Comment by sarimwaniR** [comment]
How to do that

**Comment by micziz** [comment]
Follow the documentation https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/

**Comment by sarimwaniR** [comment]
Microsoft Windows [Version 10.0.22610.1]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master>python main.py
'sox' is not recognized as an internal or external command,
operable program or batch file.
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.


██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝



  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
     to reach out to me on Twitter or submit a GitHub issue. You can find solutions to many common problems in the
                                                     Documentation


Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit from environment variable config
Traceback (most recent call last):
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 68, in <module>
    main()
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 45, in main
    reddit_object = get_obj()
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 42, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\reddit\subreddit.py", line 65, in get_subreddit_threads
    submission = get_subreddit_undone(threads, subreddit)
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\utils\subreddit.py", line 13, in get_subreddit_undone
    for submission in submissions:
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 373, in refresh
    self._request_token(
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

**Comment by sarimwaniR** [comment]
![fist](https://user-images.githubusercontent.com/101258901/174433838-3190907f-c223-4d53-a40f-3f944e04d122.png)
![ddd](https://user-images.githubusercontent.com/101258901/174433808-a1da2c63-3833-4dbb-b8c2-fd174604daac.png)

**Comment by JasonLovesDoggo** [comment]
So install SOX...
