### ISSUE TITLE
KeyError: 'MAX_COMMENT_LENGTH' (help how to fix this)

### ISSUE THREAD

**Issue by ddivide** [elebumm/RedditVideoMakerBot#539]
Using subreddit: r/AskReddit from environment variable config
Video will be: What don't you find attractive that society says you should? 👍
Thread has 6328 upvotes
Thread has a upvote ratio of 91.0%
Thread has 5670 comments
Traceback (most recent call last):
  File "C:\Users\ddiv1de\Downloads\Compressed\RedditVideoMakerBot-2.0\main.py", line 68, in <module>
    main()
  File "C:\Users\ddiv1de\Downloads\Compressed\RedditVideoMakerBot-2.0\main.py", line 45, in main
    reddit_object = get_obj()
  File "C:\Users\ddiv1de\Downloads\Compressed\RedditVideoMakerBot-2.0\main.py", line 42, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\ddiv1de\Downloads\Compressed\RedditVideoMakerBot-2.0\reddit\subreddit.py", line 94, in get_subreddit_threads
    if len(top_level_comment.body) <= int(environ["MAX_COMMENT_LENGTH"]):
  File "C:\Users\ddiv1de\AppData\Local\Programs\Python\Python310\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MAX_COMMENT_LENGTH'
![3132131](https://user-images.githubusercontent.com/102805220/174426893-614ef545-532c-4a8c-95fd-d55c9c930264.png)

**Comment by Xefili** [comment]
Add MAX_COMMENT_LENGTH=500 to your .env file
