### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) (help how to fix this)

### ISSUE THREAD

**Issue by ddivide** [elebumm/RedditVideoMakerBot#546]
Traceback (most recent call last):
  File "C:\Users\ddiv1de\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\ddiv1de\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ddiv1de\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ddiv1de\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ddiv1de\Downloads\Compressed\RedditVideoMakerBot-2.0\main.py", line 66, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\ddiv1de\Downloads\Compressed\RedditVideoMakerBot-2.0\main.py", line 59, in run_many
    main()
  File "C:\Users\ddiv1de\Downloads\Compressed\RedditVideoMakerBot-2.0\main.py", line 46, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\ddiv1de\Downloads\Compressed\RedditVideoMakerBot-2.0\video_creation\voices.py", line 54, in save_text_to_mp3
    TextToSpeech.tts(
  File "C:\Users\ddiv1de\Downloads\Compressed\RedditVideoMakerBot-2.0\TTS\POLLY.py", line 41, in tts
    if response.json()['error'] == 'T![312321312444](https://user-images.githubusercontent.com/102805220/174438296-21c22bb8-f82c-4bd3-bd11-e5f6fafdcf30.jpg)!':
  File "C:\Users\ddiv1de\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by JasonLovesDoggo** [comment]
Are you absolutely sure that this is the newest book

**Comment by ddivide** [comment]
yes 2.0

**Comment by EmotionIce** [comment]
Having almost the same issue. The Error that happened during the handling of the first is different.
![image](https://user-images.githubusercontent.com/46056526/174674965-0c826e8c-0195-4554-95ba-c299c9975169.png)
