### ISSUE TITLE
KeyError: 'MAX_COMMENT_LENGTH'

### ISSUE THREAD

**Issue by smartbutnotvery** [elebumm/RedditVideoMakerBot#565]
Traceback (most recent call last):
  File "D:\yt\reddit post bot\RedditVideoMakerBot-master\main.py", line 69, in <module>
    main()
  File "D:\yt\reddit post bot\RedditVideoMakerBot-master\main.py", line 46, in main
    reddit_object = get_obj()
  File "D:\yt\reddit post bot\RedditVideoMakerBot-master\main.py", line 43, in get_obj
    reddit_obj = get_subreddit_threads()
  File "D:\yt\reddit post bot\RedditVideoMakerBot-master\reddit\subreddit.py", line 86, in get_subreddit_threads
    if len(top_level_comment.body) <= int(environ["MAX_COMMENT_LENGTH"]):
  File "D:\apps\python\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MAX_COMMENT_LENGTH'

**Comment by Salty-Coder** [comment]
I have the same issue.

**Comment by Lopastudio** [comment]
You just have to copy ENTIRE .env template file and rename it to .env. Then put into that new .env file your info (configure it) and set MAX_COMMENT_LENGTH and it should work :)

![image](https://user-images.githubusercontent.com/79789176/174486534-3e51c825-dfe7-4ad7-87d8-6e95d8724eb9.png)

**Comment by smartbutnotvery** [comment]
yhanks for the help
