### ISSUE TITLE
main can not get TTS POLLY, JSONDecodeError and save_text_to_mp3

### ISSUE THREAD

**Issue by gffgmhj** [elebumm/RedditVideoMakerBot#568]
Traceback (most recent call last):
  File "C:/Users/C.Pöppl/Desktop/RedditVideoMakerBot-master/main.py", line 12, in <module>
    from video_creation.voices import save_text_to_mp3
  File "C:\Users\C.Pöppl\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 11, in <module>
    from TTS.swapper import TTS
  File "C:\Users\C.Pöppl\Desktop\RedditVideoMakerBot-master\TTS\swapper.py", line 6, in <module>
    from TTS.POLLY import POLLY
  File "C:\Users\C.Pöppl\Desktop\RedditVideoMakerBot-master\TTS\POLLY.py", line 9, in <module>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (D:\conda\lib\site-packages\requests\exceptions.py)

**Comment by sarimwaniR** [comment]
restarting the computer and doing it again worked for me 
step by step explantion-https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/downloading-the-bot
