### ISSUE TITLE
Got a Unicode Error when running the program

### ISSUE THREAD

**Issue by DuarteMPAndre** [elebumm/RedditVideoMakerBot#571]
Got this error when running 'main.py': 

Traceback (most recent call last):
File "c:\Users\Utilizador\Downloads\RedditVideoMakerBot-master\main.py", line 60, in
main()
File "c:\Users\Utilizador\Downloads\RedditVideoMakerBot-master\main.py", line 37, in main
reddit_object = get_obj()
File "c:\Users\Utilizador\Downloads\RedditVideoMakerBot-master\main.py", line 34, in get_obj
reddit_obj = get_subreddit_threads()
File "c:\Users\Utilizador\Downloads\RedditVideoMakerBot-master\reddit\subreddit.py", line 69, in get_subreddit_threads
print_substep(f"Video will be: {submission.title} 👍", style="bold green")
File "c:\Users\Utilizador\Downloads\RedditVideoMakerBot-master\utils\console.py", line 27, in print_substep
console.print(text, style=style)
File "C:\Users\Utilizador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rich\console.py", line 1683, in print
self._buffer.extend(new_segments)
File "C:\Users\Utilizador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rich\console.py", line 838, in exit
self._exit_buffer()
File "C:\Users\Utilizador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rich\console.py", line 796, in _exit_buffer
self._check_buffer()
File "C:\Users\Utilizador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rich\console.py", line 1988, in _check_buffer
legacy_windows_render(
File "C:\Users\Utilizador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rich_windows_renderer.py", line 17, in legacy_windows_render
term.write_styled(text, style)
File "C:\Users\Utilizador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rich_win32_console.py", line 418, in write_styled
self.write_text(text)
File "C:\Users\Utilizador\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\rich_win32_console.py", line 379, in write_text
self.write(text)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f44d' in position 29: character maps to

**Comment by hawa5085** [comment]
Run it from CMD not bitbash and it will work
