### ISSUE TITLE
Case fold error

### ISSUE THREAD

**Issue by pkuba208** [elebumm/RedditVideoMakerBot#575]
╭──────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                          │
╰──────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    main()
  File "main.py", line 47, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/root/RedditVideoMakerBot-master/video_creation/voices.py", line 32, in save_text_to_mp3
    TextToSpeech = TTS()
  File "/root/RedditVideoMakerBot-master/TTS/swapper.py", line 15, in __new__
    CHOICE = getenv("TTsChoice").casefold()
AttributeError: 'NoneType' object has no attribute 'casefold'
Here's my env file:
GNU nano 4.8              .env
REDDIT_CLIENT_ID="xxx"
REDDIT_CLIENT_SECRET="xxx"
REDDIT_USERNAME="NiceManBot"
REDDIT_PASSWORD="xxx"
REDDIT_2FA="no"
THEME="dark"
SUBREDDIT="AskReddit"
OPACITY=1.0
MAX_COMMENT_LENGTH=500

**Comment by hiccup-09** [comment]
have the same issue..please do reply if you got any solution !!
