### ISSUE TITLE
i cant explain this error

### ISSUE THREAD

**Issue by BradTFT** [elebumm/RedditVideoMakerBot#584]
backstory:
so i was re reading the prereqs and noticed i didnt have SOX. so i installed it. also noticed that ffmpeg was installed on my system via the website and also with pip. so i uninstalled the pip version and ran 'sudo apt update` and re ran the script. got this error:

```
╭──────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/gtts/tts.py", line 265, in stream
    r = s.send(
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/BradTFT/fork/RedditVideoMakerBot/main.py", line 94, in <module>
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/home/BradTFT/fork/RedditVideoMakerBot/video_creation/voices.py", line 31, in save_text_to_mp3
    tts.save(f"assets/mp3/posttext.mp3")
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/gtts/tts.py", line 329, in save
    self.write_to_fp(f)
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/gtts/tts.py", line 310, in write_to_fp
    for idx, decoded in enumerate(self.stream()):
  File "/home/BradTFT/fork/RedditVideoMakerBot/redditvenv/lib/python3.9/site-packages/gtts/tts.py", line 281, in stream
    raise gTTSError(tts=self)
gtts.tts.gTTSError: Failed to connect. Probable cause: Unknown
``` 

trying to use this script has gone error to error 😞

**Comment by BradTFT** [comment]
did this and got this error

```
╭──────────────────────────────────────────────────────────────────────────────────────────╮
│ Creating the final video 🎥                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/home/BradTFT/fork/RedditVideoMakerBot/main.py", line 71, in <module>
    main()
  File "/home/BradTFT/fork/RedditVideoMakerBot/main.py", line 53, in main
    make_final_video(number_of_comments, length)
  File "/home/BradTFT/fork/RedditVideoMakerBot/video_creation/final_video.py", line 34, in make_final_video
    VideoFileClip("assets/temp/background.mp4")
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
```

i am on debian and im not sure where i can get the updated version

**Comment by HallowedDust5** [comment]
Haha I just got the same error a few hours ago and was about to figure out what happened. Im on an Ubuntu based distro. I would start by looking at the movies website if there is one, and then the PyPi page for it.

**Comment by BradTFT** [comment]
?? can you provide links

**Comment by HallowedDust5** [comment]
[Here's](https://github.com/Zulko/moviepy) the MoviePy repo, I tried to install the repo directly from source and I had no luck, getting the same error. Hopefully you can do better though.

**Comment by BradTFT** [comment]
So try cloning and installing from source?

**Comment by BradTFT** [comment]
i tried installing [this](https://ffmpeg.org/download.html) version of ffmpeg. its newest version and came out 2 months ago. (version  FFmpeg 5.0.1 "Lorentz". scroll down on the above linked website. obviously if you are reading this issue in the future choose the newest one). gets the same error. i tried uninstalling moviepy from pip and using the cloned repo version but it wouldnt recognise that it was there. so i had to use the pip install.

**Comment by HallowedDust5** [comment]
Ya, ive been asking around on the discord server if anyone's been able to fix, but sadly, nothing's come up.
