### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by 0jrv** [elebumm/RedditVideoMakerBot#585]
i run main.py everything seems fine it gets the video name, upvotes, upvote ratio, comments, after that it give me a error?

Video will be: What's a modern day scam that's become normalized and we don't realize it's a scam anymore? 👍
Thread has 36020 upvotes
Thread has a upvote ratio of 88.0%
Thread has 22021 comments
Traceback (most recent call last):
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 69, in <module>
    main()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 46, in main
    reddit_object = get_obj()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 43, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\reddit\subreddit.py", line 86, in get_subreddit_threads
    if len(top_level_comment.body) <= int(environ["MAX_COMMENT_LENGTH"]):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MAX_COMMENT_LENGTH'

**Comment by LohnGG** [comment]
I have the same issue

**Comment by ytfuzzy** [comment]
Add `MAX_COMMENT_LENGTH=500`  to your .env file

**Comment by 0jrv** [comment]
now its Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit from environment variable config
Traceback (most recent call last):
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 69, in <module>
    main()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 46, in main
    reddit_object = get_obj()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 43, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\reddit\subreddit.py", line 61, in get_subreddit_threads
    submission = get_subreddit_undone(threads, subreddit)
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\utils\subreddit.py", line 17, in get_subreddit_undone
    if getenv("ALLOW_NSFW").casefold() == "false":
AttributeError: 'NoneType' object has no attribute 'casefold'

**Comment by 0jrv** [comment]
now its
Traceback (most recent call last):
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 69, in <module>
    main()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 46, in main
    reddit_object = get_obj()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\main.py", line 43, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\reddit\subreddit.py", line 61, in get_subreddit_threads
    submission = get_subreddit_undone(threads, subreddit)
  File "C:\Users\User\Downloads\RedditVideoMakerBot-master\utils\subreddit.py", line 17, in get_subreddit_undone
    if getenv("ALLOW_NSFW").casefold() == "false":
AttributeError: 'NoneType' object has no attribute 'casefold'
