### ISSUE TITLE
main.py won't work

### ISSUE THREAD

**Issue by frightened-2011** [elebumm/RedditVideoMakerBot#591]
i was trying to use this bot and it says this:

SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    print(
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\encodings\cp1py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-8:racter maps to <undefined>

**Comment by ytfuzzy** [comment]
Hey, you may need to install SoX if you haven't already. 
Open a terminal in the folder where your files are and run `pip install -r requirements.txt` or something If you haven't already, 
Otherwise manually download the SoX from here if it still doesn't: workhttps://sourceforge.net/projects/sox/files/sox/

**Comment by frightened-2011** [comment]
hi, it still gives me this error even when i installed sox:
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    print(
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2-8: character maps to <undefined>

Windows 7 Ultimate
Using Git Bash

**Comment by frightened-2011** [comment]
hi, i tried with cmd and it worked but it gives this error:

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ███
███╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═
══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║
  ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║
  ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚███
███╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚══
═══╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝



    Thanks for using this tool! Feel free to contribute to this project on
  GitHub! If you have any questions, feel free to reach out to me on Twitter
  or submit a GitHub issue. You can find solutions to many common problems in
                               the Documentation


Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                │
└─────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/entitledparents from environment variable config
Video will be: Mom insists I go to college or she'll turn my phone off ??
Thread has 727 upvotes
Thread has a upvote ratio of 95.0%
Thread has 172 comments
Received subreddit threads Successfully.
┌─────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                 │
└─────────────────────────────────────────────────────────────────────────────┘
Saving... --- ------------------------------------   9% 0:01:14
Saved Text to MP3 files Successfully.
┌─────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts...                                  │
└─────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    main()
  File "main.py", line 49, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\pc\reddit\RedditVideoMakerBot\video_creation\screenshot_downloa
der.py", line 29, in download_screenshots_of_reddit_posts
    with sync_playwright() as p:
  File "C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\pla
ywright\sync_api\_context_manager.py", line 83, in __enter__
    playwright = self._playwright
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'

Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection.run.<locals>.init() running a
t C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\playwrigh
t\_impl\_connection.py:197> wait_for=<Future pending cb=[<TaskWakeupMethWrapper
object at 0x00000000077F8C40>()]> cb=[ProtocolCallback.__init__.<locals>.cb() at
 C:\Users\pc\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright
\_impl\_connection.py:130]>

**Comment by frightened-2011** [comment]
hi, i found the error, playwright's new version doesnt work on windows 7 i just installed an old one and it worked.

**Comment by frightened-2011** [comment]
oh, nope it wont work help pls

**Comment by frightened-2011** [comment]
@il-progammatore-py help me please, so che lo hai sistemato puttanella, metti qua i file

**Comment by frightened-2011** [comment]
a friend is helping me, byee
