### ISSUE TITLE
[Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

### ISSUE THREAD

**Issue by OndrejBartos** [elebumm/RedditVideoMakerBot#598]
Really not sure what's causing it
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
None defined. Defaulting to 'polly.'
Traceback (most recent call last):
  File "C:\Users\Name\AppData\Local\Programs\Python\Python39\lib\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\RedditGenerator\main.py", line 71, in <module>
    main()
  File "D:\RedditGenerator\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "D:\RedditGenerator\video_creation\voices.py", line 39, in save_text_to_mp3
    length += MP3("assets/temp/mp3/title.mp3").info.length
  File "C:\Users\Name\AppData\Local\Programs\Python\Python39\lib\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "C:\Users\Name\AppData\Local\Programs\Python\Python39\lib\site-packages\mutagen\_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "C:\Users\Name\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Users\Name\AppData\Local\Programs\Python\Python39\lib\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

**Comment by HallowedDust5** [comment]
I had this same problem and I'm pretty sure it's because SoX isn't installed properly. First, install it from [this](https://sourceforge.net/projects/sox/files/sox/) link, then when you unzip the dowload, it should have a file called INSTALL, follow that and it should lead you through how to get that set up.

**Comment by OndrejBartos** [comment]
> 

When I install SoX, it isn't a zip but a .exe installer. Where exactly is the file INSTALL?

**Comment by HallowedDust5** [comment]
Oh, if its an exe run that.

**Comment by OndrejBartos** [comment]
I have SoX installed and I still get the same error.

**Comment by OndrejBartos** [comment]
I can even use it in cmd.

**Comment by Jake006thesnake** [comment]
SOLVED- https://github.com/elebumm/RedditVideoMakerBot/issues/671

**Comment by Jake006thesnake** [comment]
> ut still getting the same

https://github.com/elebumm/RedditVideoMakerBot/issues/671

**Comment by Jake006thesnake** [comment]
> the dowload, it sh

https://github.com/elebumm/RedditVideoMakerBot/issues/671

**Comment by 16aces** [comment]
I get the same error when trying to use AWSPolly, tried reinstalling SOX and tried replacing the .env with the .env.template file
