### ISSUE TITLE
(english isnt my first language). Cant run the command "main.py" and dont know where to find the env file and enviroment things [PLEASE ADD AN VIDEO ON HOW TO INSTALL]

### ISSUE THREAD

**Issue by michiel1106** [elebumm/RedditVideoMakerBot#602]
cant run command main.py. it just says 

Traceback (most recent call last):
  File "/home/michiel/Downloads/RedditVideoMakerBot-master/main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "/home/michiel/Downloads/RedditVideoMakerBot-master/reddit/subreddit.py", line 4, in <module>
    import praw
ModuleNotFoundError: No module named 'praw'

and I dont know where the enviroment thing is.

Please add an video on how to do the installation.

doing it in kali linux btw ubuntu 32 bit enviroment thing.

**Comment by Zen0xQ** [comment]
try pip3 install praw
