### ISSUE TITLE
playwright._impl._api_types.TimeoutError

### ISSUE THREAD

**Issue by empe32** [elebumm/RedditVideoMakerBot#61]
Getting this error when it loads up the headless browser

Launching Headless Browser...
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\sharm\Desktop\vidbot\new\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 34, in download_screenshots_of_reddit_posts
    page.locator('[data-test-id="post-content"]').screenshot(
  File "C:\Python38\lib\site-packages\playwright\sync_api\_generated.py", line 13249, in screenshot
    self._sync(
  File "C:\Python38\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Python38\lib\site-packages\playwright\_impl\_locator.py", line 394, in screenshot
    return await self._with_element(
  File "C:\Python38\lib\site-packages\playwright\_impl\_locator.py", line 99, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Python38\lib\site-packages\playwright\_impl\_locator.py", line 219, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Python38\lib\site-packages\playwright\_impl\_frame.py", line 293, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Python38\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Python38\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-test-id="post-content"]"
============================================================

**Comment by FreebieII** [comment]
Please see #34

**Comment by FreebieII** [comment]
Hi @empe32 

I hope you were able to resolve your issue, I will be closing this for the time being.  Feel free to re-open the issue if it has not been solved!

Happy Coding!
