### ISSUE TITLE
sometime it shows

### ISSUE THREAD

**Issue by sarimwaniR** [elebumm/RedditVideoMakerBot#617]
Traceback (most recent call last):
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 68, in <module>
    main()
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 50, in main
    final_video = make_final_video(number_of_comments, length)
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 34, in make_final_video
    VideoFileClip("assets/temp/background.mp4")
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

**Comment by andrerrazambuja** [comment]
Try deleting assets/temp/background.mp4 and running it again. I think this may be caused by some error while downloading this background video.

**Comment by sarimwaniR** [comment]
ok

**Comment by sarimwaniR** [comment]
it worked

**Comment by DevTantia** [comment]
> Try deleting assets/temp/background.mp4 and running it again. I think this may be caused by some error while downloading this background video.

does not work for me
getting the same error

@andrerrazambuja

**Comment by sarimwaniR** [comment]
it work bro

**Comment by sarimwaniR** [comment]
re dowload

**Comment by sarimwaniR** [comment]
the copy

**Comment by DevTantia** [comment]
You mean run main.py again?

**Comment by sarimwaniR** [comment]
no clone the Repository again Put the stuff in and try again
