### ISSUE TITLE
Worked fine until..

### ISSUE THREAD

**Issue by michiel1106** [elebumm/RedditVideoMakerBot#622]
I got this error

Traceback (most recent call last):
  File "C:\Users\michi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\michi\Desktop\RedditVideoMakerBot-master\main.py", line 69, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\michi\Desktop\RedditVideoMakerBot-master\main.py", line 62, in run_many
    main()
  File "C:\Users\michi\Desktop\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\michi\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 33, in save_text_to_mp3
    TextToSpeech.tts(
  File "C:\Users\michi\Desktop\RedditVideoMakerBot-master\TTS\POLLY.py", line 61, in tts
    if response.json()["error"] == "Text length is too long!":
  File "C:\Users\michi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by pot-noodle-python** [comment]
Also just had this bug.

**Comment by pot-noodle-python** [comment]
Ok so I did some digging and it turns out the [text to speech website](https://streamlabs.com/polly/speak) is returning a 500 internal server error code. It looks like the website is down and we just need to wait for it to go back up.

**Comment by sarimwaniR** [comment]
oh how much time

**Comment by pot-noodle-python** [comment]
it's working now

**Comment by sarimwaniR** [comment]
C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master>python main.py

██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝



  Thanks for using this tool! Feel free to contribute to this project on GitHub! If you have any questions, feel free
     to reach out to me on Twitter or submit a GitHub issue. You can find solutions to many common problems in the
                                                     Documentation


Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/AskReddit from environment variable config
Video will be: How does someone politely end a conversation with a person who won't stop talking? 👍
Thread has 20874 upvotes
Thread has a upvote ratio of 95.0%
Thread has 6301 comments
Received subreddit threads Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Saving Text to MP3 files...                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Saving... -- -------------------------------------   6% 0:01:49
Saved Text to MP3 files Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts...                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Downloading screenshots... ---------------------------------------- 0.1 it/s
Screenshots downloaded Successfully.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ We need to download the backgrounds videos. they are fairly large but it's only done once. 😎                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Downloading the backgrounds videos... please be patient 🙏
Downloading parkour.mp4 from https://www.youtube.com/watch?v=n_Dv4JMiwK8
Traceback (most recent call last):
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 71, in <module>
    main()
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 51, in main
    download_background()
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\video_creation\background.py", line 39, in download_background
    YouTube(uri).streams.filter(res="1080p").first().download(
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\streams.py", line 252, in download
    for chunk in request.stream(
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\request.py", line 153, in stream
    raise MaxRetriesExceeded()
pytube.exceptions.MaxRetriesExceeded

**Comment by sarimwaniR** [comment]
shoes this to me

**Comment by sarimwaniR** [comment]
solved
