### ISSUE TITLE
pleas help me 

### ISSUE THREAD

**Issue by sarimwaniR** [elebumm/RedditVideoMakerBot#629]
Traceback (most recent call last):
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 71, in <module>
    main()
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 53, in main
    make_final_video(number_of_comments, length)
  File "C:\Users\Sarim wani\OneDrive\Desktop\RedditVideoMakerBot-master\video_creation\final_video.py", line 34, in make_final_video
    VideoFileClip("assets/temp/background.mp4")
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "C:\Users\Sarim wani\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

**Comment by PrestoSole** [comment]
There is already an open issue for this #617
