### ISSUE TITLE
[Errno 22] Invalid argument: '.\x0bideo_creation\\data\x0bideos.json'

### ISSUE THREAD

**Issue by Jekxd** [elebumm/RedditVideoMakerBot#634]
Using subreddit: r/AskReddit from environment variable config
Traceback (most recent call last):
  File "C:\Users\user\Desktop\test\RedditVideoMakerBot-master\main.py", line 71, in <module>
    main()
  File "C:\Users\user\Desktop\test\RedditVideoMakerBot-master\main.py", line 48, in main
    reddit_object = get_obj()
  File "C:\Users\user\Desktop\test\RedditVideoMakerBot-master\main.py", line 45, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\user\Desktop\test\RedditVideoMakerBot-master\reddit\subreddit.py", line 74, in get_subreddit_threads
    submission = get_subreddit_undone(threads, subreddit)
  File "C:\Users\user\Desktop\test\RedditVideoMakerBot-master\utils\subreddit.py", line 11, in get_subreddit_undone
    with open(".\video_creation\data\videos.json", "r") as done_vids_raw:
OSError: [Errno 22] Invalid argument: '.\x0bideo_creation\\data\x0bideos.json'

**Comment by JasonLovesDoggo** [comment]
Replace the backslashes with two backslashes in the open request
