### ISSUE TITLE
Does not process NSFW posts

### ISSUE THREAD

**Issue by Sanyam-Ahuja** [elebumm/RedditVideoMakerBot#649]
**Describe the bug**
Whenever it encounters a NSFW post it throws this error ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts...                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Post is NSFW. You are spicy...
Traceback (most recent call last):
  File "c:\Users\sanya\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 71, in <module>
    main()
  File "c:\Users\sanya\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 50, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "c:\Users\sanya\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 52, in download_screenshots_of_reddit_posts
    ).click()  # Remove "Click to see nsfw" Button in Screenshot
  File "C:\Users\sanya\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 12327, in click
    self._sync(
  File "C:\Users\sanya\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\sanya\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 144, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Users\sanya\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 460, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\sanya\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\sanya\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-click-id="text"] button"
===========================================================

**To Reproduce**
Just Make Sure Its a NSFW post and try to make the video Make sure to set NSFW in .env to true

**Screenshots**
![image](https://user-images.githubusercontent.com/69309970/174938551-544849c7-5d74-4b38-9330-b189c4ccb899.png)

**System (please complete the following information):**
Windows 11

**Comment by Sanyam-Ahuja** [comment]
fixed it

**Comment by Agility17** [comment]
How did you fix this?

**Comment by sahedge-was-taken** [comment]
@Sanyam-Ahuja How did you fix this?
