### ISSUE TITLE
Problem after running python3 main.py

### ISSUE THREAD

**Issue by Sgegsdge** [elebumm/RedditVideoMakerBot#66]
after running python3 main.py i get this error:
Traceback (most recent call last):
  File "C:\Users\[my username]\RedditVideoMakerBot\main.py", line 1, in <module>
    from utils.console import print_markdown
  File "C:\Users\[my username]\RedditVideoMakerBot\utils\console.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

it's worth mentioning that i have rich library installed so idk what is wrong

**Comment by lesterrar** [comment]
I have the same problem tho i don't know if I have the rich library installed

**Comment by p1x3lll** [comment]
> Have no idea why but for me worked to use `python main.py` instead of `python3 main.py`

makes no sense
