### ISSUE TITLE
No ffmpeg exe could be found

### ISSUE THREAD

**Issue by davidlol01** [elebumm/RedditVideoMakerBot#668]
Can someone help me, I don't get this error message
PS C:\Users\David2.LAPTOP-4COM5CAO\Desktop\RedditVideoMakerBot> python main.py
Traceback (most recent call last):
  File "C:\Users\David2.LAPTOP-4COM5CAO\Desktop\RedditVideoMakerBot\main.py", line 10, in <module>
    from video_creation.background import download_background, chop_background_video
  File "C:\Users\David2.LAPTOP-4COM5CAO\Desktop\RedditVideoMakerBot\video_creation\background.py", line 6, in 
<module>
    from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
  File "C:\Users\David2.LAPTOP-4COM5CAO\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_tools.py", line 7, in <module>
    from moviepy.config import get_setting
  File "C:\Users\David2.LAPTOP-4COM5CAO\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\confnfig.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "C:\Users\David2.LAPTOP-4COM5CAO\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\plugugins\ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "C:\Users\David2.LAPTOP-4COM5CAO\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio_ffmpmpeg\_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE envirironment variable.
PS C:\Users\David2.LAPTOP-4COM5CAO\Desktop\RedditVideoMakerBot>

**Comment by davidlol01** [comment]
Fixed the issue, For anyone else facing this issue, I recommend using this tutorial: https://www.youtube.com/watch?v=T0ztYcPnMsY. Make sure to download playwright
