### ISSUE TITLE
No such file or directory: 'assets/temp/mp3/title.mp3'

### ISSUE THREAD

**Issue by JustinWilker** [elebumm/RedditVideoMakerBot#671]
```
Traceback (most recent call last):
  File "C:\Users\justi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\justi\Desktop\RedditVideoMakerBot-master\main.py", line 71, in <module>
    main()
  File "D:\Users\justi\Desktop\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "D:\Users\justi\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 39, in save_text_to_mp3
    length += MP3("assets/temp/mp3/title.mp3").info.length
  File "C:\Users\justi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "C:\Users\justi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mutagen\_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Users\justi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'
```

**Comment by TJ0770** [comment]
Just had this problem - how did you go about solving it?

**Comment by Jake006thesnake** [comment]
THIS WORKED!!! aka all -- after deleting the env file and filling out the sample make sure you rename the .env template file as ".env" then run your main and everything should work!

**Comment by Deadshotv21** [comment]
I deleted the .env after filling the template in and renamed it to .env, I still have this problem please help :(

**Comment by Jake006thesnake** [comment]
> I deleted the .env after filling the template in and renamed it to .env, I still have this problem please help :(


- is it the same error? Did you have any other error messages like Sox ?

( I'll do what I can to help I'm new to code)

**Comment by josh2212** [comment]
> I deleted the .env after filling the template in and renamed it to .env, I still have this problem please help :(

me too
