### ISSUE TITLE
says client_id is missing when i have provided it

### ISSUE THREAD

**Issue by choob123** [elebumm/RedditVideoMakerBot#7]
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    reddit_object = get_askreddit_threads()
  File "/Users/prasiddhakarki/Desktop/RedditVideoMakerBot-master/reddit/askreddit.py", line 17, in get_askreddit_threads
    reddit = praw.Reddit(
  File "/Users/prasiddhakarki/Library/Python/3.8/lib/python/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/Users/prasiddhakarki/Library/Python/3.8/lib/python/site-packages/praw/reddit.py", line 258, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing. 
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.

**Comment by elebumm** [comment]
Did you rename the file to `.env` instead of `.env.template`?

**Comment by totalsoda** [comment]
Having this same issue, which text editor did you use?

**Comment by totalsoda** [comment]
> Having this same issue, which text editor did you use?

Nevermind, Get Info > Name & Extension did the trick thanks
