### ISSUE TITLE
SoX Cannot Process .mp3 files

### ISSUE THREAD

**Issue by ElusiveXGames** [elebumm/RedditVideoMakerBot#700]
I keep getting this error. SoX Cannot Process .mp3 files. Ending up with a 2nd error.

To clerify, i get differnt errors if i use the default voice settings. When changing the VOICE=Mathew i get one error. Changing it to
VOICE="en_us_001" 
TTsChoice="polly"
I get this error

`This install of SoX cannot process .mp3 files.
Traceback (most recent call last):
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\video_creation\voices.py", line 39, in save_text_to_mp3
    length += MP3("assets/temp/mp3/title.mp3").info.length
  File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\id3\_file.py", line 421, in load
    self.info = self._Info(fileobj, offset)
  File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\mp3\__init__.py", line 402, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 69, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 62, in run_many
    main()
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\video_creation\voices.py", line 41, in save_text_to_mp3
    length += sox.file_info.duration("assets/temp/mp3/title.mp3")
  File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sox\file_info.py", line 122, in duration
    output = soxi(input_filepath, 'D')
  File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sox\core.py", line 147, in soxi
    shell_output = subprocess.check_output(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by ElusiveXGames** [comment]
I have changed my config to try to use the TikTok and the GTTS voice and it still breaks with the error

Traceback (most recent call last):
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 69, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 62, in run_many
    main()
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\video_creation\voices.py", line 42, in save_text_to_mp3
    if getenv("STORYMODE").casefold() == "true":
AttributeError: 'NoneType' object has no attribute 'casefold'

**Comment by JasonLovesDoggo** [comment]
> I have changed my config to try to use the TikTok and the GTTS voice and it still breaks with the error
> 
> Traceback (most recent call last):
>   File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 69, in <module>
>     run_many(int(getenv("TIMES_TO_RUN")))
>   File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 62, in run_many
>     main()
>   File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 49, in main
>     length, number_of_comments = save_text_to_mp3(reddit_object)
>   File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\video_creation\voices.py", line 42, in save_text_to_mp3
>     if getenv("STORYMODE").casefold() == "true":
> AttributeError: 'NoneType' object has no attribute 'casefold'

Guess how you fix that by putting an attribute for story mode

**Comment by JasonLovesDoggo** [comment]
> I keep getting this error. SoX Cannot Process .mp3 files. Ending up with a 2nd error.
> 
> To clerify, i get differnt errors if i use the default voice settings. When changing the VOICE=Mathew i get one error. Changing it to
> VOICE="en_us_001" 
> TTsChoice="polly"
> I get this error
> 
> `This install of SoX cannot process .mp3 files.
> Traceback (most recent call last):
>   File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\video_creation\voices.py", line 39, in save_text_to_mp3
>     length += MP3("assets/temp/mp3/title.mp3").info.length
>   File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\_file.py", line 48, in __init__
>     self.load(*args, **kwargs)
>   File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\_util.py", line 156, in wrapper
>     return func(self, h, *args, **kwargs)
>   File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\id3\_file.py", line 421, in load
>     self.info = self._Info(fileobj, offset)
>   File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\_util.py", line 185, in wrapper
>     return func(*args, **kwargs)
>   File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mutagen\mp3\__init__.py", line 402, in __init__
>     raise HeaderNotFoundError("can't sync to MPEG frame")
> mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 69, in <module>
>     run_many(int(getenv("TIMES_TO_RUN")))
>   File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 62, in run_many
>     main()
>   File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 49, in main
>     length, number_of_comments = save_text_to_mp3(reddit_object)
>   File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\video_creation\voices.py", line 41, in save_text_to_mp3
>     length += sox.file_info.duration("assets/temp/mp3/title.mp3")
>   File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sox\file_info.py", line 122, in duration
>     output = soxi(input_filepath, 'D')
>   File "C:\Users\19709\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sox\core.py", line 147, in soxi
>     shell_output = subprocess.check_output(
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 420, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified`

Try adding sox Google how to

**Comment by ElusiveXGames** [comment]
@JasonLovesDoggo I have SOX Installed. I even re-installed it

**Comment by CJthisis** [comment]
1. Go to advanced system settings
2. Go to system variables
3. Find the 'PATH' variable
4. Click on Edit
5. Add the path where sox is installed 
    a) If you installed sox via 'pip install sox', search for a folder called 'sox'
    b) If you have it installed via sourcefourge, it is in C:\Program Files (x86)\sox-14-4-2 (assuming you havent changed the destination on installation)
6. Move the sox path all the way to the top of the list of entries in the 'PATH' variable.
Hope that helps!
(If you get an error, I would advise you to search for solved issues on github which mention the same error)

**Comment by ElusiveXGames** [comment]
Traceback (most recent call last):
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 69, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 62, in run_many
    main()
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\19709\Desktop\VidBot\RedditVideoMakerBot-2.1\video_creation\voices.py", line 42, in save_text_to_mp3
    if getenv("STORYMODE").casefold() == "true":
AttributeError: 'NoneType' object has no attribute 'casefold'


I have fixed the PATH issue now i get this

**Comment by JasonLovesDoggo** [comment]
Set a value to story mode in the .env file
