### ISSUE TITLE
Error when attempting to create videos

### ISSUE THREAD

**Issue by MiloMikoreyBarber** [elebumm/RedditVideoMakerBot#709]
**Describe the bug**
Worked fine, but on this one specific Reddit thread (What is something that tastes good both hot and cold?)  it doesnt work (tried the same one multiple times).
I get an error while saving Text to MP3 files...

**To Reproduce**
Run python main.py
Wait until saving Text to MP3 files.
Error message

**Expected behavior**
Create the video properly

**Screenshots**
No screenshot, but error code:
`Traceback (most recent call last):
  File "main.py", line 69, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "main.py", line 62, in run_many
    main()
  File "main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/media/milomb/HDD/Milo/Reddit Bot/RedditVideoMakerBot-2.1/video_creation/voices.py", line 56, in save_text_to_mp3
    TextToSpeech.tts(
  File "/media/milomb/HDD/Milo/Reddit Bot/RedditVideoMakerBot-2.1/TTS/POLLY.py", line 57, in tts
    voice_data = requests.get(response.json()["speak_url"])
  File "/home/milomb/anaconda3/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/milomb/anaconda3/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/milomb/anaconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/milomb/anaconda3/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**System (please complete the following information):**
 - Device: PC
 - OS: Ubuntu Pop! OS
 - App version Latest

**Additional context**

**Comment by lamasterso** [comment]
what are you putting in the post id ?

**Comment by MiloMikoreyBarber** [comment]
Nothing, I set it to random thread. It's just coincidental that I keep getting this one.

**Comment by JasonLovesDoggo** [comment]
Fixed in the latest version of develop
