### ISSUE TITLE
401 http

### ISSUE THREAD

**Issue by xaevlc** [elebumm/RedditVideoMakerBot#711]
when ran, outputs this.

Logging into Reddit.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Getting subreddit threads...                                                                                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Using subreddit: r/AskReddit from environment variable config
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Desktop\RedditVideoMakerBot-master\main.py", line 71, in <module>
    main()
  File "C:\Users\Admin\Desktop\Desktop\RedditVideoMakerBot-master\main.py", line 48, in main
    reddit_object = get_obj()
  File "C:\Users\Admin\Desktop\Desktop\RedditVideoMakerBot-master\main.py", line 45, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\Admin\Desktop\Desktop\RedditVideoMakerBot-master\reddit\subreddit.py", line 74, in get_subreddit_threads
    submission = get_subreddit_undone(threads, subreddit)
  File "C:\Users\Admin\Desktop\Desktop\RedditVideoMakerBot-master\utils\subreddit.py", line 13, in get_subreddit_undone
    for submission in submissions:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 373, in refresh
    self._request_token(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

**Comment by xaevlc** [comment]
fixed via closed issues
