### ISSUE TITLE
How to make the script skip a sketchy thread?

### ISSUE THREAD

**Issue by tayzuz** [elebumm/RedditVideoMakerBot#715]
Having a lot of trouble with the same particular thread. Just want to make the script skip it so it can make videos.

Here's the error message I get for that thread if anyone's curious:
Traceback (most recent call last):
  File "C:\Users\yanni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yanni\RedditVideoMakerBot-master\main.py", line 69, in <module>        
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\yanni\RedditVideoMakerBot-master\main.py", line 62, in run_many        
    main()
  File "C:\Users\yanni\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\yanni\RedditVideoMakerBot-master\video_creation\voices.py", line 56, in save_text_to_mp3
    TextToSpeech.tts(
  File "C:\Users\yanni\RedditVideoMakerBot-master\TTS\POLLY.py", line 61, in tts        
    if response.json()["error"] == "Text length is too long!":
  File "C:\Users\yanni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

**Comment by JasonLovesDoggo** [comment]
That error was fixed in latest version of develop
You can bypass the thread finally adding it to the videos.json file

**Comment by tayzuz** [comment]
> That error was fixed in latest version of develop You can bypass the thread finally adding it to the videos.json file

I actually saw that in the closed tab just a couple of minutes ago. Could you explain what I have to add to the file? The title or the ID of the post?

**Comment by JasonLovesDoggo** [comment]
Look at ones the other additions in that file and then copy and paste it with a changed ID
