### ISSUE TITLE
Met with error when running main.py

### ISSUE THREAD

**Issue by amrpowershot** [elebumm/RedditVideoMakerBot#717]
**Describe the bug**
Met with error when running main,py on latest push.

**To Reproduce**
Unknown

**Expected behavior**
Video is created and saved successfully

**Screenshots**

**System (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - App version: Master/Latest push
 - 
Error:
Traceback (most recent call last):
  File "C:\Users\wards\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main()
  File "main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\wards\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 39, in save_text_to_mp3
    length += MP3("assets/temp/mp3/title.mp3").info.length
  File "C:\Users\wards\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "C:\Users\wards\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\mutagen\_util.py", line 155, in wrapper
    writable, create) as h:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\wards\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

**Comment by sarimwaniR** [comment]
close this also

**Comment by amrpowershot** [comment]
why

**Comment by JasonLovesDoggo** [comment]
#718
