### ISSUE TITLE
Moviepy and FFMPEG: b"Unrecognized option 'preset'.\nError splitting the argument list: Option not found\n"

### ISSUE THREAD

**Issue by BradTFT** [elebumm/RedditVideoMakerBot#727]
Full error:
(when running main.py)

```
[15:20:58]  Video Will Be: 41 Seconds Long                                 final_video.py:53
Moviepy - Building video assets/temp/temp.mp4.
MoviePy - Writing audio in tempTEMP_MPY_wvf_snd.mp4
MoviePy - Done.                                                                             
Moviepy - Writing video assets/temp/temp.mp4

t:   0%|                                                 | 0/1231 [00:00<?, ?it/s, now=None]Traceback (most recent call last):
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_writer.py", line 136, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/BradTFT/fork/RedditVideoMakerBot/main.py", line 71, in <module>
    main()
  File "/home/BradTFT/fork/RedditVideoMakerBot/main.py", line 53, in main
    make_final_video(number_of_comments, length)
  File "/home/BradTFT/fork/RedditVideoMakerBot/video_creation/final_video.py", line 137, in make_final_video
    final.write_videofile("assets/temp/temp.mp4", fps=30, audio_codec="aac", audio_bitrate="192k")
  File "<decorator-gen-55>", line 2, in write_videofile
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_writer.py", line 228, in ffmpeg_write_video
    writer.write_frame(frame)
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_writer.py", line 180, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file assets/temp/temp.mp4:

 b"Unrecognized option 'preset'.\nError splitting the argument list: Option not found\n"
```

**To Reproduce**
have not found a way to reproduce. on DEB10 Buster

**Screenshots**

**System (please complete the following information):**
 - Device: Chromebook (shut up ik its not the best system to code on)
 -  System OS: ChromeOS Version 101.0.4951.72 (Official Build) (32-bit)
 - Linux OS: Debain 10 Buster
 

**Additional context**
tried recloning, reinstalling all packages, and deleted all files (pertainting to this project) and reinstalled them. I am inside of a venv using `$ python3.9 -m venv venv` and `$ source venv/bin/activate` lines

EDIT: fixed spelling errors

**Comment by CallumIO** [comment]
Do you know what version of FFMPEG is installed? Could be a build that is older than the one moviepy supports

**Comment by BradTFT** [comment]
when running `$ ffmpeg -V`:
```
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: 
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
Unrecognized option 'V'.
Error splitting the argument list: Option not found
```
i installed via FFmpeg 5.0.1 "Lorentz" bzip2 tarball

**Comment by CallumIO** [comment]
Try compile ffmpeg from source rather than (i assume you used) apt. Make sure you compile with `--enable-nonfree --enable-libfaac` and `--enable-gpl --enable-libx264`

**Comment by BradTFT** [comment]
how do i do that?

**Comment by CallumIO** [comment]
https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

I assume you use apt which means you will likely only have to install each lib, and then compile rather than compiling the toolchain.

**Comment by BradTFT** [comment]
so install from the link?

**Comment by CallumIO** [comment]
Follow the guide

**Comment by BradTFT** [comment]
ok i think its all set. im gonna re run main.py

**Comment by BradTFT** [comment]
got this error now:


```
Traceback (most recent call last):
  File "/home/BradTFT/fork/RedditVideoMakerBot/main.py", line 71, in <module>
    main()
  File "/home/BradTFT/fork/RedditVideoMakerBot/main.py", line 53, in main
    make_final_video(number_of_comments, length)
  File "/home/BradTFT/fork/RedditVideoMakerBot/video_creation/final_video.py", line 34, in make_final_video
    VideoFileClip("assets/temp/background.mp4")
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/io/VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "/home/BradTFT/fork/RedditVideoMakerBot/venv/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
```

**Comment by BradTFT** [comment]
hold on im gonna fully uninstall ffmpeg and restart. also do i have to run every single command on the guide or just the dependances and the ones under the **FFMPEG** tag?

**Comment by BradTFT** [comment]
ok so i completely uninstalled it and im gonna re install it from the provided link

**Comment by BradTFT** [comment]
just spent an hour running all the compilations and it doesnt recognize i have it on my system.. what now

**Comment by BradTFT** [comment]
all my files got deleted when a backup failed and this works now for some reason :shrug:
