### ISSUE TITLE
Text too long bug

### ISSUE THREAD

**Issue by Crisez0694** [elebumm/RedditVideoMakerBot#730]
Code was working fine until randomly it'll give me an error saying text too long, haven't been able to fix this issue yet and not sure what could be causing.

 I've already checked all the files and there's nothing I can tell to be wrong, I've changed the allowed text length and no matter what amount I put it'll give the same error, I also deleted the folder and uninstalled all of the pip applications then reinstalled it, which did fix it for about 2 tries then it stopped working giving the same error again.

Not sure how to fix if anyone knows what i could try or if they have a solution that'd be great

Here's the code to the error message: 

Traceback (most recent call last):
  File "C:\Users\Crist\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Crist\Desktop\RedditVideoMakerBot-master\main.py", line 71, in <module>
    main()
  File "C:\Users\Crist\Desktop\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Crist\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 56, in save_text_to_mp3
    TextToSpeech.tts(
  File "C:\Users\Crist\Desktop\RedditVideoMakerBot-master\TTS\POLLY.py", line 61, in tts
    if response.json()["error"] == "Text length is too long!":
  File "C:\Users\Crist\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

![Capture](https://user-images.githubusercontent.com/37914330/176067035-f6f5f67e-7de7-4a1f-852c-a619bead2057.PNG)

**Comment by Clumsy0420** [comment]
Hey, I'm having the same issue which post is it crashing on? Because mine was working fine until a certain post

**Comment by Crisez0694** [comment]
> Hey, I'm having the same issue which post is it crashing on? Because mine was working fine until a certain post



> Same for me ! It seems that the post is a video


Thanks ill be checking that it sounds very possible

**Comment by Tisboom** [comment]
It worked with a photo

**Comment by Cizzl** [comment]
Fixed in develop
