### ISSUE TITLE
Python Was Not Found Run Without Arguments to Install From the Microsoft Store Error

### ISSUE THREAD

**Issue by RennieSs** [elebumm/RedditVideoMakerBot#75]
Hi! After i did `python3 main.py` it said "Python Was Not Found Run Without Arguments to Install From the Microsoft Store Error"

I found some random giud on the internet where i changed the path in the controlpanel, but didnt help..

How do i fix this?

**Comment by MIFD670** [comment]
Okay, its a issue with the windows path.
Check your Python version and be sure it is installed on your machine
Check the path environment variable
Go to -> "start" and type "Manage App Execution Aliases". Go to it and turn off "Python"

**Comment by RennieSs** [comment]
Okay i think it worked, but now there is a new problem. After typing the python3 main.py command it says this "'python3' is not recognized as an internal or external command,
operable program or batch file."

**Comment by RennieSs** [comment]
So i downlaoded Python from microsoft store, and got this in stead "ModuleNotFoundError: No module named 'rich'"

**Comment by lesterrar** [comment]
type python main.py instead of python3 main.py

**Comment by Strong10mede** [comment]
> Hi! After i did `python3 main.py` it said "Python Was Not Found Run Without Arguments to Install From the Microsoft Store Error"
> 
> I found some random giud on the internet where i changed the path in the controlpanel, but didnt help..
> 
> How do i fix this?

If you have install python 3 or above version in your PC then just rename your python.exe file to python3.exe.
To check version of python : py --version in command prompt
After renaming the python.exe file type : py3 --version in command prompt

**Comment by RennieSs** [comment]
> type python main.py instead of python3 main.py

After i did this it says "thanks for using this tool" etc. But then it says all this

"Traceback (most recent call last):
  File "F:\Reddit Vids\RedditVideoMakerBot-master\main.py", line 16, in <module>
    reddit_object = get_askreddit_threads()
  File "F:\Reddit Vids\RedditVideoMakerBot-master\reddit\askreddit.py", line 26, in get_askreddit_threads
    submission = list(threads)[random.randrange(0, 25)]
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response"

**Comment by RennieSs** [comment]
And do fix yet?-

**Comment by RennieSs** [comment]
Feel free to tell if the problem gets fixed!
