### ISSUE TITLE
Crashes On Launch

### ISSUE THREAD

**Issue by Snipessys** [elebumm/RedditVideoMakerBot#752]
Traceback (most recent call last):
  File "C:\Users\Devan\Downloads\RedditVideoMakerBot-2.1\RedditVideoMakerBot-2.1\main.py", line 13, in <module>
    from video_creation.voices import save_text_to_mp3
  File "C:\Users\Devan\Downloads\RedditVideoMakerBot-2.1\RedditVideoMakerBot-2.1\video_creation\voices.py", line 11, in <module>
    from TTS.swapper import TTS
  File "C:\Users\Devan\Downloads\RedditVideoMakerBot-2.1\RedditVideoMakerBot-2.1\TTS\swapper.py", line 6, in <module>
    from TTS.POLLY import POLLY
  File "C:\Users\Devan\Downloads\RedditVideoMakerBot-2.1\RedditVideoMakerBot-2.1\TTS\POLLY.py", line 9, in <module>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (C:\Users\Devan\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\exceptions.py)

**Comment by JasonLovesDoggo** [comment]
download newer version of requests
