### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by TylerL0216** [elebumm/RedditVideoMakerBot#763]
I get this error when running python3 main.py

Traceback (most recent call last):
  File "/Users/tylerleach/Desktop/RedditVideoMakerBot-master/main.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by Cizzl** [comment]
Please follow the instructions. 
pip install -r requirements.txt

**Comment by TylerL0216** [comment]
Traceback (most recent call last):
  File "/Users/tylerleach/Desktop/RedditVideoMakerBot-master/main.py", line 10, in <module>
    from video_creation.background import download_background, chop_background_video
  File "/Users/tylerleach/Desktop/RedditVideoMakerBot-master/video_creation/background.py", line 6, in <module>
    from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_tools.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/opt/homebrew/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/opt/homebrew/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

I get this now

**Comment by JasonLovesDoggo** [comment]
Add FFmpeg to path

**Comment by TylerL0216** [comment]
> 

can you ellaborate

**Comment by Cizzl** [comment]
@TylerL0216 https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/installing-sox#adding-sox-to-path

**Comment by TylerL0216** [comment]
I have Sox and Playwrite installed and get this error:

Traceback (most recent call last):
  File "/Users/tylerleach/Desktop/RedditVideoMakerBot-master/main.py", line 10, in <module>
    from video_creation.background import download_background, chop_background_video
  File "/Users/tylerleach/Desktop/RedditVideoMakerBot-master/video_creation/background.py", line 6, in <module>
    from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_tools.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/opt/homebrew/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/opt/homebrew/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/opt/homebrew/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

**Comment by JasonLovesDoggo** [comment]
> I have Sox and Playwrite installed and get this error:
> 
> Traceback (most recent call last):
>   File "/Users/tylerleach/Desktop/RedditVideoMakerBot-master/main.py", line 10, in <module>
>     from video_creation.background import download_background, chop_background_video
>   File "/Users/tylerleach/Desktop/RedditVideoMakerBot-master/video_creation/background.py", line 6, in <module>
>     from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
>   File "/opt/homebrew/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_tools.py", line 7, in <module>
>     from moviepy.config import get_setting
>   File "/opt/homebrew/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module>
>     FFMPEG_BINARY = get_exe()
>   File "/opt/homebrew/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 159, in get_exe
>     return imageio_ffmpeg.get_ffmpeg_exe()
>   File "/opt/homebrew/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 49, in get_ffmpeg_exe
>     raise RuntimeError(
> RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

YOU NEED TO ADD FFMPEG TO PATH. https://superuser.com/questions/624561/install-ffmpeg-on-os-x
