### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pogues2K** [elebumm/RedditVideoMakerBot#772]
I'm getting this error, anyone know how to fix it?

`Traceback (most recent call last):
  File "C:\Users\jallo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\jallo\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\jallo\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\jallo\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jallo\Desktop\redditbotvideomaker\main.py", line 69, in <module>
    main()
  File "C:\Users\jallo\Desktop\redditbotvideomaker\main.py", line 47, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\jallo\Desktop\redditbotvideomaker\video_creation\voices.py", line 56, in save_text_to_mp3
    TextToSpeech.tts(
  File "C:\Users\jallo\Desktop\redditbotvideomaker\TTS\POLLY.py", line 61, in tts
    if response.json()["error"] == "Text length is too long!":
  File "C:\Users\jallo\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Cizzl** [comment]
Text too long > fixed in develop

**Comment by Cizzl** [comment]
Normally you can try it again, then it might pick another post

**Comment by NHastings2** [comment]
Hi @Pogues2K, Recently the creator of the TTS site added a rate limit to the AWS server. After about 20 request, there is a 60 second wait before you can submit more requests. I'm currently working on a patch that will add a wait when the rate is reached so that longer comment threads can be reached.

**Comment by SADMANanuvob9** [comment]
so is there a solution for this fix ??
