### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by anon1800** [elebumm/RedditVideoMakerBot#784]
I deleted everything and installed it again and after this it works only the first time it runs, after the first time this error pops up when it creates the mp3 files. 

**Error**
Traceback (most recent call last):
  File "C:\Users\chari\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\chari\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\chari\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\chari\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\RedditVideoMakerBot-master\main.py", line 71, in <module>
    main()
  File "C:\RedditVideoMakerBot-master\main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\RedditVideoMakerBot-master\video_creation\voices.py", line 56, in save_text_to_mp3
    TextToSpeech.tts(
  File "C:\RedditVideoMakerBot-master\TTS\POLLY.py", line 61, in tts
    if response.json()["error"] == "Text length is too long!":
  File "C:\Users\chari\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**System**
 - Device: PC
 - OS: Windows 10
 - App version 2.1

**Comment by JasonLovesDoggo** [comment]
Fixed in develop
