### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by MacuKaku** [elebumm/RedditVideoMakerBot#809]
Traceback (most recent call last):
  File "C:\Users\***\Downloads\RedditVideoMakerBot-master (1)\RedditVideoMakerBot-master\main.py", line 54, in <module>
    if check_env() is not True:
  File "C:\Users\***\Downloads\RedditVideoMakerBot-master (1)\RedditVideoMakerBot-master\utils\checker.py", line 78, in check_env
    len(bounds[env]) > 1 and bounds[env][1] >= len(value)
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by Ohmnito** [comment]
Did you correctly complete the .env file?
especially these fields:

REDDIT_CLIENT_ID
REDDIT_CLIENT_SECRET
REDDIT_USERNAME
REDDIT_PASSWORD

**Comment by CordlessCoder** [comment]
I'll fix it in ~12 hours

**Comment by JasonLovesDoggo** [comment]
@CordlessCoder If you fixed it close this
