### ISSUE TITLE
Cant make it work 

### ISSUE THREAD

**Issue by SpRoXx** [elebumm/RedditVideoMakerBot#813]
`Traceback (most recent call last):
  File "C:\Users\Fish9317\Desktop\Red\main.py", line 59, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\Fish9317\Desktop\Red\main.py", line 49, in run_many
    main()
  File "C:\Users\Fish9317\Desktop\Red\main.py", line 41, in main
    make_final_video(number_of_comments, length, reddit_object)
  File "C:\Users\Fish9317\Desktop\Red\video_creation\final_video.py", line 47, in make_final_video
    audio_clips = [AudioFileClip(f"assets/mp3/{i}.mp3") for i in range(number_of_clips)]
  File "C:\Users\Fish9317\Desktop\Red\video_creation\final_video.py", line 47, in <listcomp>
    audio_clips = [AudioFileClip(f"assets/mp3/{i}.mp3") for i in range(number_of_clips)]
  File "C:\Users\Fish9317\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "C:\Users\Fish9317\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\audio\io\readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "C:\Users\Fish9317\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file assets/mp3/0.mp3 could not be found!
Please check that you entered the correct path.`
it happens to me when its creating the final video

**Comment by vitviki** [comment]
Hey,

It seems like the paths you are passing are bit incorrect. All mp3 and png files are under assets/**temp**/mp3 and assets/**temp**/png.
Here it says assets/mp3/0.mp3 which is an incorrect path. You can add "temp" in between and it should work.
