### ISSUE TITLE
Showing some error

### ISSUE THREAD

**Issue by AnD418** [elebumm/RedditVideoMakerBot#818]
Traceback (most recent call last):
  File "/home/and/.local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main()
  File "main.py", line 49, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/home/and/RedditVideoMakerBot/video_creation/voices.py", line 56, in save_text_to_mp3
    TextToSpeech.tts(
  File "/home/and/RedditVideoMakerBot/TTS/POLLY.py", line 61, in tts
    if response.json()["error"] == "Text length is too long!":
  File "/home/and/.local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
![Screenshot_20220703-072605~2](https://user-images.githubusercontent.com/69518879/177021481-8eb3eb12-2e08-43b6-8331-d8301aba9398.png)

**Comment by AnD418** [comment]
Don't know how but it started working. Thanks for the bot
