### ISSUE TITLE
  File "main.py", line 38     f'on the {x}{("st" if x == 1 else ("nd" if x == 2 else ("rd" if x == 3 else "th")))} iteration of {times}' error

### ISSUE THREAD

**Issue by CodingBreadd** [elebumm/RedditVideoMakerBot#827]
**Describe the bug**
Whenever i try to run the code, it gives me an error like this:

  File "main.py", line 38
    f'on the {x}{("st" if x == 1 else ("nd" if x == 2 else ("rd" if x == 3 else "th")))} iteration of {times}'
                                                                                                             ^
SyntaxError: invalid syntax

**Screenshots**
![Captură de ecran din 2022-07-03 la 18 24 20](https://user-images.githubusercontent.com/108622594/177046364-7554eb2d-86a1-4a35-941a-33fbe2b30e73.png)

**System (please complete the following information):**

- Python Version: 3.10
- OS: Mac OS Catalina
- App version / Branch: Latest

**Comment by JasonLovesDoggo** [comment]
If you want it to work just delete line 37 to 39
I don't know why it doesn't work though because I have 3.10 and it works perfectly fine for me

**Comment by B1GJ** [comment]
Are u sure you're running it with python3? 
Because that's a typical error to get when you try to run a python3 script with python2.
run `python --version` to make sure you're running the correct version since just running python might default to python2.

**Comment by micziz** [comment]
There is no way to upgrade python to the latest version on macos. BUT! You can use python3 and it should use the latest version.

**Comment by B1GJ** [comment]
> 

Don't forget to install all the packages again
`pip3 install -r requirements.txt`

**Comment by CodingBreadd** [comment]
Didn't work. It still gives me the same error.

**Comment by B1GJ** [comment]
Ah just noticed sox is not in the requirements.txt file, should be fixed soon.
Just try `pip3 install sox` then

**Comment by micziz** [comment]
Or, if it does not work, install sox using

```
brew install sox
```

**Comment by CodingBreadd** [comment]
It is running some of the code now, but when i need to choose the tts it gives me this error:

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Please choose one of the following TTS providers:                                                                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────╮ ╭──────────╮ ╭─────────────────╮ ╭────────╮
│ GoogleTranslate │ │ AWSPolly │ │ StreamlabsPolly │ │ TikTok │
╰─────────────────╯ ╰──────────╯ ╰─────────────────╯ ╰────────╯

StreamlabsPolly
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mutagen/_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Claudia/Desktop/Reddit/RedditVideoMakerBot-2.2.2 2/TTS/engine_wrapper.py", line 98, in call_tts
    self.length += MP3(f"{self.path}/{filename}.mp3").info.length
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mutagen/_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/mutagen/_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Claudia/Desktop/Reddit/RedditVideoMakerBot-2.2.2 2/main.py", line 70, in <module>
    main()
  File "/Users/Claudia/Desktop/Reddit/RedditVideoMakerBot-2.2.2 2/main.py", line 37, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/Users/Claudia/Desktop/Reddit/RedditVideoMakerBot-2.2.2 2/video_creation/voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "/Users/Claudia/Desktop/Reddit/RedditVideoMakerBot-2.2.2 2/TTS/engine_wrapper.py", line 58, in run
    self.call_tts("title", self.reddit_object["thread_title"])
  File "/Users/Claudia/Desktop/Reddit/RedditVideoMakerBot-2.2.2 2/TTS/engine_wrapper.py", line 100, in call_tts
    self.length += sox.file_info.duration(f"{self.path}/{filename}.mp3")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sox/file_info.py", line 121, in duration
    validate_input_file(input_filepath)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sox/file_info.py", line 248, in validate_input_file
    raise IOError(
OSError: input_filepath assets/temp/mp3/title.mp3 does not exist.

**Comment by B1GJ** [comment]
Yeah thats an issue with wrong .env variables that still need to get pulled
You can see the fix for it here https://github.com/elebumm/RedditVideoMakerBot/pull/836
