### ISSUE TITLE
prawcore.exceptions.ResponseException: received 401 HTTP response

### ISSUE THREAD

**Issue by TakeoverGamer** [elebumm/RedditVideoMakerBot#829]
**Describe the bug**
Tried to install and run the script, but I keep receiving " prawcore.exceptions.ResponseException: received 401 HTTP response "

**To Reproduce**
Not sure 

**Expected behavior**
A video to be produced

**Screenshots**

**System (please complete the following information):**

- Python Version: 3.10
- OS: Windows 11
- App version / Branch V2.2.1

**Additional context**

**Comment by TakeoverGamer** [comment]
#!/usr/bin/env python
from gettext import install
from subprocess import Popen
from os import getenv, name
from dotenv import load_dotenv
from reddit.subreddit import get_subreddit_threads
from utils.cleanup import cleanup
from utils.console import print_markdown, print_step
from utils.checker import check_env

# from utils.checker import envUpdate
from video_creation.background import download_background, chop_background_video
from video_creation.final_video import make_final_video
from video_creation.screenshot_downloader import download_screenshots_of_reddit_posts
from video_creation.voices import save_text_to_mp3

VERSION = "2.2.1"
print(
    """
██████╗ ███████╗██████╗ ██████╗ ██╗████████╗    ██╗   ██╗██╗██████╗ ███████╗ ██████╗     ███╗   ███╗ █████╗ ██╗  ██╗███████╗██████╗
██╔══██╗██╔════╝██╔══██╗██╔══██╗██║╚══██╔══╝    ██║   ██║██║██╔══██╗██╔════╝██╔═══██╗    ████╗ ████║██╔══██╗██║ ██╔╝██╔════╝██╔══██╗
██████╔╝█████╗  ██║  ██║██║  ██║██║   ██║       ██║   ██║██║██║  ██║█████╗  ██║   ██║    ██╔████╔██║███████║█████╔╝ █████╗  ██████╔╝
██╔══██╗██╔══╝  ██║  ██║██║  ██║██║   ██║       ╚██╗ ██╔╝██║██║  ██║██╔══╝  ██║   ██║    ██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝  ██╔══██╗
██║  ██║███████╗██████╔╝██████╔╝██║   ██║        ╚████╔╝ ██║██████╔╝███████╗╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═════╝ ╚═╝   ╚═╝         ╚═══╝  ╚═╝╚═════╝ ╚══════╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
"""
)
# Modified by JasonLovesDoggo
print_markdown(
    "### Thanks for using this tool! [Feel free to contribute to this project on GitHub!](https://lewismenelaws.com) If you have any questions, feel free to reach out to me on Twitter or submit a GitHub issue. You can find solutions to many common problems in the [Documentation](https://luka-hietala.gitbook.io/documentation-for-the-reddit-bot/)"
)
print_step(f"You are using V{VERSION} of the bot")

def main(POST_ID=None):
    cleanup()
    reddit_object = get_subreddit_threads(POST_ID)
    length, number_of_comments = save_text_to_mp3(reddit_object)
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
    download_background()
    chop_background_video(length)
    make_final_video(number_of_comments, length, reddit_object)


def run_many(times):
    for x in range(1, times + 1):
        print_step(
            f'on the {x}{("st" if x == 1 else ("nd" if x == 2 else ("rd" if x == 3 else "th")))} iteration of {times}'
        )  # correct 1st 2nd 3rd 4th 5th....
        main()
        Popen("cls" if name == "nt" else "clear", shell=True).wait()

import praw
from prawcore.exceptions import ResponseException
reddit = praw.Reddit(
    username="wrong_username",
    password="wrong password",
    client_id="bad client ID",
    client_secret="bad secret",
    user_agent="failing authentication",
)
try:
    print("Authenticated as {}".format(reddit.user.me()))
except ResponseException:
    print("Something went wrong during authentication")

if __name__ == "__main__":
    if check_env() is not True:
        exit()
    load_dotenv()
    try:
        if getenv("TIMES_TO_RUN") and isinstance(int(getenv("TIMES_TO_RUN")), int):
            run_many(int(getenv("TIMES_TO_RUN")))

        elif len(getenv("POST_ID", "").split("+")) > 1:
            for index, post_id in enumerate(getenv("POST_ID", "").split("+")):
                index += 1
                print_step(
                    f'on the {index}{("st" if index == 1 else ("nd" if index == 2 else ("rd" if index == 3 else "th")))} post of {len(getenv("POST_ID", "").split("+"))}'
                )
                main(post_id)
                Popen("cls" if name == "nt" else "clear", shell=True).wait()
        else:
            main()
    except KeyboardInterrupt:
        print_markdown("## Clearing temp files")
        cleanup()
        exit()

**Comment by TakeoverGamer** [comment]
![Untitled](https://user-images.githubusercontent.com/64086332/177046849-8ecd9e4e-574b-4c99-b701-a1224114e93d.png)

**Comment by TakeoverGamer** [comment]
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ You are using V2.2.1 of the bot                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Something went wrong during authentication
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ on the 1st iteration of 1                                                                                           │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Logging into Reddit.
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Getting subreddit threads...                                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Using subreddit: r/meirl from environment variable config
Traceback (most recent call last):
  File "C:\Users\myname\Documents\RedditVideoMakerBot-master\main.py", line 72, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\myname\Documents\RedditVideoMakerBot-master\main.py", line 49, in run_many
    main()
  File "C:\Users\myname\Documents\RedditVideoMakerBot-master\main.py", line 36, in main
    reddit_object = get_subreddit_threads(POST_ID)
  File "C:\Users\myname\Documents\RedditVideoMakerBot-master\reddit\subreddit.py", line 69, in get_subreddit_threads
    submission = get_subreddit_undone(threads, subreddit)
  File "C:\Users\myname\Documents\RedditVideoMakerBot-master\utils\subreddit.py", line 20, in get_subreddit_undone
    for submission in submissions:
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 373, in refresh
    self._request_token(
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\myname\AppData\Local\Programs\Python\Python310\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

**Comment by JasonLovesDoggo** [comment]
You have invalid credentials
Double and triple check them
