### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by TbWalllstreet** [elebumm/RedditVideoMakerBot#845]
Traceback (most recent call last):
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\main.py", line 70, in <module>
    main()
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\main.py", line 36, in main
    reddit_object = get_subreddit_threads(POST_ID)
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\reddit\subreddit.py", line 73, in get_subreddit_threads
    upvotes = submission.score
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\venv\lib\site-packages\praw\models\reddit\base.py", line 34, in __getattr__
    self._fetch()
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\venv\lib\site-packages\praw\models\reddit\submission.py", line 632, in _fetch
    data = self._fetch_data()
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\venv\lib\site-packages\praw\models\reddit\submission.py", line 629, in _fetch_data
    return self._reddit.request(method="GET", params=params, path=path)
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\venv\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\venv\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\venv\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "C:\Users\timon\Desktop\RedditVideoMakerBot-master\venv\lib\site-packages\prawcore\sessions.py", line 266, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.NotFound: received 404 HTTP response

I'm using Pycharm and a Windows 10 Computer.

**Comment by JasonLovesDoggo** [comment]
You have wrong credentials
Double check them
