### ISSUE TITLE
Polly Text length is too long

### ISSUE THREAD

**Issue by LinkBetweenWorlds** [elebumm/RedditVideoMakerBot#849]
Whenever I run the code after a few runs it sends the error "Text length is too long". I'm not sure how to stop it from happening.

.env file(not including login details)
REDDIT_2FA="no"
THEME="dark"
SUBREDDIT="AskReddit"
OPACITY=0.8
ALLOW_NSFW="false"
VOICE="Matthew"
TTsChoice="polly"
STORYMODE="false"
MAX_COMMENT_LENGTH="200"
COMMENT_LENGTH_RANGE="200,500"
TIMES_TO_RUN="5"

Traceback (most recent call last):
  File "main.py", line 67, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "main.py", line 60, in run_many
    main()
  File "main.py", line 47, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "E:\Video\RedditVideoMakerBot\video_creation\voices.py", line 36, in save_text_to_mp3
    random_speaker=False,
  File "E:\Video\RedditVideoMakerBot\TTS\POLLY.py", line 61, in tts
    if response.json()["error"] == "Text length is too long!":
  File "C:\Users\willi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 976, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by JasonLovesDoggo** [comment]
fixed.
