### ISSUE TITLE
it saves as multiple mp3 clips and no png, any help?

### ISSUE THREAD

**Issue by Yeetnms** [elebumm/RedditVideoMakerBot#86]

**Comment by elebumm** [comment]
It generates the mp3's before grabbing the png's so it might just be crashing. Does it provide any error?

**Comment by Yeetnms** [comment]
> It generates the mp3's before grabbing the png's so it might just be crashing. Does it provide any error?

Launching Headless Browser...
Traceback (most recent call last):
  File "C:\Users\nicky\OneDrive\Desktop\RedditVideoMakerBot-master\main.py", line 19, in <module>
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\nicky\OneDrive\Desktop\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 22, in download_screenshots_of_reddit_posts
    browser = p.chromium.launch()
  File "C:\Users\nicky\AppData\Roaming\Python\Python310\site-packages\playwright\sync_api\_generated.py", line 11538, in launch
    self._sync(
  File "C:\Users\nicky\AppData\Roaming\Python\Python310\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync    return task.result()
  File "C:\Users\nicky\AppData\Roaming\Python\Python310\site-packages\playwright\_impl\_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\nicky\AppData\Roaming\Python\Python310\site-packages\playwright\_impl\_connection.py", line 39, in send    return await self.inner_send(method, params, False)
  File "C:\Users\nicky\AppData\Roaming\Python\Python310\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\nicky\AppData\Local\ms-playwright\chromium-1005\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

**Comment by FreebieII** [comment]
Hi @Yeetnms,

I hope you were able to resolve your issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
