### ISSUE TITLE
client id issue

### ISSUE THREAD

**Issue by twannieboyy** [elebumm/RedditVideoMakerBot#87]
after doing: python main.py i get this error message

Traceback (most recent call last):
  File "C:\Users\twann\OneDrive\Bureaublad\RedditVideoMakerBot-master\main.py", line 16, in <module>
    reddit_object = get_askreddit_threads()
  File "C:\Users\twann\OneDrive\Bureaublad\RedditVideoMakerBot-master\reddit\askreddit.py", line 17, in get_askreddit_threads
    reddit = praw.Reddit(
  File "C:\Users\twann\AppData\Local\Programs\Python\Python39\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\twann\AppData\Local\Programs\Python\Python39\lib\site-packages\praw\reddit.py", line 258, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing.
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.

why does this happen? it says that the client id is missing but i am sure that it is in the correct place.

**Comment by sureyes0** [comment]
I'm getting the same error, but I am on MacBook, even though I have the file named .env, and I have my client ID in the correct place.

**Comment by elebumm** [comment]
Are you able to send a screenshot of your file directory in something like Visual Studio Code

**Comment by FreebieII** [comment]
> Are you able to send a screenshot of your file directory in something like Visual Studio Code

Hi @twannieboyy and @sureyes0 

I hope you were able to resolve your issue as there has not been activity in this Issue, I will be closing this for the time being. Feel free to re-open the issue if it has not been solved!!

Happy Coding!
