### ISSUE TITLE
Problems when running the bot.

### ISSUE THREAD

**Issue by CodingBreadd** [elebumm/RedditVideoMakerBot#870]
**Describe the bug**
I decided to run the code. I chose the "StreamlabsPolly" it did it's thing and when it launches "Headless Browser" it crashes into this error: (BTW i changed the text in TTS/streamlabs_polly.py from voice to STREAMLABS_VOICE)

Downloading the backgrounds videos... please be patient 🙏 
Downloading parkour.mp4 from https://www.youtube.com/watch?v=n_Dv4JMiwK8
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Claudia/Desktop/Reddit/RedditVideoMakerBot-2.2.2/main.py", line 70, in <module>
    main()
  File "/Users/Claudia/Desktop/Reddit/RedditVideoMakerBot-2.2.2/main.py", line 39, in main
    download_background()
  File "/Users/Claudia/Desktop/Reddit/RedditVideoMakerBot-2.2.2/video_creation/background.py", line 50, in download_background
    YouTube(uri).streams.filter(res="1080p").first().download(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Screenshots**
![Captură de ecran din 2022-07-06 la 16 55 43](https://user-images.githubusercontent.com/108622594/177567159-316d9d4f-ac99-4ff5-8477-7b85a4a75408.png)
![Captură de ecran din 2022-07-06 la 16 55 40](https://user-images.githubusercontent.com/108622594/177567200-b114bb9b-f915-4543-a78f-58e0dac860cb.png)
![Captură de ecran din 2022-07-06 la 16 55 35](https://user-images.githubusercontent.com/108622594/177567230-96b14b49-5465-48cb-ae8d-ee4da00a8dac.png)

**System (please complete the following information):**

- Python Version: 2.7 (I use pip3 and python3)
- OS: Mac OS Catalina
- App version / Branch: V2.2

**Comment by William9923** [comment]
Thx for the issue.
First, I just want to verify. The Python version that the bot support is > 3.10, so make sure that you use the Python version correctly.
Second, from the error message, it seems that the headless browser unable to open reddit page.
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>`
Is reddit blocked in your country?

**Comment by CodingBreadd** [comment]
Hey! I tried rn to join the reddit and it worked perfectly fine. I also generated videos on my pc here so there is no problem. I can't access it because im in country side but here is the ScreenShot
![Captură de ecran din 2022-07-06 la 17 33 28](https://user-images.githubusercontent.com/108622594/177575754-93764811-4697-4df9-9b34-4670938fb4fd.png)

**Comment by William9923** [comment]
when im researching on these issue, i found this [ref](https://stackoverflow.com/questions/68275857/urllib-error-urlerror-urlopen-error-ssl-certificate-verify-failed-certifica). Might be worth your time to check it out...

**Comment by JasonLovesDoggo** [comment]
https://stackoverflow.com/a/70495761/18516611
