### ISSUE TITLE
Error when running bot

### ISSUE THREAD

**Issue by urxnot** [elebumm/RedditVideoMakerBot#871]
Using United Kingdom server backend.
Traceback (most recent call last):
  File "C:\Users\Jellybean\Desktop\everything\1 RedditVideoMakerBot\main.py", line 15, in <module>
    from video_creation.voices import save_text_to_mp3
  File "C:\Users\Jellybean\Desktop\everything\1 RedditVideoMakerBot\video_creation\voices.py", line 9, in <module>
    from TTS.streamlabs_polly import StreamlabsPolly
  File "C:\Users\Jellybean\Desktop\everything\1 RedditVideoMakerBot\TTS\streamlabs_polly.py", line 4, in <module>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (C:\Users\Jellybean\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\exceptions.py)

**Comment by JasonLovesDoggo** [comment]
Update python
