### ISSUE TITLE
Error when running bot

### ISSUE THREAD

**Issue by TrojansSuck** [elebumm/RedditVideoMakerBot#875]
well so im supposed to have both the template and .env file, but whenever i do that it gives me this error, then when i remove one of them it gives me an error at the end where the mp3 cant extract. 
here is the error when i have both files
Traceback (most recent call last):
  File "D:\Git\clonedr\RedditVideoMakerBot\main.py", line 49, in <module>
    if check_env() is not True:
  File "D:\Git\clonedr\RedditVideoMakerBot\utils\checker.py", line 51, in check_env
    bounds[req_envs[-1]] = tuple(
  File "D:\Git\clonedr\RedditVideoMakerBot\utils\checker.py", line 53, in <lambda>
    lambda x: float(x) if x != "None" else None,
ValueError: could not convert string to float: '8None'

error when i have one file
**Couldn't find .env.template. Unable to check variables.**
Traceback (most recent call last):
  File "D:\Git\clonedr\RedditVideoMakerBot\main.py", line 54, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "D:\Git\clonedr\RedditVideoMakerBot\main.py", line 44, in run_many
    main()
  File "D:\Git\clonedr\RedditVideoMakerBot\main.py", line 32, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
NameError: name 'save_text_to_mp3' is not defined

**Comment by JasonLovesDoggo** [comment]
update to new version of develop.

**Comment by TrojansSuck** [comment]
> update to new version of develop.

how? i just only started python and don't really understand much
