### ISSUE TITLE
error when running main,py

### ISSUE THREAD

**Issue by Scar-Macaw** [elebumm/RedditVideoMakerBot#878]
Logging into Reddit.
Traceback (most recent call last):
  File "C:\Users\Name\Downloads\RedditVideoMakerBot-2.1\RedditVideoMakerBot-2.1\main.py", line 71, in <module>
    main()
  File "C:\Users\Name\Downloads\RedditVideoMakerBot-2.1\RedditVideoMakerBot-2.1\main.py", line 48, in main
    reddit_object = get_obj()
  File "C:\Users\Name\Downloads\RedditVideoMakerBot-2.1\RedditVideoMakerBot-2.1\main.py", line 45, in get_obj
    reddit_obj = get_subreddit_threads()
  File "C:\Users\Name\Downloads\RedditVideoMakerBot-2.1\RedditVideoMakerBot-2.1\reddit\subreddit.py", line 41, in get_subreddit_threads
    reddit = praw.Reddit(
  File "C:\Users\Name\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "C:\Users\Name\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\praw\reddit.py", line 258, in __init__
    raise MissingRequiredAttributeException(
praw.exceptions.MissingRequiredAttributeException: Required configuration setting 'client_id' missing.
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.

**Comment by vincemonte** [comment]
Scar, 

It seems that you are lacking a proper client_id for the Reddit App needed to run the script. 

Essentially, for Reddit's API to allow access to the script (through your account) you must first set up a Reddit App and provide the necessary credentials to the script. 

Here is a guide on how to set that up: [How to Use the Reddit API in Python](https://towardsdatascience.com/how-to-use-the-reddit-api-in-python-5e05ddfd1e5c)

- Select Script as the Type
- The value for Personal Use Script is the client_id (see the article linked above for more details)

If you've gone through this, can you provide further details/screenshots?

Hope this helped!

-- @vincemonte

**Comment by Scar-Macaw** [comment]
the odd thing is i already have my client id and secret id in the .env file, is there somewhere else i need to put it?

**Comment by Gh0stSim0n** [comment]
> 

what do you mean by update to latest version of develop
