### ISSUE TITLE
Crash When Using a Post with No Comments

### ISSUE THREAD

**Issue by vincemonte** [elebumm/RedditVideoMakerBot#881]
### **Description**
When a specified (arbitrary) subreddit's post contains no comments, the script will crash as it expects comments to pull from. 

### **To Reproduce**

1. Specify a subreddit (perhaps an unpopular one) within the .env config file 
   - *optional*: Specify a post in that subreddit with no comments
2. Run the main.py file
3. **Compare with a post that has comments**

### **Expected behavior**
- If a post is specified within a subreddit, and that post has no comments, the script should advise you to select a post with comments
- If no post is specified, the script should continue looking for a post with comments within the subreddit 

### ***Traceback***
`Traceback (most recent call last):
  File "C:\Users\vince\PythonCode\RedditVideoMakerBot\main.py", line 59, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))

  File "C:\Users\vince\PythonCode\RedditVideoMakerBot\main.py", line 49, in run_many
    main()

  File "C:\Users\vince\PythonCode\RedditVideoMakerBot\main.py", line 38, in main
    download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "C:\Users\vince\PythonCode\RedditVideoMakerBot\video_creation\screenshot_downloader.py", line 53, in download_screenshots_of_reddit_posts
    page.locator(

  File "C:\Users\vince\anaconda3\envs\.venv_reddit\lib\site-packages\playwright\sync_api\_generated.py", line 12230, in click
    self._sync(

  File "C:\Users\vince\anaconda3\envs\.venv_reddit\lib\site-packages\playwright\_impl\_sync_base.py", line 89, in _sync
    return task.result()

  File "C:\Users\vince\anaconda3\envs\.venv_reddit\lib\site-packages\playwright\_impl\_locator.py", line 144, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Users\vince\anaconda3\envs\.venv_reddit\lib\site-packages\playwright\_impl\_frame.py", line 474, in click
    await self._channel.send("click", locals_to_params(locals()))

  File "C:\Users\vince\anaconda3\envs\.venv_reddit\lib\site-packages\playwright\_impl\_connection.py", line 43, in send
    return await self._connection.wrap_api_call(

  File "C:\Users\vince\anaconda3\envs\.venv_reddit\lib\site-packages\playwright\_impl\_connection.py", line 370, in _
    return await result

  File "C:\Users\vince\anaconda3\envs\.venv_reddit\lib\site-packages\playwright\_impl\_connection.py", line 78, in inner_send
    result = next(iter(done)).result()

playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-click-id="text"] button"
============================================================`

#### **System (Irrelevant for this bug):**

- Python Version: Python 3.9
- OS: Windows 10
- latest/master

**Comment by JasonLovesDoggo** [comment]
ile add a check.
