### ISSUE TITLE
OSError: input_filepath assets/temp/mp3/title.mp3 does not exist.

### ISSUE THREAD

**Issue by CodingBreadd** [elebumm/RedditVideoMakerBot#893]
**Describe the bug**
When i try to run the file it gives me this error:

Traceback (most recent call last):
  File "C:\Users\Crownboo\AppData\Local\Programs\Python\Python39\lib\site-packages\mutagen\_util.py", line 251, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\MINGW\RedditVideoMakerBot-2.2.2\TTS\engine_wrapper.py", line 98, in call_tts
    self.length += MP3(f"{self.path}/{filename}.mp3").info.length
  File "C:\Users\Crownboo\AppData\Local\Programs\Python\Python39\lib\site-packages\mutagen\_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "C:\Users\Crownboo\AppData\Local\Programs\Python\Python39\lib\site-packages\mutagen\_util.py", line 154, in wrapper
    with _openfile(self, filething, filename, fileobj,
  File "C:\Users\Crownboo\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Users\Crownboo\AppData\Local\Programs\Python\Python39\lib\site-packages\mutagen\_util.py", line 272, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'assets/temp/mp3/title.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\MINGW\RedditVideoMakerBot-2.2.2\main.py", line 70, in <module>
    main()
  File "M:\MINGW\RedditVideoMakerBot-2.2.2\main.py", line 37, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "M:\MINGW\RedditVideoMakerBot-2.2.2\video_creation\voices.py", line 49, in save_text_to_mp3
    return text_to_mp3.run()
  File "M:\MINGW\RedditVideoMakerBot-2.2.2\TTS\engine_wrapper.py", line 58, in run
    self.call_tts("title", self.reddit_object["thread_title"])
  File "M:\MINGW\RedditVideoMakerBot-2.2.2\TTS\engine_wrapper.py", line 100, in call_tts
    self.length += sox.file_info.duration(f"{self.path}/{filename}.mp3")
  File "C:\Users\Crownboo\AppData\Local\Programs\Python\Python39\lib\site-packages\sox\file_info.py", line 121, in duration
    validate_input_file(input_filepath)
  File "C:\Users\Crownboo\AppData\Local\Programs\Python\Python39\lib\site-packages\sox\file_info.py", line 248, in validate_input_file
    raise IOError(
OSError: input_filepath assets/temp/mp3/title.mp3 does not exist.

**System (please complete the following information):**

- Python Version: Python 3.9
- OS: Windows 11
- App version / Branch: Latest

**Comment by matichek** [comment]
Yes, I have the same :).

**Comment by JasonLovesDoggo** [comment]
fixed.
