### ISSUE TITLE
ModuleNotFoundError: No module named 'sox'

### ISSUE THREAD

**Issue by atlanier** [elebumm/RedditVideoMakerBot#895]
C:\Users\atuck\OneDrive\Desktop\RedditVideoMakerBot-2.2.2>python main.py
Using United States server backend.
Traceback (most recent call last):
  File "C:\Users\atuck\OneDrive\Desktop\RedditVideoMakerBot-2.2.2\main.py", line 15, in <module>
    from video_creation.voices import save_text_to_mp3
  File "C:\Users\atuck\OneDrive\Desktop\RedditVideoMakerBot-2.2.2\video_creation\voices.py", line 7, in <module>
    from TTS.engine_wrapper import TTSEngine
  File "C:\Users\atuck\OneDrive\Desktop\RedditVideoMakerBot-2.2.2\TTS\engine_wrapper.py", line 7, in <module>
    import sox
ModuleNotFoundError: No module named 'sox'

This is what i get when i run main.py

**Comment by atlanier** [comment]
I have figured it out.  I installed sox for Python2 not Python3, Sorry for your time.

**Comment by washeido** [comment]
how did you install sox differently?
