### ISSUE TITLE
OSError: MoviePy error: the file assets/mp3/0.mp3 could not be found! 

### ISSUE THREAD

**Issue by piotr4256** [elebumm/RedditVideoMakerBot#902]
![Bez tytułu](https://user-images.githubusercontent.com/108935483/177988822-dc21ee34-f491-4dfe-afce-01bf2e4ae137.png)
 
The problem occurs when creating the final video. How to fix that?

**Comment by kunal5hah** [comment]
The issue is being addressed here.
https://github.com/elebumm/RedditVideoMakerBot/issues/822

**Comment by dylannalex** [comment]
I'm having a similar issue with the new version _RedditVideoMakerBot-v3.0.1_. When running `main.py`, at the phase of _"Creating the final video 🎥"_
it raises:

```
Traceback (most recent call last):
  File "D:\root\repos\bots\reddit_bot\RedditVideoMakerBot\main.py", line 115, in <module>
    raise err
  File "D:\root\repos\bots\reddit_bot\RedditVideoMakerBot\main.py", line 99, in <module>
    run_many(config["settings"]["times_to_run"])
  File "D:\root\repos\bots\reddit_bot\RedditVideoMakerBot\main.py", line 63, in run_many
    main()
  File "D:\root\repos\bots\reddit_bot\RedditVideoMakerBot\main.py", line 55, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "D:\root\repos\bots\reddit_bot\RedditVideoMakerBot\video_creation\final_video.py", line 116, in make_final_video
    audio_clips = [
  File "D:\root\repos\bots\reddit_bot\RedditVideoMakerBot\video_creation\final_video.py", line 117, in <listcomp>
    AudioFileClip(f"assets/temp/{reddit_id}/mp3/{i}.mp3")
  File "D:\root\repos\bots\reddit_bot\RedditVideoMakerBot\venv\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "D:\root\repos\bots\reddit_bot\RedditVideoMakerBot\venv\lib\site-packages\moviepy\audio\io\readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "D:\root\repos\bots\reddit_bot\RedditVideoMakerBot\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file assets/temp/115gfl5/mp3/5.mp3 could not be found!
Please check that you entered the correct path.
```
And here is the `assets\` folder it created
![image](https://user-images.githubusercontent.com/59183947/219901807-319e47db-fd72-4377-9a3f-d6ca45dc8a14.png)

The weird thing is that if I remove the virtual environment and reinstall all dependencies it works, but once a video is successfully created, it stops working for the next videos because of this bug. 

**System Information**

Operating System : Windows 10
Python version : Python 3.10.10
