### ISSUE TITLE
main.py error when ran

### ISSUE THREAD

**Issue by TrojansSuck** [elebumm/RedditVideoMakerBot#906]
whenever i execute the python file it shows this
Traceback (most recent call last):
File "D:\Git\clonedr\RedditVideoMakerBot\main.py", line 49, in
if check_env() is not True:
File "D:\Git\clonedr\RedditVideoMakerBot\utils\checker.py", line 51, in check_env
bounds[req_envs[-1]] = tuple(
File "D:\Git\clonedr\RedditVideoMakerBot\utils\checker.py", line 53, in
lambda x: float(x) if x != "None" else None,
ValueError: could not convert string to float: '8None'
(someone tried to help me before, but I didn't understand how to do what they said.)

**Comment by William9923** [comment]
Hi @TrojansSuck , if possible, could you also state the version you are using? Im pretty sure the newest version is not using `checker.py` file. Thanks 🙏

**Comment by TrojansSuck** [comment]
> Hi @TrojansSuck , if possible, could you also state the version you are using? Im pretty sure the newest version is not using `checker.py` file. Thanks 🙏

Hello, sorry for the late reply, I was on vacation.
I'm using python 3.10 from windows store cause command prompt wont work without it.
