### ISSUE TITLE
Python Version Problem

### ISSUE THREAD

**Issue by augis5654** [elebumm/RedditVideoMakerBot#920]
PS C:\Users\augus\OneDrive\This PC\RedditVideoMakerBot-master> python main.py 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\augus\OneDrive\This PC\RedditVideoMakerBot-master\reddit\subreddit.py", line 9, in <module>
    from utils.videos import check_done
  File "C:\Users\augus\OneDrive\This PC\RedditVideoMakerBot-master\utils\videos.py", line 12, in <module>
    redditobj: dict[str],
TypeError: 'type' object is not subscriptable

What can i do to fix this problem? I am quite new so i need some help.

**Comment by c-v-meyer** [comment]
Please run
`python3 --version`
and post the results

**Comment by JasonLovesDoggo** [comment]
Fixed

**Comment by augis5654** [comment]
> 

![image](https://user-images.githubusercontent.com/108991494/178588856-21d909be-05d0-460d-bf3d-04a80dc1d982.png)
