### ISSUE TITLE
Running with docker

### ISSUE THREAD

**Issue by EbadiDev** [elebumm/RedditVideoMakerBot#938]
**Is your feature request related to a problem? Please describe.**

I'm new to docker and trying to build it and run it through railway website with docker 
It's build well but not going to run, getting some python errors
**Describe the solution you'd like**

**Errors**
`Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
File "main.py", line 6, in <module>
from reddit.subreddit import get_subreddit_threads
File "/app/reddit/subreddit.py", line 9, in <module>
from utils.videos import check_done
File "/app/utils/videos.py", line 12, in <module>
redditobj: dict[str],
TypeError: 'type' object is not subscriptable`

**Additional context** (optional)

![image](https://user-images.githubusercontent.com/7106201/178139267-27fac5de-6376-4325-8031-0de2e64084b1.png)

**Comment by EbadiDev** [comment]
on heroku everything works well
