### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'casefold'

### ISSUE THREAD

**Issue by justin321123** [elebumm/RedditVideoMakerBot#939]
**Describe the bug**
Everyone time i run it it gives this error: 
`Traceback (most recent call last):
  File "C:\Users\justi\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 70, in <module>
    main()
  File "C:\Users\justi\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 36, in main
    reddit_object = get_subreddit_threads(POST_ID)
  File "C:\Users\justi\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\reddit\subreddit.py", line 29, in get_subreddit_threads
    if username.casefold().startswith("u/"):
AttributeError: 'NoneType' object has no attribute 'casefold'

**System (please complete the following information):**

- Python Version: Python 3.9.13
- OS: Windows 10
- App: VS Code

**Comment by JasonLovesDoggo** [comment]
Use the develop branch
