### ISSUE TITLE
Error starting the program!

### ISSUE THREAD

**Issue by phoenixMCode** [elebumm/RedditVideoMakerBot#942]
This happens everytime i run the code 
Couldn't find .env.template. Unable to check variables.
Logging into Reddit.
Traceback (most recent call last):
  File "C:\Users\foodi\Downloads\Redditmaker\RedditVideoMakerBot-master\main.py", line 70, in <module>
    main()
  File "C:\Users\foodi\Downloads\Redditmaker\RedditVideoMakerBot-master\main.py", line 36, in main
    reddit_object = get_subreddit_threads(POST_ID)
  File "C:\Users\foodi\Downloads\Redditmaker\RedditVideoMakerBot-master\reddit\subreddit.py", line 29, in get_subreddit_threads
    if username.casefold().startswith("u/"):
AttributeError: 'NoneType' object has no attribute 'casefold'

**Comment by Ziipen** [comment]
Hey buddy!

Try using the development branch :-)

**Comment by phoenixMCode** [comment]
> Hey buddy!
> 
> Try using the development branch :-)

hey, thanks for the early reply, i got a new error when i tried the dev branch

File "C:\Users\foodi\Downloads\RedditVideoMakerBot-develop\RedditVideoMakerBot-develop\main.py", line 5, in <module>
    from reddit.subreddit import get_subreddit_threads
  File "C:\Users\foodi\Downloads\RedditVideoMakerBot-develop\RedditVideoMakerBot-develop\reddit\subreddit.py", line 3, in <module>
    from utils import settings
  File "C:\Users\foodi\Downloads\RedditVideoMakerBot-develop\RedditVideoMakerBot-develop\utils\settings.py", line 2, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'


looks like i might be missing something im just not sure what that is

**Comment by CordlessCoder** [comment]
@phoenixMCode install the requirements.
`pip3 install -r requirements.txt`

**Comment by phoenixMCode** [comment]
> @phoenixMCode install the requirements. `pip3 install -r requirements.txt`

Hey, it opened by it seems like its still having issues with toml, the module is downloaded  installed but i get this

Encountered error when trying to to load .config.template.toml: [Errno 2] No such file or directory:
'.config.template.toml'

thanks!

**Comment by CordlessCoder** [comment]
Did you touch that file?

**Comment by phoenixMCode** [comment]
> 

No, i installed the requirements then tried to run it imediatly after, can i re-install?

**Comment by CordlessCoder** [comment]
You need to be in the correct directory when running the file

**Comment by CordlessCoder** [comment]
I'm the same directory as main.py specifically

**Comment by phoenixMCode** [comment]
> I'm the same directory as main.py specifically

I think i got it, tried to do a runthrough and just trying to find the output now LMAO

**Comment by William9923** [comment]
I think we could close this issue 🙏
