### ISSUE TITLE
bugs in different lines

### ISSUE THREAD

**Issue by pikpika** [elebumm/RedditVideoMakerBot#944]
bugs in different lines https://gyazo.com/b13baf13d19bcf54e6294c8ab9a22e15

**Comment by pikpika** [comment]
Traceback (most recent call last):
  File "D:\Github-rik\RedditVideoMakerBot-master (2)\RedditVideoMakerBot-master\main.py", line 59, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "D:\Github-rik\RedditVideoMakerBot-master (2)\RedditVideoMakerBot-master\main.py", line 49, in run_many
    main()
  File "D:\Github-rik\RedditVideoMakerBot-master (2)\RedditVideoMakerBot-master\main.py", line 41, in main
    make_final_video(number_of_comments, length, reddit_object)
  File "D:\Github-rik\RedditVideoMakerBot-master (2)\RedditVideoMakerBot-master\video_creation\final_video.py", line 47, in make_final_video
    audio_clips = [AudioFileClip(f"assets/temp/mp3/{i}.mp3") for i in range(number_of_clips)]
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by William9923** [comment]
Is this the last version? (v2.2.2)?

**Comment by JasonLovesDoggo** [comment]
fixed.

**Comment by Haidule** [comment]
what was the problem ?
