### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by ass-warrior** [elebumm/RedditVideoMakerBot#947]
so basically every time i run the bot it gives me this error

Traceback (most recent call last):
  File "C:\Users\User\RedditVideoMakerBot\main.py", line 61, in <module>
    main()
  File "C:\Users\User\RedditVideoMakerBot\main.py", line 27, in main
    reddit_object = get_subreddit_threads(POST_ID)
  File "C:\Users\User\RedditVideoMakerBot\reddit\subreddit.py", line 77, in get_subreddit_threads
    print_substep(f"Video will be: {submission.title} :thumbsup:", style="bold green")
  File "C:\Users\User\RedditVideoMakerBot\utils\console.py", line 29, in print_substep
    console.print(text, style=style)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1635, in print
    with self:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 838, in __exit__
    self._exit_buffer()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 796, in _exit_buffer
    self._check_buffer()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1988, in _check_buffer
    legacy_windows_render(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_win32_console.py", line 418, in write_styled
    self.write_text(text)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_win32_console.py", line 379, in write_text
    self.write(text)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f44d' in position 74: character maps to <undefined>

- Python Version: python 3.10
- OS: windows 10
- App version master

**Comment by William9923** [comment]
hi, could we see the POST_ID value? (in the .env file)

**Comment by ass-warrior** [comment]
POST_ID=""
i mean it said to put something if you want a specific post so i left it blank

**Comment by William9923** [comment]
i think this issue happens on specific Reddit Title Video (edge case). If you happen to still save the Reddit post it would be great

**Comment by ass-warrior** [comment]
unfortunately i dont but this happens every time i try to run the bot reguardless of the post that gets chosen

**Comment by JasonLovesDoggo** [comment]
use 2.3
