### ISSUE TITLE
*Unable to read first frame* error when completing the video

### ISSUE THREAD

**Issue by Unavailable-11** [elebumm/RedditVideoMakerBot#973]
When I tried making a video, it gave me an error saying *unable to find .env template. Unable to check variable* but it still continued with the video-making process but at the end, it gave me this error :

Traceback (most recent call last):
  File "C:\Users\~\Downloads\RedditVideoMakerBot-master\main.py", line 59, in <module>
    run_many(int(getenv("TIMES_TO_RUN")))
  File "C:\Users\~\Downloads\RedditVideoMakerBot-master\main.py", line 49, in run_many
    main()
  File "C:\Users\~\Downloads\RedditVideoMakerBot-master\main.py", line 41, in main
    make_final_video(number_of_comments, length, reddit_object)
  File "C:\Users\~\Downloads\RedditVideoMakerBot-master\video_creation\final_video.py", line 40, in make_final_video
    VideoFileClip("assets/temp/background.mp4")
  File "C:\Users\~\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\~\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "C:\Users\~\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

I checked and double-checked the file, it was set up correctly and all the info matches and interestingly enough when I set it to 3 repeats it synced with 3 despite saying it could load my variables. I'm on windows 10, Python 3.10, and I just downloaded the file today should it all should be up to date. Sox and everything else is working fine so I don't know what it is. (The environment variable is also set up as well idk if it affects this.) Can you please help as I'm not too good at this stuff.

**Comment by JasonLovesDoggo** [comment]
Fixed in develop

**Comment by Unavailable-11** [comment]
but what does that mean?

**Comment by JasonLovesDoggo** [comment]
> but what does that mean?

download the develop branch or wait like an hr for 2.3 to be released
