### ISSUE TITLE
Cannot create final video

### ISSUE THREAD

**Issue by quandaledingleofficial** [elebumm/RedditVideoMakerBot#976]
**Describe the bug**
Everything works fine until its time to make the final video. A bunch of things show up, the main point being that it cannot read the background video it just chopped. 

**To Reproduce**
Not sure; I was just running the script

**Expected behavior**

`Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command successful
Background video chopped successfully!
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Creating the final video 🎥                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "C:\Users\s2660\Downloads\RedditVideoMakerBot-master (1)\RedditVideoMakerBot-master\main.py", line 65, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\s2660\Downloads\RedditVideoMakerBot-master (1)\RedditVideoMakerBot-master\main.py", line 56, in run_many
    main()
  File "C:\Users\s2660\Downloads\RedditVideoMakerBot-master (1)\RedditVideoMakerBot-master\main.py", line 48, in main
    make_final_video(number_of_comments, length, reddit_object, bg_config)
  File "C:\Users\s2660\Downloads\RedditVideoMakerBot-master (1)\RedditVideoMakerBot-master\video_creation\final_video.py", line 68, in make_final_video
    VideoFileClip("assets/temp/background.mp4")
  File "C:\Users\s2660\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 88, in __init__
    self.reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt,
  File "C:\Users\s2660\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "C:\Users\s2660\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file assets/temp/background.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.`

**Screenshots**

![image](https://user-images.githubusercontent.com/103541955/178566965-5fca5863-db59-42af-85bf-9edeb3e09759.png)

**System (please complete the following information):**

- Python Version: Python 3.10
- OS: Windows 10
- App version / Branch: Latest

**Comment by kikijoko** [comment]
Same error here

**Comment by JasonLovesDoggo** [comment]
update FFMPEG

**Comment by quandaledingleofficial** [comment]
I did, twice. From the official website.

**Comment by StopmotionSimonYT** [comment]
Maybe try to delete the background video's and download them again

**Comment by kikijoko** [comment]
I did all of the above and it didnt solve it

**Comment by KPGNED** [comment]
same, can't find the file/final project anywhere. maby delete the config.toml?

**Comment by KPGNED** [comment]
i deleted the config.toml file, it works now with no errors but i need to do it with the default. i think it something in the settings... just Y everything. give it a try and let's hope its works.

**Comment by kikijoko** [comment]
I set a different background and it runs okay now
