### ISSUE TITLE
Unable to download NSFW screenshots

### ISSUE THREAD

**Issue by sahedge-was-taken** [elebumm/RedditVideoMakerBot#978]
### When downloading screenshots from NSFW posts the process ends with:
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Downloading screenshots of reddit posts... │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Launching Headless Browser...
Post is NSFW. You are spicy...
Traceback (most recent call last):
File "c:\Users\sb\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 71, in
main()
File "c:\Users\sb\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\main.py", line 50, in main
download_screenshots_of_reddit_posts(reddit_object, number_of_comments)
File "c:\Users\sb\Downloads\RedditVideoMakerBot-master\RedditVideoMakerBot-master\video_creation\screenshot_downloader.py", line 52, in download_screenshots_of_reddit_posts
).click() # Remove "Click to see nsfw" Button in Screenshot
File "C:\Users\sb\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api_generated.py", line 12327, in click
self._sync(
File "C:\Users\sb\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_sync_base.py", line 88, in _sync
return task.result()
File "C:\Users\sb\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_locator.py", line 144, in click
return await self._frame.click(self._selector, strict=True, **params)
File "C:\Users\sb\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_frame.py", line 460, in click
await self._channel.send("click", locals_to_params(locals()))
File "C:\Users\sb\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_connection.py", line 39, in send
return await self.inner_send(method, params, False)
File "C:\Users\sb\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright_impl_connection.py", line 63, in inner_send
result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "[data-click-id="text"] button"

### **To Reproduce**
- Enable NSFW
- Attempt to process a NSFW post

### **Expected behavior**
Continue with downloaded screenshots like SFW posts.

### **System**

- Python Version: Python 3.10.2
- OS: Win 11
- App version: 2.3

**Additional context**
#649 is a similar issue that has been closed without a resolution/solution.
tysm :)

**Comment by StopmotionSimonYT** [comment]
Is this only with NSFW or does the error also happen with non NSFW?

**Comment by JasonLovesDoggo** [comment]
> Is this only with NSFW or does the error also happen with non NSFW?

this will only happen on NSFW

**Comment by sahedge-was-taken** [comment]
Thank you so much @JasonLovesDoggo. This fixed the issue :)

**Comment by JasonLovesDoggo** [comment]
> Thank you so much @JasonLovesDoggo. This fixed the issue :)

Np!
