### ISSUE TITLE
the translator does not work in some languages

### ISSUE THREAD

**Issue by lixaioy** [elebumm/RedditVideoMakerBot#995]
I translate the text into Ukrainian, put Uk in the language parameters.  I use Google Translate for TTS, so it only supports the Ukrainian language out of all options.  When starting the bot, I get the following error
`Translating Text...
Saving... ----------------------------------------   Translating Text...
Saving... ----------------------------------------   Translating Text...
Saving... ----------------------------------------   Translating Text...
Saving... ---------------------------------------- 0.9 it/s  Translating Text...
Saving... ---------------------------------------- 0.9 it/s
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\main.py", line 65, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\main.py", line 56, in run_many
    main()
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\main.py", line 42, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\video_creation\voices.py", line 48, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\TTS\engine_wrapper.py", line 73, in run
    self.split_post(comment["comment_body"], idx)  # Split the comment
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\TTS\engine_wrapper.py", line 95, in split_post
    self.call_tts(f"{idx}-{idy - offset}.part", text_cut)
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\TTS\engine_wrapper.py", line 113, in call_tts
    self.tts_module.run(text=process_text(text), filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\TTS\GTTS.py", line 15, in run
    tts = gTTS(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 134, in __init__
    assert text, "No text to speak"
AssertionError: No text to speak`

In standard English, everything works flawlessly, for which many thanks to the developers!

**Comment by lixaioy** [comment]
The title post is translated normally, you can listen to it in temporary files.  But the comments are not voiced or translated at all

**Comment by lixaioy** [comment]
I clicked something, now it gives such an error
`Saving... ----------------------------------------
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\main.py", line 65, in <module>
    run_many(config["settings"]["times_to_run"])
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\main.py", line 56, in run_many
    main()
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\main.py", line 42, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\video_creation\voices.py", line 48, in save_text_to_mp3
    return text_to_mp3.run()
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\TTS\engine_wrapper.py", line 73, in run
    self.split_post(comment["comment_body"], idx)  # Split the comment
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\TTS\engine_wrapper.py", line 95, in split_post
    self.call_tts(f"{idx}-{idy - offset}.part", text_cut)
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\TTS\engine_wrapper.py", line 113, in call_tts
    self.tts_module.run(text=process_text(text), filepath=f"{self.path}/{filename}.mp3")
  File "C:\Users\admin\Desktop\RedditVideoMakerBot\TTS\GTTS.py", line 20, in run
    tts.save(filepath)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 329, in save
    self.write_to_fp(f)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 310, in write_to_fp
    for idx, decoded in enumerate(self.stream()):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 260, in stream
    prepared_requests = self._prepare_requests()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gtts\tts.py", line 209, in _prepare_requests
    assert text_parts, "No text to send to TTS API"
AssertionError: No text to send to TTS API
`

**Comment by JasonLovesDoggo** [comment]
are you using 2.3?

**Comment by JasonLovesDoggo** [comment]
> How to check? I just downloaded it today, so it's probably true

look in main.py and see what the __VERSION__ or VERSION variable says

**Comment by lixaioy** [comment]
Checked, version 2.3

**Comment by JasonLovesDoggo** [comment]
Will be fixed alongside of. #1006
